// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_lockouts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredLockouts = `-- name: CleanupExpiredLockouts :exec
UPDATE account_lockouts SET 
    active = false
WHERE unlocks_at <= NOW() AND active = true
`

func (q *Queries) CleanupExpiredLockouts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredLockouts)
	return err
}

const createAccountLockout = `-- name: CreateAccountLockout :one
INSERT INTO account_lockouts (
    user_id, email, ip_address, reason, unlocks_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, email, ip_address, reason, locked_at, unlocks_at, active
`

type CreateAccountLockoutParams struct {
	UserID    string             `json:"userId"`
	Email     string             `json:"email"`
	IpAddress *string            `json:"ipAddress"`
	Reason    string             `json:"reason"`
	UnlocksAt pgtype.Timestamptz `json:"unlocksAt"`
}

func (q *Queries) CreateAccountLockout(ctx context.Context, arg CreateAccountLockoutParams) (AccountLockout, error) {
	row := q.db.QueryRow(ctx, createAccountLockout,
		arg.UserID,
		arg.Email,
		arg.IpAddress,
		arg.Reason,
		arg.UnlocksAt,
	)
	var i AccountLockout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.IpAddress,
		&i.Reason,
		&i.LockedAt,
		&i.UnlocksAt,
		&i.Active,
	)
	return i, err
}

const getAccountLockoutByEmail = `-- name: GetAccountLockoutByEmail :one
SELECT id, user_id, email, ip_address, reason, locked_at, unlocks_at, active FROM account_lockouts 
WHERE email = $1 AND active = true AND unlocks_at > NOW()
ORDER BY locked_at DESC
LIMIT 1
`

type GetAccountLockoutByEmailParams struct {
	Email string `json:"email"`
}

func (q *Queries) GetAccountLockoutByEmail(ctx context.Context, arg GetAccountLockoutByEmailParams) (AccountLockout, error) {
	row := q.db.QueryRow(ctx, getAccountLockoutByEmail, arg.Email)
	var i AccountLockout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.IpAddress,
		&i.Reason,
		&i.LockedAt,
		&i.UnlocksAt,
		&i.Active,
	)
	return i, err
}

const getAccountLockoutHistory = `-- name: GetAccountLockoutHistory :many
SELECT id, user_id, email, ip_address, reason, locked_at, unlocks_at, active FROM account_lockouts 
WHERE user_id = $1 
ORDER BY locked_at DESC
LIMIT $2 OFFSET $3
`

type GetAccountLockoutHistoryParams struct {
	UserID string `json:"userId"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetAccountLockoutHistory(ctx context.Context, arg GetAccountLockoutHistoryParams) ([]AccountLockout, error) {
	rows, err := q.db.Query(ctx, getAccountLockoutHistory, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountLockout{}
	for rows.Next() {
		var i AccountLockout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.IpAddress,
			&i.Reason,
			&i.LockedAt,
			&i.UnlocksAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveAccountLockout = `-- name: GetActiveAccountLockout :one
SELECT id, user_id, email, ip_address, reason, locked_at, unlocks_at, active FROM account_lockouts 
WHERE user_id = $1 AND active = true AND unlocks_at > NOW()
ORDER BY locked_at DESC
LIMIT 1
`

type GetActiveAccountLockoutParams struct {
	UserID string `json:"userId"`
}

func (q *Queries) GetActiveAccountLockout(ctx context.Context, arg GetActiveAccountLockoutParams) (AccountLockout, error) {
	row := q.db.QueryRow(ctx, getActiveAccountLockout, arg.UserID)
	var i AccountLockout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.IpAddress,
		&i.Reason,
		&i.LockedAt,
		&i.UnlocksAt,
		&i.Active,
	)
	return i, err
}

const unlockAccount = `-- name: UnlockAccount :exec
UPDATE account_lockouts SET 
    active = false
WHERE user_id = $1 AND active = true
`

type UnlockAccountParams struct {
	UserID string `json:"userId"`
}

func (q *Queries) UnlockAccount(ctx context.Context, arg UnlockAccountParams) error {
	_, err := q.db.Exec(ctx, unlockAccount, arg.UserID)
	return err
}

const unlockAccountByEmail = `-- name: UnlockAccountByEmail :exec
UPDATE account_lockouts SET 
    active = false
WHERE email = $1 AND active = true
`

type UnlockAccountByEmailParams struct {
	Email string `json:"email"`
}

func (q *Queries) UnlockAccountByEmail(ctx context.Context, arg UnlockAccountByEmailParams) error {
	_, err := q.db.Exec(ctx, unlockAccountByEmail, arg.Email)
	return err
}
