// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_lockouts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredLockouts = `-- name: CleanupExpiredLockouts :exec
UPDATE account_lockouts SET 
    active = false
WHERE unlocks_at <= NOW() AND active = true
`

func (q *Queries) CleanupExpiredLockouts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredLockouts)
	return err
}

const createAccountLockout = `-- name: CreateAccountLockout :one
INSERT INTO account_lockouts (
    user_id, email, ip_address, reason, unlocks_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, email, ip_address, reason, locked_at, unlocks_at, active
`

func (q *Queries) CreateAccountLockout(ctx context.Context, userID string, email string, ipAddress *string, reason string, unlocksAt pgtype.Timestamptz) (AccountLockout, error) {
	row := q.db.QueryRow(ctx, createAccountLockout,
		userID,
		email,
		ipAddress,
		reason,
		unlocksAt,
	)
	var i AccountLockout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.IpAddress,
		&i.Reason,
		&i.LockedAt,
		&i.UnlocksAt,
		&i.Active,
	)
	return i, err
}

const getAccountLockoutByEmail = `-- name: GetAccountLockoutByEmail :one
SELECT id, user_id, email, ip_address, reason, locked_at, unlocks_at, active FROM account_lockouts 
WHERE email = $1 AND active = true AND unlocks_at > NOW()
ORDER BY locked_at DESC
LIMIT 1
`

func (q *Queries) GetAccountLockoutByEmail(ctx context.Context, email string) (AccountLockout, error) {
	row := q.db.QueryRow(ctx, getAccountLockoutByEmail, email)
	var i AccountLockout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.IpAddress,
		&i.Reason,
		&i.LockedAt,
		&i.UnlocksAt,
		&i.Active,
	)
	return i, err
}

const getAccountLockoutHistory = `-- name: GetAccountLockoutHistory :many
SELECT id, user_id, email, ip_address, reason, locked_at, unlocks_at, active FROM account_lockouts 
WHERE user_id = $1 
ORDER BY locked_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) GetAccountLockoutHistory(ctx context.Context, userID string, limit int32, offset int32) ([]AccountLockout, error) {
	rows, err := q.db.Query(ctx, getAccountLockoutHistory, userID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountLockout{}
	for rows.Next() {
		var i AccountLockout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.IpAddress,
			&i.Reason,
			&i.LockedAt,
			&i.UnlocksAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveAccountLockout = `-- name: GetActiveAccountLockout :one
SELECT id, user_id, email, ip_address, reason, locked_at, unlocks_at, active FROM account_lockouts 
WHERE user_id = $1 AND active = true AND unlocks_at > NOW()
ORDER BY locked_at DESC
LIMIT 1
`

func (q *Queries) GetActiveAccountLockout(ctx context.Context, userID string) (AccountLockout, error) {
	row := q.db.QueryRow(ctx, getActiveAccountLockout, userID)
	var i AccountLockout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.IpAddress,
		&i.Reason,
		&i.LockedAt,
		&i.UnlocksAt,
		&i.Active,
	)
	return i, err
}

const unlockAccount = `-- name: UnlockAccount :exec
UPDATE account_lockouts SET 
    active = false
WHERE user_id = $1 AND active = true
`

func (q *Queries) UnlockAccount(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, unlockAccount, userID)
	return err
}

const unlockAccountByEmail = `-- name: UnlockAccountByEmail :exec
UPDATE account_lockouts SET 
    active = false
WHERE email = $1 AND active = true
`

func (q *Queries) UnlockAccountByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, unlockAccountByEmail, email)
	return err
}
