// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT COUNT(*) FROM audit_logs
WHERE organization_id = $1
  AND document_type = $2
  AND document_id   = $3
`

type CountAuditEventsParams struct {
	OrganizationID string `json:"organizationId"`
	DocumentType   string `json:"documentType"`
	DocumentID     string `json:"documentId"`
}

func (q *Queries) CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents, arg.OrganizationID, arg.DocumentType, arg.DocumentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogs = `-- name: CountAuditLogs :one

SELECT COUNT(*) FROM audit_logs
WHERE organization_id = $1
  AND ($2::text = '' OR action        = $2)
  AND ($3::text = '' OR document_type = $3)
  AND ($4::text = '' OR user_id       = $4)
`

type CountAuditLogsParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Column4        string `json:"column4"`
}

// Audit log queries
// Uses empty-string = skip-filter pattern to avoid nullable params.
// All queries return the full row (no preloads needed for audit logs).
func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentAuditLogs = `-- name: CountDocumentAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE organization_id = $1
  AND document_id = $2
`

type CountDocumentAuditLogsParams struct {
	OrganizationID string `json:"organizationId"`
	DocumentID     string `json:"documentId"`
}

func (q *Queries) CountDocumentAuditLogs(ctx context.Context, arg CountDocumentAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentAuditLogs, arg.OrganizationID, arg.DocumentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, organization_id, document_id, document_type,
       user_id, actor_name, actor_role, action, changes, details, created_at
FROM audit_logs
WHERE organization_id = $1
  AND document_type = $2
  AND document_id   = $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAuditEventsParams struct {
	OrganizationID string `json:"organizationId"`
	DocumentType   string `json:"documentType"`
	DocumentID     string `json:"documentId"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.OrganizationID,
		arg.DocumentType,
		arg.DocumentID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentID,
			&i.DocumentType,
			&i.UserID,
			&i.ActorName,
			&i.ActorRole,
			&i.Action,
			&i.Changes,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, organization_id, document_id, document_type,
       user_id, actor_name, actor_role, action, changes, details, created_at
FROM audit_logs
WHERE organization_id = $1
  AND ($2::text = '' OR action        = $2)
  AND ($3::text = '' OR document_type = $3)
  AND ($4::text = '' OR user_id       = $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListAuditLogsParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Column4        string `json:"column4"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentID,
			&i.DocumentType,
			&i.UserID,
			&i.ActorName,
			&i.ActorRole,
			&i.Action,
			&i.Changes,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentAuditLogs = `-- name: ListDocumentAuditLogs :many
SELECT id, organization_id, document_id, document_type,
       user_id, actor_name, actor_role, action, changes, details, created_at
FROM audit_logs
WHERE organization_id = $1
  AND document_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListDocumentAuditLogsParams struct {
	OrganizationID string `json:"organizationId"`
	DocumentID     string `json:"documentId"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListDocumentAuditLogs(ctx context.Context, arg ListDocumentAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listDocumentAuditLogs,
		arg.OrganizationID,
		arg.DocumentID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentID,
			&i.DocumentType,
			&i.UserID,
			&i.ActorName,
			&i.ActorRole,
			&i.Action,
			&i.Changes,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
