// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package db

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const countBudgets = `-- name: CountBudgets :one
SELECT COUNT(*) FROM budgets 
WHERE organization_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR UPPER(status) = UPPER($2))
  AND ($3::text = '' OR department = $3)
  AND ($4::text = '' OR fiscal_year = $4)
`

type CountBudgetsParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Column4        string `json:"column4"`
}

func (q *Queries) CountBudgets(ctx context.Context, arg CountBudgetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBudgets,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (
    id, organization_id, owner_id, budget_code, department, department_id,
    status, fiscal_year, total_budget, allocated_amount, remaining_amount,
    approval_stage, name, description, currency, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, organization_id, owner_id, budget_code, department, department_id, status, fiscal_year, total_budget, allocated_amount, remaining_amount, approval_stage, approval_history, name, description, currency, created_by, items, action_history, metadata, deleted_at, created_at, updated_at
`

type CreateBudgetParams struct {
	ID              string           `json:"id"`
	OrganizationID  string           `json:"organizationId"`
	OwnerID         string           `json:"ownerId"`
	BudgetCode      string           `json:"budgetCode"`
	Department      *string          `json:"department"`
	DepartmentID    *string          `json:"departmentId"`
	Status          *string          `json:"status"`
	FiscalYear      *string          `json:"fiscalYear"`
	TotalBudget     *decimal.Decimal `json:"totalBudget"`
	AllocatedAmount *decimal.Decimal `json:"allocatedAmount"`
	RemainingAmount *decimal.Decimal `json:"remainingAmount"`
	ApprovalStage   *int32           `json:"approvalStage"`
	Name            *string          `json:"name"`
	Description     *string          `json:"description"`
	Currency        *string          `json:"currency"`
	CreatedBy       *string          `json:"createdBy"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.ID,
		arg.OrganizationID,
		arg.OwnerID,
		arg.BudgetCode,
		arg.Department,
		arg.DepartmentID,
		arg.Status,
		arg.FiscalYear,
		arg.TotalBudget,
		arg.AllocatedAmount,
		arg.RemainingAmount,
		arg.ApprovalStage,
		arg.Name,
		arg.Description,
		arg.Currency,
		arg.CreatedBy,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.BudgetCode,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.FiscalYear,
		&i.TotalBudget,
		&i.AllocatedAmount,
		&i.RemainingAmount,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.Name,
		&i.Description,
		&i.Currency,
		&i.CreatedBy,
		&i.Items,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetByCode = `-- name: GetBudgetByCode :one
SELECT id, organization_id, owner_id, budget_code, department, department_id, status, fiscal_year, total_budget, allocated_amount, remaining_amount, approval_stage, approval_history, name, description, currency, created_by, items, action_history, metadata, deleted_at, created_at, updated_at FROM budgets WHERE organization_id = $1 AND budget_code = $2 AND deleted_at IS NULL
`

type GetBudgetByCodeParams struct {
	OrganizationID string `json:"organizationId"`
	BudgetCode     string `json:"budgetCode"`
}

func (q *Queries) GetBudgetByCode(ctx context.Context, arg GetBudgetByCodeParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByCode, arg.OrganizationID, arg.BudgetCode)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.BudgetCode,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.FiscalYear,
		&i.TotalBudget,
		&i.AllocatedAmount,
		&i.RemainingAmount,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.Name,
		&i.Description,
		&i.Currency,
		&i.CreatedBy,
		&i.Items,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetByID = `-- name: GetBudgetByID :one

SELECT id, organization_id, owner_id, budget_code, department, department_id, status, fiscal_year, total_budget, allocated_amount, remaining_amount, approval_stage, approval_history, name, description, currency, created_by, items, action_history, metadata, deleted_at, created_at, updated_at FROM budgets WHERE id = $1 AND deleted_at IS NULL
`

type GetBudgetByIDParams struct {
	ID string `json:"id"`
}

// Budget queries
// Organization-scoped budget CRUD operations
func (q *Queries) GetBudgetByID(ctx context.Context, arg GetBudgetByIDParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, arg.ID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.BudgetCode,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.FiscalYear,
		&i.TotalBudget,
		&i.AllocatedAmount,
		&i.RemainingAmount,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.Name,
		&i.Description,
		&i.Currency,
		&i.CreatedBy,
		&i.Items,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgets = `-- name: ListBudgets :many
SELECT id, organization_id, owner_id, budget_code, department, department_id, status, fiscal_year, total_budget, allocated_amount, remaining_amount, approval_stage, approval_history, name, description, currency, created_by, items, action_history, metadata, deleted_at, created_at, updated_at FROM budgets 
WHERE organization_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR UPPER(status) = UPPER($2))
  AND ($3::text = '' OR department = $3)
  AND ($4::text = '' OR fiscal_year = $4)
  AND ($5::text = '' OR budget_code ILIKE $5)
ORDER BY created_at DESC
LIMIT $6 OFFSET $7
`

type ListBudgetsParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Column4        string `json:"column4"`
	Column5        string `json:"column5"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListBudgets(ctx context.Context, arg ListBudgetsParams) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgets,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OwnerID,
			&i.BudgetCode,
			&i.Department,
			&i.DepartmentID,
			&i.Status,
			&i.FiscalYear,
			&i.TotalBudget,
			&i.AllocatedAmount,
			&i.RemainingAmount,
			&i.ApprovalStage,
			&i.ApprovalHistory,
			&i.Name,
			&i.Description,
			&i.Currency,
			&i.CreatedBy,
			&i.Items,
			&i.ActionHistory,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseBudget = `-- name: ReleaseBudget :one
UPDATE budgets SET
    allocated_amount = GREATEST(allocated_amount - $2, 0),
    remaining_amount = remaining_amount + $2,
    updated_at       = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, owner_id, budget_code, department, department_id, status, fiscal_year, total_budget, allocated_amount, remaining_amount, approval_stage, approval_history, name, description, currency, created_by, items, action_history, metadata, deleted_at, created_at, updated_at
`

type ReleaseBudgetParams struct {
	ID              string           `json:"id"`
	AllocatedAmount *decimal.Decimal `json:"allocatedAmount"`
}

func (q *Queries) ReleaseBudget(ctx context.Context, arg ReleaseBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, releaseBudget, arg.ID, arg.AllocatedAmount)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.BudgetCode,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.FiscalYear,
		&i.TotalBudget,
		&i.AllocatedAmount,
		&i.RemainingAmount,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.Name,
		&i.Description,
		&i.Currency,
		&i.CreatedBy,
		&i.Items,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveBudget = `-- name: ReserveBudget :one
UPDATE budgets SET
    allocated_amount = allocated_amount + $2,
    remaining_amount = remaining_amount - $2,
    updated_at       = NOW()
WHERE id = $1
  AND deleted_at IS NULL
  AND remaining_amount >= $2
RETURNING id, organization_id, owner_id, budget_code, department, department_id, status, fiscal_year, total_budget, allocated_amount, remaining_amount, approval_stage, approval_history, name, description, currency, created_by, items, action_history, metadata, deleted_at, created_at, updated_at
`

type ReserveBudgetParams struct {
	ID              string           `json:"id"`
	AllocatedAmount *decimal.Decimal `json:"allocatedAmount"`
}

func (q *Queries) ReserveBudget(ctx context.Context, arg ReserveBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, reserveBudget, arg.ID, arg.AllocatedAmount)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.BudgetCode,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.FiscalYear,
		&i.TotalBudget,
		&i.AllocatedAmount,
		&i.RemainingAmount,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.Name,
		&i.Description,
		&i.Currency,
		&i.CreatedBy,
		&i.Items,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteBudget = `-- name: SoftDeleteBudget :exec
UPDATE budgets SET deleted_at = NOW() WHERE id = $1
`

type SoftDeleteBudgetParams struct {
	ID string `json:"id"`
}

func (q *Queries) SoftDeleteBudget(ctx context.Context, arg SoftDeleteBudgetParams) error {
	_, err := q.db.Exec(ctx, softDeleteBudget, arg.ID)
	return err
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets SET 
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    department = COALESCE($4, department),
    department_id = COALESCE($5, department_id),
    status = COALESCE($6, status),
    total_budget = COALESCE($7, total_budget),
    allocated_amount = COALESCE($8, allocated_amount),
    remaining_amount = COALESCE($9, remaining_amount),
    approval_stage = COALESCE($10, approval_stage),
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, owner_id, budget_code, department, department_id, status, fiscal_year, total_budget, allocated_amount, remaining_amount, approval_stage, approval_history, name, description, currency, created_by, items, action_history, metadata, deleted_at, created_at, updated_at
`

type UpdateBudgetParams struct {
	ID              string           `json:"id"`
	Name            *string          `json:"name"`
	Description     *string          `json:"description"`
	Department      *string          `json:"department"`
	DepartmentID    *string          `json:"departmentId"`
	Status          *string          `json:"status"`
	TotalBudget     *decimal.Decimal `json:"totalBudget"`
	AllocatedAmount *decimal.Decimal `json:"allocatedAmount"`
	RemainingAmount *decimal.Decimal `json:"remainingAmount"`
	ApprovalStage   *int32           `json:"approvalStage"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Department,
		arg.DepartmentID,
		arg.Status,
		arg.TotalBudget,
		arg.AllocatedAmount,
		arg.RemainingAmount,
		arg.ApprovalStage,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.BudgetCode,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.FiscalYear,
		&i.TotalBudget,
		&i.AllocatedAmount,
		&i.RemainingAmount,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.Name,
		&i.Description,
		&i.Currency,
		&i.CreatedBy,
		&i.Items,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBudgetAllocatedAmount = `-- name: UpdateBudgetAllocatedAmount :one
UPDATE budgets SET
    allocated_amount = allocated_amount + $2,
    remaining_amount = total_budget - (allocated_amount + $2),
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, owner_id, budget_code, department, department_id, status, fiscal_year, total_budget, allocated_amount, remaining_amount, approval_stage, approval_history, name, description, currency, created_by, items, action_history, metadata, deleted_at, created_at, updated_at
`

type UpdateBudgetAllocatedAmountParams struct {
	ID              string           `json:"id"`
	AllocatedAmount *decimal.Decimal `json:"allocatedAmount"`
}

func (q *Queries) UpdateBudgetAllocatedAmount(ctx context.Context, arg UpdateBudgetAllocatedAmountParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudgetAllocatedAmount, arg.ID, arg.AllocatedAmount)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.BudgetCode,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.FiscalYear,
		&i.TotalBudget,
		&i.AllocatedAmount,
		&i.RemainingAmount,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.Name,
		&i.Description,
		&i.Currency,
		&i.CreatedBy,
		&i.Items,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBudgetRemainingAmount = `-- name: UpdateBudgetRemainingAmount :one
UPDATE budgets SET
    remaining_amount = COALESCE($2, remaining_amount),
    updated_at       = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, owner_id, budget_code, department, department_id, status, fiscal_year, total_budget, allocated_amount, remaining_amount, approval_stage, approval_history, name, description, currency, created_by, items, action_history, metadata, deleted_at, created_at, updated_at
`

type UpdateBudgetRemainingAmountParams struct {
	ID              string           `json:"id"`
	RemainingAmount *decimal.Decimal `json:"remainingAmount"`
}

func (q *Queries) UpdateBudgetRemainingAmount(ctx context.Context, arg UpdateBudgetRemainingAmountParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudgetRemainingAmount, arg.ID, arg.RemainingAmount)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.BudgetCode,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.FiscalYear,
		&i.TotalBudget,
		&i.AllocatedAmount,
		&i.RemainingAmount,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.Name,
		&i.Description,
		&i.Currency,
		&i.CreatedBy,
		&i.Items,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
