// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category_budget_codes.sql

package db

import (
	"context"
)

const countCategoryBudgetCodes = `-- name: CountCategoryBudgetCodes :one
SELECT COUNT(*) FROM category_budget_codes
WHERE category_id = $1
  AND ($2::bool IS NULL OR active = $2)
`

type CountCategoryBudgetCodesParams struct {
	CategoryID string `json:"categoryId"`
	Column2    bool   `json:"column2"`
}

func (q *Queries) CountCategoryBudgetCodes(ctx context.Context, arg CountCategoryBudgetCodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoryBudgetCodes, arg.CategoryID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategoryBudgetCode = `-- name: CreateCategoryBudgetCode :one

INSERT INTO category_budget_codes (
    id, category_id, budget_code, active
) VALUES (
    $1, $2, $3, $4
) RETURNING id, category_id, budget_code, active, created_at, updated_at
`

type CreateCategoryBudgetCodeParams struct {
	ID         string `json:"id"`
	CategoryID string `json:"categoryId"`
	BudgetCode string `json:"budgetCode"`
	Active     *bool  `json:"active"`
}

// Category budget code queries
// Many-to-one mapping of GL/budget codes per category. No deleted_at column.
func (q *Queries) CreateCategoryBudgetCode(ctx context.Context, arg CreateCategoryBudgetCodeParams) (CategoryBudgetCode, error) {
	row := q.db.QueryRow(ctx, createCategoryBudgetCode,
		arg.ID,
		arg.CategoryID,
		arg.BudgetCode,
		arg.Active,
	)
	var i CategoryBudgetCode
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BudgetCode,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategoryBudgetCode = `-- name: DeleteCategoryBudgetCode :exec
DELETE FROM category_budget_codes WHERE id = $1
`

type DeleteCategoryBudgetCodeParams struct {
	ID string `json:"id"`
}

func (q *Queries) DeleteCategoryBudgetCode(ctx context.Context, arg DeleteCategoryBudgetCodeParams) error {
	_, err := q.db.Exec(ctx, deleteCategoryBudgetCode, arg.ID)
	return err
}

const getCategoryBudgetCodeByID = `-- name: GetCategoryBudgetCodeByID :one
SELECT id, category_id, budget_code, active, created_at, updated_at FROM category_budget_codes WHERE id = $1
`

type GetCategoryBudgetCodeByIDParams struct {
	ID string `json:"id"`
}

func (q *Queries) GetCategoryBudgetCodeByID(ctx context.Context, arg GetCategoryBudgetCodeByIDParams) (CategoryBudgetCode, error) {
	row := q.db.QueryRow(ctx, getCategoryBudgetCodeByID, arg.ID)
	var i CategoryBudgetCode
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BudgetCode,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoryBudgetCodesByCategory = `-- name: ListCategoryBudgetCodesByCategory :many
SELECT id, category_id, budget_code, active, created_at, updated_at FROM category_budget_codes
WHERE category_id = $1
  AND ($2::bool IS NULL OR active = $2)
ORDER BY budget_code ASC
`

type ListCategoryBudgetCodesByCategoryParams struct {
	CategoryID string `json:"categoryId"`
	Column2    bool   `json:"column2"`
}

func (q *Queries) ListCategoryBudgetCodesByCategory(ctx context.Context, arg ListCategoryBudgetCodesByCategoryParams) ([]CategoryBudgetCode, error) {
	rows, err := q.db.Query(ctx, listCategoryBudgetCodesByCategory, arg.CategoryID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryBudgetCode{}
	for rows.Next() {
		var i CategoryBudgetCode
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.BudgetCode,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoryBudgetCode = `-- name: UpdateCategoryBudgetCode :one
UPDATE category_budget_codes SET
    budget_code = COALESCE($2, budget_code),
    active      = COALESCE($3, active),
    updated_at  = NOW()
WHERE id = $1
RETURNING id, category_id, budget_code, active, created_at, updated_at
`

type UpdateCategoryBudgetCodeParams struct {
	ID         string `json:"id"`
	BudgetCode string `json:"budgetCode"`
	Active     *bool  `json:"active"`
}

func (q *Queries) UpdateCategoryBudgetCode(ctx context.Context, arg UpdateCategoryBudgetCodeParams) (CategoryBudgetCode, error) {
	row := q.db.QueryRow(ctx, updateCategoryBudgetCode, arg.ID, arg.BudgetCode, arg.Active)
	var i CategoryBudgetCode
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BudgetCode,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
