// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"
)

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*) FROM categories 
WHERE organization_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR name ILIKE $2)
  AND ($3::text = '' OR UPPER(active) = UPPER($3))
`

type CountCategoriesParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
}

func (q *Queries) CountCategories(ctx context.Context, arg CountCategoriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories, arg.OrganizationID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    id, organization_id, name, description, active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, organization_id, name, description, active, created_at, updated_at
`

type CreateCategoryParams struct {
	ID             string  `json:"id"`
	OrganizationID string  `json:"organizationId"`
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	Active         *bool   `json:"active"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Active,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one

SELECT id, organization_id, name, description, active, created_at, updated_at FROM categories WHERE id = $1 AND deleted_at IS NULL
`

type GetCategoryByIDParams struct {
	ID string `json:"id"`
}

// Category queries
// Organization-scoped category CRUD operations
func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, organization_id, name, description, active, created_at, updated_at FROM categories WHERE organization_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetCategoryByNameParams struct {
	OrganizationID string `json:"organizationId"`
	Name           string `json:"name"`
}

func (q *Queries) GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, arg.OrganizationID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, organization_id, name, description, active, created_at, updated_at FROM categories 
WHERE organization_id = $1 AND deleted_at IS NULL AND active = true
ORDER BY name ASC
`

type ListActiveCategoriesParams struct {
	OrganizationID string `json:"organizationId"`
}

func (q *Queries) ListActiveCategories(ctx context.Context, arg ListActiveCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listActiveCategories, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, organization_id, name, description, active, created_at, updated_at FROM categories 
WHERE organization_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR name ILIKE $2)
  AND ($3::text = '' OR UPPER(active) = UPPER($3))
ORDER BY name ASC
LIMIT $4 OFFSET $5
`

type ListCategoriesParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE categories SET deleted_at = NOW() WHERE id = $1
`

type SoftDeleteCategoryParams struct {
	ID string `json:"id"`
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, softDeleteCategory, arg.ID)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET 
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    active = COALESCE($4, active),
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, name, description, active, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Active      *bool   `json:"active"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Active,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
