// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

const countDocuments = `-- name: CountDocuments :one
SELECT COUNT(*) FROM documents
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::text[]      IS NULL OR document_type = ANY($2::text[]))
  AND ($3::text[]      IS NULL OR status        = ANY($3::text[]))
  AND ($4::text[]      IS NULL OR department    = ANY($4::text[]))
  AND ($5::text[]      IS NULL OR created_by    = ANY($5::text[]))
  AND ($6::timestamptz IS NULL OR created_at >= $6)
  AND ($7::timestamptz IS NULL OR created_at <= $7)
  AND ($8::numeric     IS NULL OR amount     >= $8)
  AND ($9::numeric     IS NULL OR amount     <= $9)
  AND ($10::text       = '' OR (title ILIKE '%' || $10 || '%' OR description ILIKE '%' || $10 || '%'))
`

type CountDocumentsParams struct {
	OrganizationID string             `json:"organizationId"`
	Column2        []string           `json:"column2"`
	Column3        []string           `json:"column3"`
	Column4        []string           `json:"column4"`
	Column5        []string           `json:"column5"`
	Column6        pgtype.Timestamptz `json:"column6"`
	Column7        pgtype.Timestamptz `json:"column7"`
	Column8        decimal.Decimal    `json:"column8"`
	Column9        decimal.Decimal    `json:"column9"`
	Column10       string             `json:"column10"`
}

func (q *Queries) CountDocuments(ctx context.Context, arg CountDocumentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingApprovalDocuments = `-- name: CountPendingApprovalDocuments :one
SELECT COUNT(*) FROM documents
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND UPPER(status) IN ('PENDING','PENDING_APPROVAL','IN_REVIEW','SUBMITTED')
`

type CountPendingApprovalDocumentsParams struct {
	OrganizationID string `json:"organizationId"`
}

func (q *Queries) CountPendingApprovalDocuments(ctx context.Context, arg CountPendingApprovalDocumentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingApprovalDocuments, arg.OrganizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id, organization_id, document_type, document_number, title, description,
    status, amount, currency, department, created_by, updated_by, workflow_id,
    data, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, organization_id, document_type, document_number, title, description, status, amount, currency, department, created_by, updated_by, workflow_id, data, metadata, deleted_at, created_at, updated_at
`

type CreateDocumentParams struct {
	ID             pgtype.UUID      `json:"id"`
	OrganizationID string           `json:"organizationId"`
	DocumentType   string           `json:"documentType"`
	DocumentNumber string           `json:"documentNumber"`
	Title          string           `json:"title"`
	Description    *string          `json:"description"`
	Status         string           `json:"status"`
	Amount         *decimal.Decimal `json:"amount"`
	Currency       *string          `json:"currency"`
	Department     *string          `json:"department"`
	CreatedBy      string           `json:"createdBy"`
	UpdatedBy      *string          `json:"updatedBy"`
	WorkflowID     pgtype.UUID      `json:"workflowId"`
	Data           []byte           `json:"data"`
	Metadata       []byte           `json:"metadata"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.OrganizationID,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.Department,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.WorkflowID,
		arg.Data,
		arg.Metadata,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Department,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.WorkflowID,
		&i.Data,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one

SELECT id, organization_id, document_type, document_number, title, description, status, amount, currency, department, created_by, updated_by, workflow_id, data, metadata, deleted_at, created_at, updated_at FROM documents
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetDocumentByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID string      `json:"organizationId"`
}

// Documents queries
// Generic documents table (NOT typed docs like requisitions, POs, etc.)
// Organization-scoped CRUD with soft-delete via deleted_at IS NULL.
func (q *Queries) GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, arg.ID, arg.OrganizationID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Department,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.WorkflowID,
		&i.Data,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByNumber = `-- name: GetDocumentByNumber :one
SELECT id, organization_id, document_type, document_number, title, description, status, amount, currency, department, created_by, updated_by, workflow_id, data, metadata, deleted_at, created_at, updated_at FROM documents
WHERE organization_id = $1 AND document_number = $2 AND deleted_at IS NULL
`

type GetDocumentByNumberParams struct {
	OrganizationID string `json:"organizationId"`
	DocumentNumber string `json:"documentNumber"`
}

func (q *Queries) GetDocumentByNumber(ctx context.Context, arg GetDocumentByNumberParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByNumber, arg.OrganizationID, arg.DocumentNumber)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Department,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.WorkflowID,
		&i.Data,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentStatsByDepartment = `-- name: GetDocumentStatsByDepartment :many
SELECT department, COUNT(*) AS count
FROM documents
WHERE organization_id = $1 AND deleted_at IS NULL AND department IS NOT NULL
GROUP BY department
ORDER BY count DESC
`

type GetDocumentStatsByDepartmentParams struct {
	OrganizationID string `json:"organizationId"`
}

type GetDocumentStatsByDepartmentRow struct {
	Department *string `json:"department"`
	Count      int64   `json:"count"`
}

func (q *Queries) GetDocumentStatsByDepartment(ctx context.Context, arg GetDocumentStatsByDepartmentParams) ([]GetDocumentStatsByDepartmentRow, error) {
	rows, err := q.db.Query(ctx, getDocumentStatsByDepartment, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocumentStatsByDepartmentRow{}
	for rows.Next() {
		var i GetDocumentStatsByDepartmentRow
		if err := rows.Scan(&i.Department, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentStatsByStatus = `-- name: GetDocumentStatsByStatus :many
SELECT status, COUNT(*) AS count
FROM documents
WHERE organization_id = $1 AND deleted_at IS NULL
GROUP BY status
ORDER BY count DESC
`

type GetDocumentStatsByStatusParams struct {
	OrganizationID string `json:"organizationId"`
}

type GetDocumentStatsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetDocumentStatsByStatus(ctx context.Context, arg GetDocumentStatsByStatusParams) ([]GetDocumentStatsByStatusRow, error) {
	rows, err := q.db.Query(ctx, getDocumentStatsByStatus, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocumentStatsByStatusRow{}
	for rows.Next() {
		var i GetDocumentStatsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentStatsByType = `-- name: GetDocumentStatsByType :many
SELECT document_type, COUNT(*) AS count
FROM documents
WHERE organization_id = $1 AND deleted_at IS NULL
GROUP BY document_type
ORDER BY count DESC
`

type GetDocumentStatsByTypeParams struct {
	OrganizationID string `json:"organizationId"`
}

type GetDocumentStatsByTypeRow struct {
	DocumentType string `json:"documentType"`
	Count        int64  `json:"count"`
}

func (q *Queries) GetDocumentStatsByType(ctx context.Context, arg GetDocumentStatsByTypeParams) ([]GetDocumentStatsByTypeRow, error) {
	rows, err := q.db.Query(ctx, getDocumentStatsByType, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocumentStatsByTypeRow{}
	for rows.Next() {
		var i GetDocumentStatsByTypeRow
		if err := rows.Scan(&i.DocumentType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, organization_id, document_type, document_number, title, description, status, amount, currency, department, created_by, updated_by, workflow_id, data, metadata, deleted_at, created_at, updated_at FROM documents
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::text[]      IS NULL OR document_type = ANY($2::text[]))
  AND ($3::text[]      IS NULL OR status        = ANY($3::text[]))
  AND ($4::text[]      IS NULL OR department    = ANY($4::text[]))
  AND ($5::text[]      IS NULL OR created_by    = ANY($5::text[]))
  AND ($6::timestamptz IS NULL OR created_at >= $6)
  AND ($7::timestamptz IS NULL OR created_at <= $7)
  AND ($8::numeric     IS NULL OR amount     >= $8)
  AND ($9::numeric     IS NULL OR amount     <= $9)
  AND ($10::text       = '' OR (title ILIKE '%' || $10 || '%' OR description ILIKE '%' || $10 || '%'))
ORDER BY created_at DESC
LIMIT $11 OFFSET $12
`

type ListDocumentsParams struct {
	OrganizationID string             `json:"organizationId"`
	Column2        []string           `json:"column2"`
	Column3        []string           `json:"column3"`
	Column4        []string           `json:"column4"`
	Column5        []string           `json:"column5"`
	Column6        pgtype.Timestamptz `json:"column6"`
	Column7        pgtype.Timestamptz `json:"column7"`
	Column8        decimal.Decimal    `json:"column8"`
	Column9        decimal.Decimal    `json:"column9"`
	Column10       string             `json:"column10"`
	Limit          int32              `json:"limit"`
	Offset         int32              `json:"offset"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.Department,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.WorkflowID,
			&i.Data,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDocuments = `-- name: ListRecentDocuments :many
SELECT id, organization_id, document_type, document_number, title, description, status, amount, currency, department, created_by, updated_by, workflow_id, data, metadata, deleted_at, created_at, updated_at FROM documents
WHERE organization_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentDocumentsParams struct {
	OrganizationID string `json:"organizationId"`
	Limit          int32  `json:"limit"`
}

func (q *Queries) ListRecentDocuments(ctx context.Context, arg ListRecentDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listRecentDocuments, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.Department,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.WorkflowID,
			&i.Data,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDocument = `-- name: SoftDeleteDocument :exec
UPDATE documents SET deleted_at = NOW() WHERE id = $1
`

type SoftDeleteDocumentParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, softDeleteDocument, arg.ID)
	return err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents SET
    title       = COALESCE($2,  title),
    description = COALESCE($3,  description),
    status      = COALESCE($4,  status),
    amount      = COALESCE($5,  amount),
    currency    = COALESCE($6,  currency),
    department  = COALESCE($7,  department),
    updated_by  = COALESCE($8,  updated_by),
    workflow_id = COALESCE($9,  workflow_id),
    data        = COALESCE($10, data),
    metadata    = COALESCE($11, metadata),
    updated_at  = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, document_type, document_number, title, description, status, amount, currency, department, created_by, updated_by, workflow_id, data, metadata, deleted_at, created_at, updated_at
`

type UpdateDocumentParams struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Description *string          `json:"description"`
	Status      string           `json:"status"`
	Amount      *decimal.Decimal `json:"amount"`
	Currency    *string          `json:"currency"`
	Department  *string          `json:"department"`
	UpdatedBy   *string          `json:"updatedBy"`
	WorkflowID  pgtype.UUID      `json:"workflowId"`
	Data        []byte           `json:"data"`
	Metadata    []byte           `json:"metadata"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.Department,
		arg.UpdatedBy,
		arg.WorkflowID,
		arg.Data,
		arg.Metadata,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Department,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.WorkflowID,
		&i.Data,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
