// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents_extra.sql

package db

import (
	"context"
)

const getLinkedGRNByPONumber = `-- name: GetLinkedGRNByPONumber :one
SELECT id, organization_id, document_number, po_document_number, status, received_date, received_by, items, quality_issues, approval_stage, approval_history, created_by, owner_id, warehouse_location, notes, stage_name, approved_by, automation_used, auto_created_pv, action_history, metadata, budget_code, cost_center, project_code, deleted_at, created_at, updated_at, linked_pv FROM goods_received_notes
WHERE po_document_number = $1
  AND organization_id = $2
  AND deleted_at IS NULL
  AND UPPER(status) != 'CANCELLED'
ORDER BY created_at DESC
LIMIT 1
`

type GetLinkedGRNByPONumberParams struct {
	PoDocumentNumber *string `json:"poDocumentNumber"`
	OrganizationID   string  `json:"organizationId"`
}

func (q *Queries) GetLinkedGRNByPONumber(ctx context.Context, arg GetLinkedGRNByPONumberParams) (GoodsReceivedNote, error) {
	row := q.db.QueryRow(ctx, getLinkedGRNByPONumber, arg.PoDocumentNumber, arg.OrganizationID)
	var i GoodsReceivedNote
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.PoDocumentNumber,
		&i.Status,
		&i.ReceivedDate,
		&i.ReceivedBy,
		&i.Items,
		&i.QualityIssues,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.CreatedBy,
		&i.OwnerID,
		&i.WarehouseLocation,
		&i.Notes,
		&i.StageName,
		&i.ApprovedBy,
		&i.AutomationUsed,
		&i.AutoCreatedPv,
		&i.ActionHistory,
		&i.Metadata,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedPv,
	)
	return i, err
}

const getLinkedPOByRequisition = `-- name: GetLinkedPOByRequisition :one

SELECT id, organization_id, document_number, vendor_id, status, items, total_amount, currency, delivery_date, approval_stage, approval_history, linked_requisition, description, department, department_id, gl_code, title, priority, subtotal, tax, total, budget_code, cost_center, project_code, required_by_date, source_requisition_number, source_requisition_id, created_by, owner_id, action_history, metadata, estimated_cost, quotation_gate_overridden, bypass_justification, automation_used, auto_created_grn, deleted_at, created_at, updated_at, procurement_flow FROM purchase_orders
WHERE source_requisition_id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
  AND UPPER(status) != 'CANCELLED'
ORDER BY created_at DESC
LIMIT 1
`

type GetLinkedPOByRequisitionParams struct {
	SourceRequisitionID *string `json:"sourceRequisitionId"`
	OrganizationID      string  `json:"organizationId"`
}

// Documents extra: cross-document link lookups
// Used to fetch the related typed-document for a given document number/id.
func (q *Queries) GetLinkedPOByRequisition(ctx context.Context, arg GetLinkedPOByRequisitionParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, getLinkedPOByRequisition, arg.SourceRequisitionID, arg.OrganizationID)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.Status,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.DeliveryDate,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedRequisition,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.GlCode,
		&i.Title,
		&i.Priority,
		&i.Subtotal,
		&i.Tax,
		&i.Total,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.RequiredByDate,
		&i.SourceRequisitionNumber,
		&i.SourceRequisitionID,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.EstimatedCost,
		&i.QuotationGateOverridden,
		&i.BypassJustification,
		&i.AutomationUsed,
		&i.AutoCreatedGrn,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcurementFlow,
	)
	return i, err
}

const getLinkedPOByRequisitionNumber = `-- name: GetLinkedPOByRequisitionNumber :one
SELECT id, organization_id, document_number, vendor_id, status, items, total_amount, currency, delivery_date, approval_stage, approval_history, linked_requisition, description, department, department_id, gl_code, title, priority, subtotal, tax, total, budget_code, cost_center, project_code, required_by_date, source_requisition_number, source_requisition_id, created_by, owner_id, action_history, metadata, estimated_cost, quotation_gate_overridden, bypass_justification, automation_used, auto_created_grn, deleted_at, created_at, updated_at, procurement_flow FROM purchase_orders
WHERE source_requisition_number = $1
  AND organization_id = $2
  AND deleted_at IS NULL
  AND UPPER(status) != 'CANCELLED'
ORDER BY created_at DESC
LIMIT 1
`

type GetLinkedPOByRequisitionNumberParams struct {
	SourceRequisitionNumber *string `json:"sourceRequisitionNumber"`
	OrganizationID          string  `json:"organizationId"`
}

func (q *Queries) GetLinkedPOByRequisitionNumber(ctx context.Context, arg GetLinkedPOByRequisitionNumberParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, getLinkedPOByRequisitionNumber, arg.SourceRequisitionNumber, arg.OrganizationID)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.Status,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.DeliveryDate,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedRequisition,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.GlCode,
		&i.Title,
		&i.Priority,
		&i.Subtotal,
		&i.Tax,
		&i.Total,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.RequiredByDate,
		&i.SourceRequisitionNumber,
		&i.SourceRequisitionID,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.EstimatedCost,
		&i.QuotationGateOverridden,
		&i.BypassJustification,
		&i.AutomationUsed,
		&i.AutoCreatedGrn,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcurementFlow,
	)
	return i, err
}

const getLinkedPVByGRNNumber = `-- name: GetLinkedPVByGRNNumber :one
SELECT id, organization_id, document_number, vendor_id, invoice_number, status, amount, currency, payment_method, gl_code, description, approval_stage, approval_history, linked_po, title, department, department_id, priority, requested_by_name, requested_date, submitted_at, approved_at, paid_date, payment_due_date, budget_code, cost_center, project_code, tax_amount, withholding_tax_amount, paid_amount, source_purchase_order_number, source_requisition_number, bank_details, items, created_by, owner_id, action_history, metadata, deleted_at, created_at, updated_at, linked_grn FROM payment_vouchers
WHERE linked_grn = $1
  AND organization_id = $2
  AND deleted_at IS NULL
  AND UPPER(status) != 'CANCELLED'
ORDER BY created_at DESC
LIMIT 1
`

type GetLinkedPVByGRNNumberParams struct {
	LinkedGrn      *string `json:"linkedGrn"`
	OrganizationID string  `json:"organizationId"`
}

func (q *Queries) GetLinkedPVByGRNNumber(ctx context.Context, arg GetLinkedPVByGRNNumberParams) (PaymentVoucher, error) {
	row := q.db.QueryRow(ctx, getLinkedPVByGRNNumber, arg.LinkedGrn, arg.OrganizationID)
	var i PaymentVoucher
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.GlCode,
		&i.Description,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedPo,
		&i.Title,
		&i.Department,
		&i.DepartmentID,
		&i.Priority,
		&i.RequestedByName,
		&i.RequestedDate,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.PaidDate,
		&i.PaymentDueDate,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.TaxAmount,
		&i.WithholdingTaxAmount,
		&i.PaidAmount,
		&i.SourcePurchaseOrderNumber,
		&i.SourceRequisitionNumber,
		&i.BankDetails,
		&i.Items,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedGrn,
	)
	return i, err
}

const getLinkedPVByPONumber = `-- name: GetLinkedPVByPONumber :one
SELECT id, organization_id, document_number, vendor_id, invoice_number, status, amount, currency, payment_method, gl_code, description, approval_stage, approval_history, linked_po, title, department, department_id, priority, requested_by_name, requested_date, submitted_at, approved_at, paid_date, payment_due_date, budget_code, cost_center, project_code, tax_amount, withholding_tax_amount, paid_amount, source_purchase_order_number, source_requisition_number, bank_details, items, created_by, owner_id, action_history, metadata, deleted_at, created_at, updated_at, linked_grn FROM payment_vouchers
WHERE linked_po = $1
  AND organization_id = $2
  AND deleted_at IS NULL
  AND UPPER(status) != 'CANCELLED'
ORDER BY created_at DESC
LIMIT 1
`

type GetLinkedPVByPONumberParams struct {
	LinkedPo       *string `json:"linkedPo"`
	OrganizationID string  `json:"organizationId"`
}

func (q *Queries) GetLinkedPVByPONumber(ctx context.Context, arg GetLinkedPVByPONumberParams) (PaymentVoucher, error) {
	row := q.db.QueryRow(ctx, getLinkedPVByPONumber, arg.LinkedPo, arg.OrganizationID)
	var i PaymentVoucher
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.GlCode,
		&i.Description,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedPo,
		&i.Title,
		&i.Department,
		&i.DepartmentID,
		&i.Priority,
		&i.RequestedByName,
		&i.RequestedDate,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.PaidDate,
		&i.PaymentDueDate,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.TaxAmount,
		&i.WithholdingTaxAmount,
		&i.PaidAmount,
		&i.SourcePurchaseOrderNumber,
		&i.SourceRequisitionNumber,
		&i.BankDetails,
		&i.Items,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedGrn,
	)
	return i, err
}

const getRequisitionByPONumber = `-- name: GetRequisitionByPONumber :one
SELECT r.id, r.organization_id, r.document_number, r.requester_id, r.title, r.description, r.department, r.department_id, r.status, r.priority, r.items, r.total_amount, r.currency, r.approval_stage, r.approval_history, r.action_history, r.category_id, r.preferred_vendor_id, r.is_estimate, r.required_by_date, r.cost_center, r.project_code, r.budget_code, r.source_of_funds, r.created_by, r.created_by_name, r.created_by_role, r.metadata, r.automation_used, r.auto_created_po, r.deleted_at, r.created_at, r.updated_at FROM requisitions r
INNER JOIN purchase_orders po
        ON po.source_requisition_id = r.id
       AND po.organization_id = r.organization_id
WHERE po.document_number = $1
  AND r.organization_id = $2
  AND r.deleted_at  IS NULL
  AND po.deleted_at IS NULL
ORDER BY po.created_at DESC
LIMIT 1
`

type GetRequisitionByPONumberParams struct {
	DocumentNumber string `json:"documentNumber"`
	OrganizationID string `json:"organizationId"`
}

func (q *Queries) GetRequisitionByPONumber(ctx context.Context, arg GetRequisitionByPONumberParams) (Requisition, error) {
	row := q.db.QueryRow(ctx, getRequisitionByPONumber, arg.DocumentNumber, arg.OrganizationID)
	var i Requisition
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.RequesterID,
		&i.Title,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.Priority,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.ActionHistory,
		&i.CategoryID,
		&i.PreferredVendorID,
		&i.IsEstimate,
		&i.RequiredByDate,
		&i.CostCenter,
		&i.ProjectCode,
		&i.BudgetCode,
		&i.SourceOfFunds,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedByRole,
		&i.Metadata,
		&i.AutomationUsed,
		&i.AutoCreatedPo,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
