// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: grns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGRNs = `-- name: CountGRNs :one
SELECT COUNT(*) FROM goods_received_notes
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::text       = '' OR UPPER(status)         = UPPER($2))
  AND ($3::text       = '' OR po_document_number    = $3)
  AND ($4::text       = '' OR received_by           = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
  AND ($7::text       = '' OR (document_number ILIKE '%' || $7 || '%' OR notes ILIKE '%' || $7 || '%'))
`

type CountGRNsParams struct {
	OrganizationID string             `json:"organizationId"`
	Column2        string             `json:"column2"`
	Column3        string             `json:"column3"`
	Column4        string             `json:"column4"`
	Column5        pgtype.Timestamptz `json:"column5"`
	Column6        pgtype.Timestamptz `json:"column6"`
	Column7        string             `json:"column7"`
}

func (q *Queries) CountGRNs(ctx context.Context, arg CountGRNsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGRNs,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGRNsAll = `-- name: CountGRNsAll :one
SELECT COUNT(*) FROM goods_received_notes
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status)           = UPPER($2))
  AND ($3::text = '' OR po_document_number      = $3)
`

type CountGRNsAllParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
}

func (q *Queries) CountGRNsAll(ctx context.Context, arg CountGRNsAllParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGRNsAll, arg.OrganizationID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGRNsByPO = `-- name: CountGRNsByPO :one
SELECT COUNT(*) FROM goods_received_notes
WHERE organization_id    = $1
  AND po_document_number = $2
  AND deleted_at IS NULL
`

type CountGRNsByPOParams struct {
	OrganizationID   string  `json:"organizationId"`
	PoDocumentNumber *string `json:"poDocumentNumber"`
}

func (q *Queries) CountGRNsByPO(ctx context.Context, arg CountGRNsByPOParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGRNsByPO, arg.OrganizationID, arg.PoDocumentNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGRNsLimited = `-- name: CountGRNsLimited :one
SELECT COUNT(*) FROM goods_received_notes g
WHERE g.organization_id = $1
  AND ($2::text = '' OR UPPER(g.status)          = UPPER($2))
  AND ($3::text = '' OR g.po_document_number     = $3)
  AND (
      g.created_by  = $4
      OR g.received_by = $4
      OR g.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'grn'
            AND (
                wt.assigned_user_id        = $4
                OR LOWER(wt.assigned_role) = LOWER($5)
                OR wt.assigned_role        = ANY($6::text[])
                OR wt.claimed_by           = $4
            )
      )
  )
`

type CountGRNsLimitedParams struct {
	OrganizationID string   `json:"organizationId"`
	Column2        string   `json:"column2"`
	Column3        string   `json:"column3"`
	CreatedBy      *string  `json:"createdBy"`
	Lower          string   `json:"lower"`
	Column6        []string `json:"column6"`
}

func (q *Queries) CountGRNsLimited(ctx context.Context, arg CountGRNsLimitedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGRNsLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.CreatedBy,
		arg.Lower,
		arg.Column6,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGRN = `-- name: CreateGRN :one
INSERT INTO goods_received_notes (
    id, organization_id, document_number, po_document_number, status,
    received_date, received_by, created_by, warehouse_location, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, organization_id, document_number, po_document_number, status, received_date, received_by, items, quality_issues, approval_stage, approval_history, created_by, owner_id, warehouse_location, notes, stage_name, approved_by, automation_used, auto_created_pv, action_history, metadata, budget_code, cost_center, project_code, deleted_at, created_at, updated_at, linked_pv
`

type CreateGRNParams struct {
	ID                string             `json:"id"`
	OrganizationID    string             `json:"organizationId"`
	DocumentNumber    string             `json:"documentNumber"`
	PoDocumentNumber  *string            `json:"poDocumentNumber"`
	Status            *string            `json:"status"`
	ReceivedDate      pgtype.Timestamptz `json:"receivedDate"`
	ReceivedBy        *string            `json:"receivedBy"`
	CreatedBy         *string            `json:"createdBy"`
	WarehouseLocation *string            `json:"warehouseLocation"`
	Notes             *string            `json:"notes"`
}

func (q *Queries) CreateGRN(ctx context.Context, arg CreateGRNParams) (GoodsReceivedNote, error) {
	row := q.db.QueryRow(ctx, createGRN,
		arg.ID,
		arg.OrganizationID,
		arg.DocumentNumber,
		arg.PoDocumentNumber,
		arg.Status,
		arg.ReceivedDate,
		arg.ReceivedBy,
		arg.CreatedBy,
		arg.WarehouseLocation,
		arg.Notes,
	)
	var i GoodsReceivedNote
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.PoDocumentNumber,
		&i.Status,
		&i.ReceivedDate,
		&i.ReceivedBy,
		&i.Items,
		&i.QualityIssues,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.CreatedBy,
		&i.OwnerID,
		&i.WarehouseLocation,
		&i.Notes,
		&i.StageName,
		&i.ApprovedBy,
		&i.AutomationUsed,
		&i.AutoCreatedPv,
		&i.ActionHistory,
		&i.Metadata,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedPv,
	)
	return i, err
}

const getGRNByDocumentNumber = `-- name: GetGRNByDocumentNumber :one
SELECT id, organization_id, document_number, po_document_number, status, received_date, received_by, items, quality_issues, approval_stage, approval_history, created_by, owner_id, warehouse_location, notes, stage_name, approved_by, automation_used, auto_created_pv, action_history, metadata, budget_code, cost_center, project_code, deleted_at, created_at, updated_at, linked_pv FROM goods_received_notes WHERE organization_id = $1 AND document_number = $2 AND deleted_at IS NULL
`

type GetGRNByDocumentNumberParams struct {
	OrganizationID string `json:"organizationId"`
	DocumentNumber string `json:"documentNumber"`
}

func (q *Queries) GetGRNByDocumentNumber(ctx context.Context, arg GetGRNByDocumentNumberParams) (GoodsReceivedNote, error) {
	row := q.db.QueryRow(ctx, getGRNByDocumentNumber, arg.OrganizationID, arg.DocumentNumber)
	var i GoodsReceivedNote
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.PoDocumentNumber,
		&i.Status,
		&i.ReceivedDate,
		&i.ReceivedBy,
		&i.Items,
		&i.QualityIssues,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.CreatedBy,
		&i.OwnerID,
		&i.WarehouseLocation,
		&i.Notes,
		&i.StageName,
		&i.ApprovedBy,
		&i.AutomationUsed,
		&i.AutoCreatedPv,
		&i.ActionHistory,
		&i.Metadata,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedPv,
	)
	return i, err
}

const getGRNByID = `-- name: GetGRNByID :one

SELECT id, organization_id, document_number, po_document_number, status, received_date, received_by, items, quality_issues, approval_stage, approval_history, created_by, owner_id, warehouse_location, notes, stage_name, approved_by, automation_used, auto_created_pv, action_history, metadata, budget_code, cost_center, project_code, deleted_at, created_at, updated_at, linked_pv FROM goods_received_notes WHERE id = $1 AND deleted_at IS NULL
`

type GetGRNByIDParams struct {
	ID string `json:"id"`
}

// Goods received note read queries.
// Both CanViewAll and IsProcurement use the unfiltered path (ApplyToQuery passes through).
// Limited adds owner (created_by OR received_by) + workflow_tasks involvement.
func (q *Queries) GetGRNByID(ctx context.Context, arg GetGRNByIDParams) (GoodsReceivedNote, error) {
	row := q.db.QueryRow(ctx, getGRNByID, arg.ID)
	var i GoodsReceivedNote
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.PoDocumentNumber,
		&i.Status,
		&i.ReceivedDate,
		&i.ReceivedBy,
		&i.Items,
		&i.QualityIssues,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.CreatedBy,
		&i.OwnerID,
		&i.WarehouseLocation,
		&i.Notes,
		&i.StageName,
		&i.ApprovedBy,
		&i.AutomationUsed,
		&i.AutoCreatedPv,
		&i.ActionHistory,
		&i.Metadata,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedPv,
	)
	return i, err
}

const linkPVToGRN = `-- name: LinkPVToGRN :exec
UPDATE goods_received_notes SET linked_pv = $2, updated_at = NOW() WHERE id = $1
`

type LinkPVToGRNParams struct {
	ID       string  `json:"id"`
	LinkedPv *string `json:"linkedPv"`
}

func (q *Queries) LinkPVToGRN(ctx context.Context, arg LinkPVToGRNParams) error {
	_, err := q.db.Exec(ctx, linkPVToGRN, arg.ID, arg.LinkedPv)
	return err
}

const listGRNIDsAll = `-- name: ListGRNIDsAll :many
SELECT id FROM goods_received_notes
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status)           = UPPER($2))
  AND ($3::text = '' OR po_document_number      = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListGRNIDsAllParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListGRNIDsAll(ctx context.Context, arg ListGRNIDsAllParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listGRNIDsAll,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGRNIDsLimited = `-- name: ListGRNIDsLimited :many
SELECT g.id FROM goods_received_notes g
WHERE g.organization_id = $1
  AND ($2::text = '' OR UPPER(g.status)          = UPPER($2))
  AND ($3::text = '' OR g.po_document_number     = $3)
  AND (
      g.created_by  = $4
      OR g.received_by = $4
      OR g.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'grn'
            AND (
                wt.assigned_user_id        = $4
                OR LOWER(wt.assigned_role) = LOWER($5)
                OR wt.assigned_role        = ANY($6::text[])
                OR wt.claimed_by           = $4
            )
      )
  )
ORDER BY g.created_at DESC
LIMIT $7 OFFSET $8
`

type ListGRNIDsLimitedParams struct {
	OrganizationID string   `json:"organizationId"`
	Column2        string   `json:"column2"`
	Column3        string   `json:"column3"`
	CreatedBy      *string  `json:"createdBy"`
	Lower          string   `json:"lower"`
	Column6        []string `json:"column6"`
	Limit          int32    `json:"limit"`
	Offset         int32    `json:"offset"`
}

func (q *Queries) ListGRNIDsLimited(ctx context.Context, arg ListGRNIDsLimitedParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listGRNIDsLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.CreatedBy,
		arg.Lower,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGRNs = `-- name: ListGRNs :many
SELECT id, organization_id, document_number, po_document_number, status, received_date, received_by, items, quality_issues, approval_stage, approval_history, created_by, owner_id, warehouse_location, notes, stage_name, approved_by, automation_used, auto_created_pv, action_history, metadata, budget_code, cost_center, project_code, deleted_at, created_at, updated_at, linked_pv FROM goods_received_notes
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::text       = '' OR UPPER(status)         = UPPER($2))
  AND ($3::text       = '' OR po_document_number    = $3)
  AND ($4::text       = '' OR received_by           = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
  AND ($7::text       = '' OR (document_number ILIKE '%' || $7 || '%' OR notes ILIKE '%' || $7 || '%'))
ORDER BY created_at DESC
LIMIT $8 OFFSET $9
`

type ListGRNsParams struct {
	OrganizationID string             `json:"organizationId"`
	Column2        string             `json:"column2"`
	Column3        string             `json:"column3"`
	Column4        string             `json:"column4"`
	Column5        pgtype.Timestamptz `json:"column5"`
	Column6        pgtype.Timestamptz `json:"column6"`
	Column7        string             `json:"column7"`
	Limit          int32              `json:"limit"`
	Offset         int32              `json:"offset"`
}

func (q *Queries) ListGRNs(ctx context.Context, arg ListGRNsParams) ([]GoodsReceivedNote, error) {
	rows, err := q.db.Query(ctx, listGRNs,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GoodsReceivedNote{}
	for rows.Next() {
		var i GoodsReceivedNote
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentNumber,
			&i.PoDocumentNumber,
			&i.Status,
			&i.ReceivedDate,
			&i.ReceivedBy,
			&i.Items,
			&i.QualityIssues,
			&i.ApprovalStage,
			&i.ApprovalHistory,
			&i.CreatedBy,
			&i.OwnerID,
			&i.WarehouseLocation,
			&i.Notes,
			&i.StageName,
			&i.ApprovedBy,
			&i.AutomationUsed,
			&i.AutoCreatedPv,
			&i.ActionHistory,
			&i.Metadata,
			&i.BudgetCode,
			&i.CostCenter,
			&i.ProjectCode,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LinkedPv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGRNsByPO = `-- name: ListGRNsByPO :many
SELECT id, organization_id, document_number, po_document_number, status, received_date, received_by, items, quality_issues, approval_stage, approval_history, created_by, owner_id, warehouse_location, notes, stage_name, approved_by, automation_used, auto_created_pv, action_history, metadata, budget_code, cost_center, project_code, deleted_at, created_at, updated_at, linked_pv FROM goods_received_notes
WHERE organization_id    = $1
  AND po_document_number = $2
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListGRNsByPOParams struct {
	OrganizationID   string  `json:"organizationId"`
	PoDocumentNumber *string `json:"poDocumentNumber"`
}

func (q *Queries) ListGRNsByPO(ctx context.Context, arg ListGRNsByPOParams) ([]GoodsReceivedNote, error) {
	rows, err := q.db.Query(ctx, listGRNsByPO, arg.OrganizationID, arg.PoDocumentNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GoodsReceivedNote{}
	for rows.Next() {
		var i GoodsReceivedNote
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentNumber,
			&i.PoDocumentNumber,
			&i.Status,
			&i.ReceivedDate,
			&i.ReceivedBy,
			&i.Items,
			&i.QualityIssues,
			&i.ApprovalStage,
			&i.ApprovalHistory,
			&i.CreatedBy,
			&i.OwnerID,
			&i.WarehouseLocation,
			&i.Notes,
			&i.StageName,
			&i.ApprovedBy,
			&i.AutomationUsed,
			&i.AutoCreatedPv,
			&i.ActionHistory,
			&i.Metadata,
			&i.BudgetCode,
			&i.CostCenter,
			&i.ProjectCode,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LinkedPv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGRN = `-- name: SoftDeleteGRN :exec
UPDATE goods_received_notes SET deleted_at = NOW() WHERE id = $1
`

type SoftDeleteGRNParams struct {
	ID string `json:"id"`
}

func (q *Queries) SoftDeleteGRN(ctx context.Context, arg SoftDeleteGRNParams) error {
	_, err := q.db.Exec(ctx, softDeleteGRN, arg.ID)
	return err
}

const updateGRN = `-- name: UpdateGRN :one
UPDATE goods_received_notes SET 
    status = COALESCE($2, status),
    received_date = COALESCE($3, received_date),
    received_by = COALESCE($4, received_by),
    warehouse_location = COALESCE($5, warehouse_location),
    notes = COALESCE($6, notes),
    approval_stage = COALESCE($7, approval_stage),
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, document_number, po_document_number, status, received_date, received_by, items, quality_issues, approval_stage, approval_history, created_by, owner_id, warehouse_location, notes, stage_name, approved_by, automation_used, auto_created_pv, action_history, metadata, budget_code, cost_center, project_code, deleted_at, created_at, updated_at, linked_pv
`

type UpdateGRNParams struct {
	ID                string             `json:"id"`
	Status            *string            `json:"status"`
	ReceivedDate      pgtype.Timestamptz `json:"receivedDate"`
	ReceivedBy        *string            `json:"receivedBy"`
	WarehouseLocation *string            `json:"warehouseLocation"`
	Notes             *string            `json:"notes"`
	ApprovalStage     *int32             `json:"approvalStage"`
}

func (q *Queries) UpdateGRN(ctx context.Context, arg UpdateGRNParams) (GoodsReceivedNote, error) {
	row := q.db.QueryRow(ctx, updateGRN,
		arg.ID,
		arg.Status,
		arg.ReceivedDate,
		arg.ReceivedBy,
		arg.WarehouseLocation,
		arg.Notes,
		arg.ApprovalStage,
	)
	var i GoodsReceivedNote
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.PoDocumentNumber,
		&i.Status,
		&i.ReceivedDate,
		&i.ReceivedBy,
		&i.Items,
		&i.QualityIssues,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.CreatedBy,
		&i.OwnerID,
		&i.WarehouseLocation,
		&i.Notes,
		&i.StageName,
		&i.ApprovedBy,
		&i.AutomationUsed,
		&i.AutoCreatedPv,
		&i.ActionHistory,
		&i.Metadata,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedPv,
	)
	return i, err
}

const updateGRNLinkedPV = `-- name: UpdateGRNLinkedPV :exec
UPDATE goods_received_notes
SET linked_pv  = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateGRNLinkedPVParams struct {
	ID       string  `json:"id"`
	LinkedPv *string `json:"linkedPv"`
}

func (q *Queries) UpdateGRNLinkedPV(ctx context.Context, arg UpdateGRNLinkedPVParams) error {
	_, err := q.db.Exec(ctx, updateGRNLinkedPV, arg.ID, arg.LinkedPv)
	return err
}

const updateGRNStatus = `-- name: UpdateGRNStatus :one
UPDATE goods_received_notes
SET status         = $2,
    approval_stage = COALESCE($3, approval_stage),
    updated_at     = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, document_number, po_document_number, status, received_date, received_by, items, quality_issues, approval_stage, approval_history, created_by, owner_id, warehouse_location, notes, stage_name, approved_by, automation_used, auto_created_pv, action_history, metadata, budget_code, cost_center, project_code, deleted_at, created_at, updated_at, linked_pv
`

type UpdateGRNStatusParams struct {
	ID            string  `json:"id"`
	Status        *string `json:"status"`
	ApprovalStage *int32  `json:"approvalStage"`
}

func (q *Queries) UpdateGRNStatus(ctx context.Context, arg UpdateGRNStatusParams) (GoodsReceivedNote, error) {
	row := q.db.QueryRow(ctx, updateGRNStatus, arg.ID, arg.Status, arg.ApprovalStage)
	var i GoodsReceivedNote
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.PoDocumentNumber,
		&i.Status,
		&i.ReceivedDate,
		&i.ReceivedBy,
		&i.Items,
		&i.QualityIssues,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.CreatedBy,
		&i.OwnerID,
		&i.WarehouseLocation,
		&i.Notes,
		&i.StageName,
		&i.ApprovedBy,
		&i.AutomationUsed,
		&i.AutoCreatedPv,
		&i.ActionHistory,
		&i.Metadata,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedPv,
	)
	return i, err
}
