// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: impersonation_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countImpersonationLogs = `-- name: CountImpersonationLogs :one
SELECT COUNT(*) FROM impersonation_logs
WHERE ($1::text       = '' OR impersonator_id    = $1)
  AND ($2::text       = '' OR target_id          = $2)
  AND ($3::text       = '' OR impersonation_type = $3)
  AND ($4::bool       IS NULL OR revoked         = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
`

type CountImpersonationLogsParams struct {
	Column1 string             `json:"column1"`
	Column2 string             `json:"column2"`
	Column3 string             `json:"column3"`
	Column4 bool               `json:"column4"`
	Column5 pgtype.Timestamptz `json:"column5"`
	Column6 pgtype.Timestamptz `json:"column6"`
}

func (q *Queries) CountImpersonationLogs(ctx context.Context, arg CountImpersonationLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImpersonationLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImpersonationLog = `-- name: CreateImpersonationLog :one

INSERT INTO impersonation_logs (
    id, impersonator_id, impersonator_email, target_id, target_email,
    impersonation_type, token_jti, reason, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, impersonator_id, impersonator_email, target_id, target_email, impersonation_type, token_jti, reason, expires_at, revoked, revoked_at, revoked_by, created_at
`

type CreateImpersonationLogParams struct {
	ID                string             `json:"id"`
	ImpersonatorID    string             `json:"impersonatorId"`
	ImpersonatorEmail string             `json:"impersonatorEmail"`
	TargetID          string             `json:"targetId"`
	TargetEmail       string             `json:"targetEmail"`
	ImpersonationType string             `json:"impersonationType"`
	TokenJti          string             `json:"tokenJti"`
	Reason            *string            `json:"reason"`
	ExpiresAt         pgtype.Timestamptz `json:"expiresAt"`
}

// Impersonation log queries
// Tracks platform/admin user impersonation events. id is TEXT not UUID.
func (q *Queries) CreateImpersonationLog(ctx context.Context, arg CreateImpersonationLogParams) (ImpersonationLog, error) {
	row := q.db.QueryRow(ctx, createImpersonationLog,
		arg.ID,
		arg.ImpersonatorID,
		arg.ImpersonatorEmail,
		arg.TargetID,
		arg.TargetEmail,
		arg.ImpersonationType,
		arg.TokenJti,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i ImpersonationLog
	err := row.Scan(
		&i.ID,
		&i.ImpersonatorID,
		&i.ImpersonatorEmail,
		&i.TargetID,
		&i.TargetEmail,
		&i.ImpersonationType,
		&i.TokenJti,
		&i.Reason,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getImpersonationLogByID = `-- name: GetImpersonationLogByID :one
SELECT id, impersonator_id, impersonator_email, target_id, target_email, impersonation_type, token_jti, reason, expires_at, revoked, revoked_at, revoked_by, created_at FROM impersonation_logs WHERE id = $1
`

type GetImpersonationLogByIDParams struct {
	ID string `json:"id"`
}

func (q *Queries) GetImpersonationLogByID(ctx context.Context, arg GetImpersonationLogByIDParams) (ImpersonationLog, error) {
	row := q.db.QueryRow(ctx, getImpersonationLogByID, arg.ID)
	var i ImpersonationLog
	err := row.Scan(
		&i.ID,
		&i.ImpersonatorID,
		&i.ImpersonatorEmail,
		&i.TargetID,
		&i.TargetEmail,
		&i.ImpersonationType,
		&i.TokenJti,
		&i.Reason,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getImpersonationLogByJTI = `-- name: GetImpersonationLogByJTI :one
SELECT id, impersonator_id, impersonator_email, target_id, target_email, impersonation_type, token_jti, reason, expires_at, revoked, revoked_at, revoked_by, created_at FROM impersonation_logs WHERE token_jti = $1
`

type GetImpersonationLogByJTIParams struct {
	TokenJti string `json:"tokenJti"`
}

func (q *Queries) GetImpersonationLogByJTI(ctx context.Context, arg GetImpersonationLogByJTIParams) (ImpersonationLog, error) {
	row := q.db.QueryRow(ctx, getImpersonationLogByJTI, arg.TokenJti)
	var i ImpersonationLog
	err := row.Scan(
		&i.ID,
		&i.ImpersonatorID,
		&i.ImpersonatorEmail,
		&i.TargetID,
		&i.TargetEmail,
		&i.ImpersonationType,
		&i.TokenJti,
		&i.Reason,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveImpersonations = `-- name: ListActiveImpersonations :many
SELECT id, impersonator_id, impersonator_email, target_id, target_email, impersonation_type, token_jti, reason, expires_at, revoked, revoked_at, revoked_by, created_at FROM impersonation_logs
WHERE revoked = false AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveImpersonations(ctx context.Context) ([]ImpersonationLog, error) {
	rows, err := q.db.Query(ctx, listActiveImpersonations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImpersonationLog{}
	for rows.Next() {
		var i ImpersonationLog
		if err := rows.Scan(
			&i.ID,
			&i.ImpersonatorID,
			&i.ImpersonatorEmail,
			&i.TargetID,
			&i.TargetEmail,
			&i.ImpersonationType,
			&i.TokenJti,
			&i.Reason,
			&i.ExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImpersonationLogs = `-- name: ListImpersonationLogs :many
SELECT id, impersonator_id, impersonator_email, target_id, target_email, impersonation_type, token_jti, reason, expires_at, revoked, revoked_at, revoked_by, created_at FROM impersonation_logs
WHERE ($1::text       = '' OR impersonator_id    = $1)
  AND ($2::text       = '' OR target_id          = $2)
  AND ($3::text       = '' OR impersonation_type = $3)
  AND ($4::bool       IS NULL OR revoked         = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
ORDER BY created_at DESC
LIMIT $7 OFFSET $8
`

type ListImpersonationLogsParams struct {
	Column1 string             `json:"column1"`
	Column2 string             `json:"column2"`
	Column3 string             `json:"column3"`
	Column4 bool               `json:"column4"`
	Column5 pgtype.Timestamptz `json:"column5"`
	Column6 pgtype.Timestamptz `json:"column6"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
}

func (q *Queries) ListImpersonationLogs(ctx context.Context, arg ListImpersonationLogsParams) ([]ImpersonationLog, error) {
	rows, err := q.db.Query(ctx, listImpersonationLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImpersonationLog{}
	for rows.Next() {
		var i ImpersonationLog
		if err := rows.Scan(
			&i.ID,
			&i.ImpersonatorID,
			&i.ImpersonatorEmail,
			&i.TargetID,
			&i.TargetEmail,
			&i.ImpersonationType,
			&i.TokenJti,
			&i.Reason,
			&i.ExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeImpersonationLog = `-- name: RevokeImpersonationLog :exec
UPDATE impersonation_logs
SET revoked    = true,
    revoked_at = NOW(),
    revoked_by = $2
WHERE id = $1
`

type RevokeImpersonationLogParams struct {
	ID        string  `json:"id"`
	RevokedBy *string `json:"revokedBy"`
}

func (q *Queries) RevokeImpersonationLog(ctx context.Context, arg RevokeImpersonationLogParams) error {
	_, err := q.db.Exec(ctx, revokeImpersonationLog, arg.ID, arg.RevokedBy)
	return err
}
