// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoginAttempt = `-- name: CreateLoginAttempt :one
INSERT INTO login_attempts (
    user_id, email, ip_address, user_agent, success, failure_reason
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, email, ip_address, user_agent, success, failure_reason, attempted_at
`

type CreateLoginAttemptParams struct {
	UserID        *string `json:"userId"`
	Email         string  `json:"email"`
	IpAddress     *string `json:"ipAddress"`
	UserAgent     *string `json:"userAgent"`
	Success       bool    `json:"success"`
	FailureReason *string `json:"failureReason"`
}

func (q *Queries) CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, createLoginAttempt,
		arg.UserID,
		arg.Email,
		arg.IpAddress,
		arg.UserAgent,
		arg.Success,
		arg.FailureReason,
	)
	var i LoginAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.IpAddress,
		&i.UserAgent,
		&i.Success,
		&i.FailureReason,
		&i.AttemptedAt,
	)
	return i, err
}

const deleteOldLoginAttempts = `-- name: DeleteOldLoginAttempts :exec
DELETE FROM login_attempts WHERE attempted_at < $1
`

type DeleteOldLoginAttemptsParams struct {
	AttemptedAt pgtype.Timestamptz `json:"attemptedAt"`
}

func (q *Queries) DeleteOldLoginAttempts(ctx context.Context, arg DeleteOldLoginAttemptsParams) error {
	_, err := q.db.Exec(ctx, deleteOldLoginAttempts, arg.AttemptedAt)
	return err
}

const getLoginAttemptsByEmail = `-- name: GetLoginAttemptsByEmail :many
SELECT id, user_id, email, ip_address, user_agent, success, failure_reason, attempted_at FROM login_attempts 
WHERE email = $1 
ORDER BY attempted_at DESC
LIMIT $2 OFFSET $3
`

type GetLoginAttemptsByEmailParams struct {
	Email  string `json:"email"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetLoginAttemptsByEmail(ctx context.Context, arg GetLoginAttemptsByEmailParams) ([]LoginAttempt, error) {
	rows, err := q.db.Query(ctx, getLoginAttemptsByEmail, arg.Email, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginAttempt{}
	for rows.Next() {
		var i LoginAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.IpAddress,
			&i.UserAgent,
			&i.Success,
			&i.FailureReason,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoginAttemptsByUser = `-- name: GetLoginAttemptsByUser :many
SELECT id, user_id, email, ip_address, user_agent, success, failure_reason, attempted_at FROM login_attempts 
WHERE user_id = $1 
ORDER BY attempted_at DESC
LIMIT $2 OFFSET $3
`

type GetLoginAttemptsByUserParams struct {
	UserID *string `json:"userId"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
}

func (q *Queries) GetLoginAttemptsByUser(ctx context.Context, arg GetLoginAttemptsByUserParams) ([]LoginAttempt, error) {
	rows, err := q.db.Query(ctx, getLoginAttemptsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginAttempt{}
	for rows.Next() {
		var i LoginAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.IpAddress,
			&i.UserAgent,
			&i.Success,
			&i.FailureReason,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentFailedAttempts = `-- name: GetRecentFailedAttempts :one
SELECT COUNT(*) FROM login_attempts 
WHERE email = $1 AND success = false AND attempted_at > $2
`

type GetRecentFailedAttemptsParams struct {
	Email       string             `json:"email"`
	AttemptedAt pgtype.Timestamptz `json:"attemptedAt"`
}

func (q *Queries) GetRecentFailedAttempts(ctx context.Context, arg GetRecentFailedAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRecentFailedAttempts, arg.Email, arg.AttemptedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRecentFailedAttemptsByIP = `-- name: GetRecentFailedAttemptsByIP :one
SELECT COUNT(*) FROM login_attempts 
WHERE ip_address = $1 AND success = false AND attempted_at > $2
`

type GetRecentFailedAttemptsByIPParams struct {
	IpAddress   *string            `json:"ipAddress"`
	AttemptedAt pgtype.Timestamptz `json:"attemptedAt"`
}

func (q *Queries) GetRecentFailedAttemptsByIP(ctx context.Context, arg GetRecentFailedAttemptsByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRecentFailedAttemptsByIP, arg.IpAddress, arg.AttemptedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}
