// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

type AccountLockout struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"userId"`
	Email     string             `json:"email"`
	IpAddress *string            `json:"ipAddress"`
	Reason    string             `json:"reason"`
	LockedAt  pgtype.Timestamptz `json:"lockedAt"`
	UnlocksAt pgtype.Timestamptz `json:"unlocksAt"`
	Active    *bool              `json:"active"`
}

type AuditLog struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organizationId"`
	DocumentID     string             `json:"documentId"`
	DocumentType   string             `json:"documentType"`
	UserID         string             `json:"userId"`
	ActorName      string             `json:"actorName"`
	ActorRole      string             `json:"actorRole"`
	Action         string             `json:"action"`
	Changes        []byte             `json:"changes"`
	Details        []byte             `json:"details"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
}

type Budget struct {
	ID              string             `json:"id"`
	OrganizationID  string             `json:"organizationId"`
	OwnerID         string             `json:"ownerId"`
	BudgetCode      string             `json:"budgetCode"`
	Department      *string            `json:"department"`
	DepartmentID    *string            `json:"departmentId"`
	Status          *string            `json:"status"`
	FiscalYear      *string            `json:"fiscalYear"`
	TotalBudget     *decimal.Decimal   `json:"totalBudget"`
	AllocatedAmount *decimal.Decimal   `json:"allocatedAmount"`
	RemainingAmount *decimal.Decimal   `json:"remainingAmount"`
	ApprovalStage   *int32             `json:"approvalStage"`
	ApprovalHistory []byte             `json:"approvalHistory"`
	Name            *string            `json:"name"`
	Description     *string            `json:"description"`
	Currency        *string            `json:"currency"`
	CreatedBy       *string            `json:"createdBy"`
	Items           []byte             `json:"items"`
	ActionHistory   []byte             `json:"actionHistory"`
	Metadata        []byte             `json:"metadata"`
	DeletedAt       pgtype.Timestamptz `json:"deletedAt"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

type Category struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organizationId"`
	Name           string             `json:"name"`
	Description    *string            `json:"description"`
	Active         *bool              `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type CategoryBudgetCode struct {
	ID         string             `json:"id"`
	CategoryID string             `json:"categoryId"`
	BudgetCode string             `json:"budgetCode"`
	Active     *bool              `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

// Unified document table for all business document types
type Document struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID string             `json:"organizationId"`
	DocumentType   string             `json:"documentType"`
	DocumentNumber string             `json:"documentNumber"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	Status         string             `json:"status"`
	Amount         *decimal.Decimal   `json:"amount"`
	Currency       *string            `json:"currency"`
	Department     *string            `json:"department"`
	CreatedBy      string             `json:"createdBy"`
	UpdatedBy      *string            `json:"updatedBy"`
	WorkflowID     pgtype.UUID        `json:"workflowId"`
	Data           []byte             `json:"data"`
	Metadata       []byte             `json:"metadata"`
	DeletedAt      pgtype.Timestamptz `json:"deletedAt"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type EmailVerification struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     string             `json:"userId"`
	Email      string             `json:"email"`
	Token      string             `json:"token"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	VerifiedAt pgtype.Timestamptz `json:"verifiedAt"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type EnvironmentVariable struct {
	ID          string             `json:"id"`
	Key         string             `json:"key"`
	Value       *string            `json:"value"`
	Environment string             `json:"environment"`
	IsSecret    *bool              `json:"isSecret"`
	Description *string            `json:"description"`
	IsRequired  *bool              `json:"isRequired"`
	Category    *string            `json:"category"`
	CreatedBy   *string            `json:"createdBy"`
	UpdatedBy   *string            `json:"updatedBy"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type FeatureFlag struct {
	ID              string             `json:"id"`
	Key             string             `json:"key"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	Type            string             `json:"type"`
	DefaultValue    *string            `json:"defaultValue"`
	Enabled         *bool              `json:"enabled"`
	Environment     *string            `json:"environment"`
	Category        *string            `json:"category"`
	Tags            []byte             `json:"tags"`
	Targeting       []byte             `json:"targeting"`
	Variations      []byte             `json:"variations"`
	LastEvaluated   pgtype.Timestamptz `json:"lastEvaluated"`
	EvaluationCount *int64             `json:"evaluationCount"`
	IsArchived      *bool              `json:"isArchived"`
	ExpiresAt       pgtype.Timestamptz `json:"expiresAt"`
	CreatedBy       *string            `json:"createdBy"`
	UpdatedBy       *string            `json:"updatedBy"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

type GoodsReceivedNote struct {
	ID                string             `json:"id"`
	OrganizationID    string             `json:"organizationId"`
	DocumentNumber    string             `json:"documentNumber"`
	PoDocumentNumber  *string            `json:"poDocumentNumber"`
	Status            *string            `json:"status"`
	ReceivedDate      pgtype.Timestamptz `json:"receivedDate"`
	ReceivedBy        *string            `json:"receivedBy"`
	Items             []byte             `json:"items"`
	QualityIssues     []byte             `json:"qualityIssues"`
	ApprovalStage     *int32             `json:"approvalStage"`
	ApprovalHistory   []byte             `json:"approvalHistory"`
	CreatedBy         *string            `json:"createdBy"`
	OwnerID           *string            `json:"ownerId"`
	WarehouseLocation *string            `json:"warehouseLocation"`
	Notes             *string            `json:"notes"`
	StageName         *string            `json:"stageName"`
	ApprovedBy        *string            `json:"approvedBy"`
	AutomationUsed    *bool              `json:"automationUsed"`
	AutoCreatedPv     []byte             `json:"autoCreatedPv"`
	ActionHistory     []byte             `json:"actionHistory"`
	Metadata          []byte             `json:"metadata"`
	BudgetCode        *string            `json:"budgetCode"`
	CostCenter        *string            `json:"costCenter"`
	ProjectCode       *string            `json:"projectCode"`
	DeletedAt         pgtype.Timestamptz `json:"deletedAt"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
	LinkedPv          *string            `json:"linkedPv"`
}

// Impersonation events for audit/security — visible to super_admin only

type LoginAttempt struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        *string            `json:"userId"`
	Email         string             `json:"email"`
	IpAddress     *string            `json:"ipAddress"`
	UserAgent     *string            `json:"userAgent"`
	Success       bool               `json:"success"`
	FailureReason *string            `json:"failureReason"`
	AttemptedAt   pgtype.Timestamptz `json:"attemptedAt"`
}

type Notification struct {
	ID                 pgtype.UUID        `json:"id"`
	OrganizationID     string             `json:"organizationId"`
	RecipientID        string             `json:"recipientId"`
	Type               string             `json:"type"`
	DocumentID         *string            `json:"documentId"`
	DocumentType       *string            `json:"documentType"`
	Subject            string             `json:"subject"`
	Body               string             `json:"body"`
	Sent               *bool              `json:"sent"`
	SentAt             pgtype.Timestamptz `json:"sentAt"`
	EntityID           *string            `json:"entityId"`
	EntityType         *string            `json:"entityType"`
	EntityNumber       *string            `json:"entityNumber"`
	RelatedUserID      *string            `json:"relatedUserId"`
	RelatedUserName    *string            `json:"relatedUserName"`
	IsRead             *bool              `json:"isRead"`
	ReadAt             pgtype.Timestamptz `json:"readAt"`
	ActionTaken        *bool              `json:"actionTaken"`
	ActionTakenAt      pgtype.Timestamptz `json:"actionTakenAt"`
	Importance         *string            `json:"importance"`
	QuickAction        []byte             `json:"quickAction"`
	ReassignmentReason *string            `json:"reassignmentReason"`
	Message            *string            `json:"message"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
}

type NotificationPreference struct {
	ID                     pgtype.UUID        `json:"id"`
	UserID                 string             `json:"userId"`
	OrganizationID         string             `json:"organizationId"`
	EmailEnabled           *bool              `json:"emailEnabled"`
	PushEnabled            *bool              `json:"pushEnabled"`
	InAppEnabled           *bool              `json:"inAppEnabled"`
	NotifyTaskAssigned     *bool              `json:"notifyTaskAssigned"`
	NotifyTaskReassigned   *bool              `json:"notifyTaskReassigned"`
	NotifyTaskApproved     *bool              `json:"notifyTaskApproved"`
	NotifyTaskRejected     *bool              `json:"notifyTaskRejected"`
	NotifyWorkflowComplete *bool              `json:"notifyWorkflowComplete"`
	NotifyApprovalOverdue  *bool              `json:"notifyApprovalOverdue"`
	NotifyCommentsAdded    *bool              `json:"notifyCommentsAdded"`
	QuietHoursEnabled      *bool              `json:"quietHoursEnabled"`
	QuietHoursStart        *int32             `json:"quietHoursStart"`
	QuietHoursEnd          *int32             `json:"quietHoursEnd"`
	CreatedAt              pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt              pgtype.Timestamptz `json:"updatedAt"`
}

type Organization struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	Description  *string            `json:"description"`
	LogoUrl      *string            `json:"logoUrl"`
	PrimaryColor *string            `json:"primaryColor"`
	Active       *bool              `json:"active"`
	Tagline      *string            `json:"tagline"`
	CreatedBy    *string            `json:"createdBy"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type OrganizationBranch struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organizationId"`
	Name           string             `json:"name"`
	Code           *string            `json:"code"`
	ProvinceID     *string            `json:"provinceId"`
	TownID         *string            `json:"townId"`
	Address        *string            `json:"address"`
	ManagerID      *string            `json:"managerId"`
	IsActive       bool               `json:"isActive"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

// Organization departments with manager name support
type OrganizationDepartment struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organizationId"`
	Name           string             `json:"name"`
	Code           *string            `json:"code"`
	Description    *string            `json:"description"`
	ParentID       *string            `json:"parentId"`
	ManagerName    *string            `json:"managerName"`
	IsActive       bool               `json:"isActive"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type OrganizationMember struct {
	ID                string             `json:"id"`
	OrganizationID    string             `json:"organizationId"`
	UserID            string             `json:"userId"`
	Role              string             `json:"role"`
	Department        *string            `json:"department"`
	DepartmentID      *string            `json:"departmentId"`
	Title             *string            `json:"title"`
	BranchID          *string            `json:"branchId"`
	Active            *bool              `json:"active"`
	InvitedAt         pgtype.Timestamptz `json:"invitedAt"`
	JoinedAt          pgtype.Timestamptz `json:"joinedAt"`
	InvitedBy         *string            `json:"invitedBy"`
	CustomPermissions []byte             `json:"customPermissions"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type OrganizationRole struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID *string            `json:"organizationId"`
	Name           string             `json:"name"`
	Description    *string            `json:"description"`
	IsSystemRole   *bool              `json:"isSystemRole"`
	Permissions    []byte             `json:"permissions"`
	Active         *bool              `json:"active"`
	CreatedBy      *string            `json:"createdBy"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type OrganizationSetting struct {
	ID                       string             `json:"id"`
	OrganizationID           string             `json:"organizationId"`
	RequireDigitalSignatures *bool              `json:"requireDigitalSignatures"`
	DefaultApprovalChain     *string            `json:"defaultApprovalChain"`
	Currency                 *string            `json:"currency"`
	FiscalYearStart          *int32             `json:"fiscalYearStart"`
	EnableBudgetValidation   *bool              `json:"enableBudgetValidation"`
	BudgetVarianceThreshold  *decimal.Decimal   `json:"budgetVarianceThreshold"`
	CreatedAt                pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                pgtype.Timestamptz `json:"updatedAt"`
	ProcurementFlow          *string            `json:"procurementFlow"`
}

type PasswordReset struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"userId"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	UsedAt    pgtype.Timestamptz `json:"usedAt"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type PaymentVoucher struct {
	ID                        string             `json:"id"`
	OrganizationID            string             `json:"organizationId"`
	DocumentNumber            string             `json:"documentNumber"`
	VendorID                  *string            `json:"vendorId"`
	InvoiceNumber             *string            `json:"invoiceNumber"`
	Status                    *string            `json:"status"`
	Amount                    *decimal.Decimal   `json:"amount"`
	Currency                  *string            `json:"currency"`
	PaymentMethod             *string            `json:"paymentMethod"`
	GlCode                    *string            `json:"glCode"`
	Description               *string            `json:"description"`
	ApprovalStage             *int32             `json:"approvalStage"`
	ApprovalHistory           []byte             `json:"approvalHistory"`
	LinkedPo                  *string            `json:"linkedPo"`
	Title                     *string            `json:"title"`
	Department                *string            `json:"department"`
	DepartmentID              *string            `json:"departmentId"`
	Priority                  *string            `json:"priority"`
	RequestedByName           *string            `json:"requestedByName"`
	RequestedDate             pgtype.Timestamptz `json:"requestedDate"`
	SubmittedAt               pgtype.Timestamptz `json:"submittedAt"`
	ApprovedAt                pgtype.Timestamptz `json:"approvedAt"`
	PaidDate                  pgtype.Timestamptz `json:"paidDate"`
	PaymentDueDate            pgtype.Timestamptz `json:"paymentDueDate"`
	BudgetCode                *string            `json:"budgetCode"`
	CostCenter                *string            `json:"costCenter"`
	ProjectCode               *string            `json:"projectCode"`
	TaxAmount                 *decimal.Decimal   `json:"taxAmount"`
	WithholdingTaxAmount      *decimal.Decimal   `json:"withholdingTaxAmount"`
	PaidAmount                *decimal.Decimal   `json:"paidAmount"`
	SourcePurchaseOrderNumber *string            `json:"sourcePurchaseOrderNumber"`
	SourceRequisitionNumber   *string            `json:"sourceRequisitionNumber"`
	BankDetails               []byte             `json:"bankDetails"`
	Items                     []byte             `json:"items"`
	CreatedBy                 *string            `json:"createdBy"`
	OwnerID                   *string            `json:"ownerId"`
	ActionHistory             []byte             `json:"actionHistory"`
	Metadata                  []byte             `json:"metadata"`
	DeletedAt                 pgtype.Timestamptz `json:"deletedAt"`
	CreatedAt                 pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                 pgtype.Timestamptz `json:"updatedAt"`
	LinkedGrn                 *string            `json:"linkedGrn"`
}

type Province struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Code string      `json:"code"`
}

type PurchaseOrder struct {
	ID                      string             `json:"id"`
	OrganizationID          string             `json:"organizationId"`
	DocumentNumber          string             `json:"documentNumber"`
	VendorID                *string            `json:"vendorId"`
	Status                  *string            `json:"status"`
	Items                   []byte             `json:"items"`
	TotalAmount             *decimal.Decimal   `json:"totalAmount"`
	Currency                *string            `json:"currency"`
	DeliveryDate            pgtype.Timestamptz `json:"deliveryDate"`
	ApprovalStage           *int32             `json:"approvalStage"`
	ApprovalHistory         []byte             `json:"approvalHistory"`
	LinkedRequisition       *string            `json:"linkedRequisition"`
	Description             *string            `json:"description"`
	Department              *string            `json:"department"`
	DepartmentID            *string            `json:"departmentId"`
	GlCode                  *string            `json:"glCode"`
	Title                   *string            `json:"title"`
	Priority                *string            `json:"priority"`
	Subtotal                *decimal.Decimal   `json:"subtotal"`
	Tax                     *decimal.Decimal   `json:"tax"`
	Total                   *decimal.Decimal   `json:"total"`
	BudgetCode              *string            `json:"budgetCode"`
	CostCenter              *string            `json:"costCenter"`
	ProjectCode             *string            `json:"projectCode"`
	RequiredByDate          pgtype.Timestamptz `json:"requiredByDate"`
	SourceRequisitionNumber *string            `json:"sourceRequisitionNumber"`
	SourceRequisitionID     *string            `json:"sourceRequisitionId"`
	CreatedBy               *string            `json:"createdBy"`
	OwnerID                 *string            `json:"ownerId"`
	ActionHistory           []byte             `json:"actionHistory"`
	Metadata                []byte             `json:"metadata"`
	EstimatedCost           decimal.Decimal    `json:"estimatedCost"`
	QuotationGateOverridden bool               `json:"quotationGateOverridden"`
	BypassJustification     string             `json:"bypassJustification"`
	AutomationUsed          *bool              `json:"automationUsed"`
	AutoCreatedGrn          []byte             `json:"autoCreatedGrn"`
	DeletedAt               pgtype.Timestamptz `json:"deletedAt"`
	CreatedAt               pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt               pgtype.Timestamptz `json:"updatedAt"`
	ProcurementFlow         *string            `json:"procurementFlow"`
}

type Requisition struct {
	ID                string             `json:"id"`
	OrganizationID    string             `json:"organizationId"`
	DocumentNumber    string             `json:"documentNumber"`
	RequesterID       string             `json:"requesterId"`
	Title             string             `json:"title"`
	Description       *string            `json:"description"`
	Department        *string            `json:"department"`
	DepartmentID      *string            `json:"departmentId"`
	Status            *string            `json:"status"`
	Priority          *string            `json:"priority"`
	Items             []byte             `json:"items"`
	TotalAmount       *decimal.Decimal   `json:"totalAmount"`
	Currency          *string            `json:"currency"`
	ApprovalStage     *int32             `json:"approvalStage"`
	ApprovalHistory   []byte             `json:"approvalHistory"`
	ActionHistory     []byte             `json:"actionHistory"`
	CategoryID        *string            `json:"categoryId"`
	PreferredVendorID *string            `json:"preferredVendorId"`
	IsEstimate        *bool              `json:"isEstimate"`
	RequiredByDate    pgtype.Timestamptz `json:"requiredByDate"`
	CostCenter        *string            `json:"costCenter"`
	ProjectCode       *string            `json:"projectCode"`
	BudgetCode        *string            `json:"budgetCode"`
	SourceOfFunds     *string            `json:"sourceOfFunds"`
	CreatedBy         *string            `json:"createdBy"`
	CreatedByName     *string            `json:"createdByName"`
	CreatedByRole     *string            `json:"createdByRole"`
	Metadata          []byte             `json:"metadata"`
	AutomationUsed    *bool              `json:"automationUsed"`
	AutoCreatedPo     []byte             `json:"autoCreatedPo"`
	DeletedAt         pgtype.Timestamptz `json:"deletedAt"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type Session struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       string             `json:"userId"`
	RefreshToken string             `json:"refreshToken"`
	IpAddress    *string            `json:"ipAddress"`
	UserAgent    *string            `json:"userAgent"`
	ExpiresAt    pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

// Tracks individual approvals per workflow stage
type StageApprovalRecord struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organizationId"`
	WorkflowTaskID string             `json:"workflowTaskId"`
	StageNumber    int32              `json:"stageNumber"`
	ApproverID     string             `json:"approverId"`
	ApproverName   string             `json:"approverName"`
	ApproverRole   string             `json:"approverRole"`
	ManNumber      string             `json:"manNumber"`
	Position       string             `json:"position"`
	Action         string             `json:"action"`
	Comments       *string            `json:"comments"`
	Signature      *string            `json:"signature"`
	ApprovedAt     pgtype.Timestamptz `json:"approvedAt"`
	IpAddress      *string            `json:"ipAddress"`
	UserAgent      *string            `json:"userAgent"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
}

type SystemSetting struct {
	ID           string             `json:"id"`
	Key          string             `json:"key"`
	Value        *string            `json:"value"`
	Type         string             `json:"type"`
	Category     string             `json:"category"`
	Description  *string            `json:"description"`
	DefaultValue *string            `json:"defaultValue"`
	IsRequired   *bool              `json:"isRequired"`
	IsSecret     *bool              `json:"isSecret"`
	Environment  *string            `json:"environment"`
	Validation   []byte             `json:"validation"`
	CreatedBy    *string            `json:"createdBy"`
	UpdatedBy    *string            `json:"updatedBy"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

// Round-robin task assignment history
type TaskAssignmentHistory struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organizationId"`
	Role           string             `json:"role"`
	AssignedUserID string             `json:"assignedUserId"`
	AssignedAt     pgtype.Timestamptz `json:"assignedAt"`
}

type Town struct {
	ID         pgtype.UUID `json:"id"`
	ProvinceID pgtype.UUID `json:"provinceId"`
	Name       string      `json:"name"`
	Code       *string     `json:"code"`
}

type User struct {
	ID                    string             `json:"id"`
	Email                 string             `json:"email"`
	Name                  string             `json:"name"`
	Password              string             `json:"password"`
	Role                  string             `json:"role"`
	Active                bool               `json:"active"`
	LastLogin             pgtype.Timestamp   `json:"lastLogin"`
	CurrentOrganizationID *string            `json:"currentOrganizationId"`
	IsSuperAdmin          bool               `json:"isSuperAdmin"`
	Preferences           []byte             `json:"preferences"`
	DeletedAt             pgtype.Timestamp   `json:"deletedAt"`
	Position              *string            `json:"position"`
	ManNumber             *string            `json:"manNumber"`
	NrcNumber             *string            `json:"nrcNumber"`
	Contact               *string            `json:"contact"`
	MfaEnabled            bool               `json:"mfaEnabled"`
	IsLdapUser            bool               `json:"isLdapUser"`
	MustChangePassword    bool               `json:"mustChangePassword"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

// User action audit trail — no FK on user_id to avoid lock contention
type UserActivityLog struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         string             `json:"userId"`
	OrganizationID *string            `json:"organizationId"`
	ActionType     string             `json:"actionType"`
	ResourceType   *string            `json:"resourceType"`
	ResourceID     *string            `json:"resourceId"`
	IpAddress      *string            `json:"ipAddress"`
	UserAgent      *string            `json:"userAgent"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
}

type UserOrganizationRole struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         string             `json:"userId"`
	OrganizationID string             `json:"organizationId"`
	RoleID         pgtype.UUID        `json:"roleId"`
	AssignedBy     *string            `json:"assignedBy"`
	AssignedAt     pgtype.Timestamptz `json:"assignedAt"`
	Active         *bool              `json:"active"`
}

// Organization-scoped vendors for multi-tenant security
type Vendor struct {
	ID              string             `json:"id"`
	OrganizationID  string             `json:"organizationId"`
	VendorCode      string             `json:"vendorCode"`
	Name            string             `json:"name"`
	Email           *string            `json:"email"`
	Phone           *string            `json:"phone"`
	Country         *string            `json:"country"`
	City            *string            `json:"city"`
	BankAccount     *string            `json:"bankAccount"`
	BankName        string             `json:"bankName"`
	AccountName     string             `json:"accountName"`
	AccountNumber   string             `json:"accountNumber"`
	BranchCode      string             `json:"branchCode"`
	SwiftCode       string             `json:"swiftCode"`
	ContactPerson   string             `json:"contactPerson"`
	PhysicalAddress string             `json:"physicalAddress"`
	TaxID           *string            `json:"taxId"`
	Active          *bool              `json:"active"`
	DeletedAt       pgtype.Timestamptz `json:"deletedAt"`
	CreatedBy       *string            `json:"createdBy"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

// Workflow definitions with frontend compatibility
type Workflow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID string             `json:"organizationId"`
	Name           string             `json:"name"`
	Description    *string            `json:"description"`
	DocumentType   string             `json:"documentType"`
	EntityType     string             `json:"entityType"`
	Version        *int32             `json:"version"`
	Stages         json.RawMessage    `json:"stages"`
	Conditions     []byte             `json:"conditions"`
	IsActive       *bool              `json:"isActive"`
	IsDefault      *bool              `json:"isDefault"`
	CreatedBy      *string            `json:"createdBy"`
	DeletedAt      pgtype.Timestamptz `json:"deletedAt"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

// Tracks workflow execution for specific entities
type WorkflowAssignment struct {
	ID              string             `json:"id"`
	OrganizationID  string             `json:"organizationId"`
	EntityID        string             `json:"entityId"`
	EntityType      string             `json:"entityType"`
	WorkflowID      pgtype.UUID        `json:"workflowId"`
	WorkflowVersion int32              `json:"workflowVersion"`
	CurrentStage    *int32             `json:"currentStage"`
	Status          *string            `json:"status"`
	StageHistory    []byte             `json:"stageHistory"`
	AssignedAt      pgtype.Timestamptz `json:"assignedAt"`
	AssignedBy      string             `json:"assignedBy"`
	CompletedAt     pgtype.Timestamptz `json:"completedAt"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

// Default workflow mappings for entity types per organization
type WorkflowDefault struct {
	ID                     string             `json:"id"`
	OrganizationID         string             `json:"organizationId"`
	EntityType             string             `json:"entityType"`
	DefaultWorkflowID      pgtype.UUID        `json:"defaultWorkflowId"`
	DefaultWorkflowVersion int32              `json:"defaultWorkflowVersion"`
	SetBy                  string             `json:"setBy"`
	SetAt                  pgtype.Timestamptz `json:"setAt"`
}

// Individual approval tasks within workflow assignments with concurrency control
type WorkflowTask struct {
	ID                   string             `json:"id"`
	OrganizationID       string             `json:"organizationId"`
	WorkflowAssignmentID string             `json:"workflowAssignmentId"`
	EntityID             string             `json:"entityId"`
	EntityType           string             `json:"entityType"`
	StageNumber          int32              `json:"stageNumber"`
	StageName            string             `json:"stageName"`
	AssignmentType       *string            `json:"assignmentType"`
	AssignedRole         *string            `json:"assignedRole"`
	AssignedUserID       *string            `json:"assignedUserId"`
	Status               *string            `json:"status"`
	Priority             *string            `json:"priority"`
	ClaimedAt            pgtype.Timestamptz `json:"claimedAt"`
	ClaimedBy            *string            `json:"claimedBy"`
	ClaimExpiry          pgtype.Timestamptz `json:"claimExpiry"`
	CompletedAt          pgtype.Timestamptz `json:"completedAt"`
	DueDate              pgtype.Timestamptz `json:"dueDate"`
	Version              int32              `json:"version"`
	UpdatedBy            *string            `json:"updatedBy"`
	CreatedAt            pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt            pgtype.Timestamptz `json:"updatedAt"`
}
