// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*) FROM notifications
WHERE recipient_id = $1
  AND ($2::text       = '' OR organization_id = $2)
  AND ($3::text       = '' OR type            = $3)
  AND ($4::bool       IS NULL OR is_read      = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
`

type CountNotificationsParams struct {
	RecipientID string             `json:"recipientId"`
	Column2     string             `json:"column2"`
	Column3     string             `json:"column3"`
	Column4     bool               `json:"column4"`
	Column5     pgtype.Timestamptz `json:"column5"`
	Column6     pgtype.Timestamptz `json:"column6"`
}

func (q *Queries) CountNotifications(ctx context.Context, arg CountNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications,
		arg.RecipientID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE recipient_id = $1 AND is_read = false
`

type CountUnreadNotificationsParams struct {
	RecipientID string `json:"recipientId"`
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.RecipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (
    id, organization_id, recipient_id, type, document_id, document_type,
    subject, body, sent, sent_at, entity_id, entity_type, entity_number,
    related_user_id, related_user_name, is_read, importance, quick_action,
    reassignment_reason, message
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
) RETURNING id, organization_id, recipient_id, type, document_id, document_type, subject, body, sent, sent_at, entity_id, entity_type, entity_number, related_user_id, related_user_name, is_read, read_at, action_taken, action_taken_at, importance, quick_action, reassignment_reason, message, created_at, updated_at
`

type CreateNotificationParams struct {
	ID                 pgtype.UUID        `json:"id"`
	OrganizationID     string             `json:"organizationId"`
	RecipientID        string             `json:"recipientId"`
	Type               string             `json:"type"`
	DocumentID         *string            `json:"documentId"`
	DocumentType       *string            `json:"documentType"`
	Subject            string             `json:"subject"`
	Body               string             `json:"body"`
	Sent               *bool              `json:"sent"`
	SentAt             pgtype.Timestamptz `json:"sentAt"`
	EntityID           *string            `json:"entityId"`
	EntityType         *string            `json:"entityType"`
	EntityNumber       *string            `json:"entityNumber"`
	RelatedUserID      *string            `json:"relatedUserId"`
	RelatedUserName    *string            `json:"relatedUserName"`
	IsRead             *bool              `json:"isRead"`
	Importance         *string            `json:"importance"`
	QuickAction        []byte             `json:"quickAction"`
	ReassignmentReason *string            `json:"reassignmentReason"`
	Message            *string            `json:"message"`
}

// Notification queries
// User-scoped notification CRUD operations and bulk-update helpers.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.OrganizationID,
		arg.RecipientID,
		arg.Type,
		arg.DocumentID,
		arg.DocumentType,
		arg.Subject,
		arg.Body,
		arg.Sent,
		arg.SentAt,
		arg.EntityID,
		arg.EntityType,
		arg.EntityNumber,
		arg.RelatedUserID,
		arg.RelatedUserName,
		arg.IsRead,
		arg.Importance,
		arg.QuickAction,
		arg.ReassignmentReason,
		arg.Message,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RecipientID,
		&i.Type,
		&i.DocumentID,
		&i.DocumentType,
		&i.Subject,
		&i.Body,
		&i.Sent,
		&i.SentAt,
		&i.EntityID,
		&i.EntityType,
		&i.EntityNumber,
		&i.RelatedUserID,
		&i.RelatedUserName,
		&i.IsRead,
		&i.ReadAt,
		&i.ActionTaken,
		&i.ActionTakenAt,
		&i.Importance,
		&i.QuickAction,
		&i.ReassignmentReason,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE id = $1
`

type DeleteNotificationParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID)
	return err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications WHERE created_at < $1
`

type DeleteOldNotificationsParams struct {
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) DeleteOldNotifications(ctx context.Context, arg DeleteOldNotificationsParams) error {
	_, err := q.db.Exec(ctx, deleteOldNotifications, arg.CreatedAt)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, organization_id, recipient_id, type, document_id, document_type, subject, body, sent, sent_at, entity_id, entity_type, entity_number, related_user_id, related_user_name, is_read, read_at, action_taken, action_taken_at, importance, quick_action, reassignment_reason, message, created_at, updated_at FROM notifications WHERE id = $1
`

type GetNotificationByIDParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, arg.ID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RecipientID,
		&i.Type,
		&i.DocumentID,
		&i.DocumentType,
		&i.Subject,
		&i.Body,
		&i.Sent,
		&i.SentAt,
		&i.EntityID,
		&i.EntityType,
		&i.EntityNumber,
		&i.RelatedUserID,
		&i.RelatedUserName,
		&i.IsRead,
		&i.ReadAt,
		&i.ActionTaken,
		&i.ActionTakenAt,
		&i.Importance,
		&i.QuickAction,
		&i.ReassignmentReason,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, organization_id, recipient_id, type, document_id, document_type, subject, body, sent, sent_at, entity_id, entity_type, entity_number, related_user_id, related_user_name, is_read, read_at, action_taken, action_taken_at, importance, quick_action, reassignment_reason, message, created_at, updated_at FROM notifications
WHERE recipient_id = $1
  AND ($2::text       = '' OR organization_id = $2)
  AND ($3::text       = '' OR type            = $3)
  AND ($4::bool       IS NULL OR is_read      = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
ORDER BY created_at DESC
LIMIT $7 OFFSET $8
`

type ListNotificationsParams struct {
	RecipientID string             `json:"recipientId"`
	Column2     string             `json:"column2"`
	Column3     string             `json:"column3"`
	Column4     bool               `json:"column4"`
	Column5     pgtype.Timestamptz `json:"column5"`
	Column6     pgtype.Timestamptz `json:"column6"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.RecipientID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RecipientID,
			&i.Type,
			&i.DocumentID,
			&i.DocumentType,
			&i.Subject,
			&i.Body,
			&i.Sent,
			&i.SentAt,
			&i.EntityID,
			&i.EntityType,
			&i.EntityNumber,
			&i.RelatedUserID,
			&i.RelatedUserName,
			&i.IsRead,
			&i.ReadAt,
			&i.ActionTaken,
			&i.ActionTakenAt,
			&i.Importance,
			&i.QuickAction,
			&i.ReassignmentReason,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsentNotifications = `-- name: ListUnsentNotifications :many
SELECT id, organization_id, recipient_id, type, document_id, document_type, subject, body, sent, sent_at, entity_id, entity_type, entity_number, related_user_id, related_user_name, is_read, read_at, action_taken, action_taken_at, importance, quick_action, reassignment_reason, message, created_at, updated_at FROM notifications
WHERE sent = false
ORDER BY created_at ASC
LIMIT $1
`

type ListUnsentNotificationsParams struct {
	Limit int32 `json:"limit"`
}

func (q *Queries) ListUnsentNotifications(ctx context.Context, arg ListUnsentNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnsentNotifications, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RecipientID,
			&i.Type,
			&i.DocumentID,
			&i.DocumentType,
			&i.Subject,
			&i.Body,
			&i.Sent,
			&i.SentAt,
			&i.EntityID,
			&i.EntityType,
			&i.EntityNumber,
			&i.RelatedUserID,
			&i.RelatedUserName,
			&i.IsRead,
			&i.ReadAt,
			&i.ActionTaken,
			&i.ActionTakenAt,
			&i.Importance,
			&i.QuickAction,
			&i.ReassignmentReason,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET is_read = true,
    read_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type MarkNotificationReadParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notifications
SET sent = true,
    sent_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type MarkNotificationSentParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) error {
	_, err := q.db.Exec(ctx, markNotificationSent, arg.ID)
	return err
}

const markNotificationsReadBulk = `-- name: MarkNotificationsReadBulk :exec
UPDATE notifications
SET is_read = true,
    read_at = NOW(),
    updated_at = NOW()
WHERE id::text = ANY($1::text[])
`

type MarkNotificationsReadBulkParams struct {
	Column1 []string `json:"column1"`
}

func (q *Queries) MarkNotificationsReadBulk(ctx context.Context, arg MarkNotificationsReadBulkParams) error {
	_, err := q.db.Exec(ctx, markNotificationsReadBulk, arg.Column1)
	return err
}

const updateNotificationActionTaken = `-- name: UpdateNotificationActionTaken :exec
UPDATE notifications
SET action_taken = true,
    action_taken_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type UpdateNotificationActionTakenParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateNotificationActionTaken(ctx context.Context, arg UpdateNotificationActionTakenParams) error {
	_, err := q.db.Exec(ctx, updateNotificationActionTaken, arg.ID)
	return err
}
