// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_preferences.sql

package db

import (
	"context"
)

const deleteNotificationPreferences = `-- name: DeleteNotificationPreferences :exec
DELETE FROM notification_preferences WHERE user_id = $1
`

type DeleteNotificationPreferencesParams struct {
	UserID string `json:"userId"`
}

func (q *Queries) DeleteNotificationPreferences(ctx context.Context, arg DeleteNotificationPreferencesParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationPreferences, arg.UserID)
	return err
}

const getNotificationPreferencesByUser = `-- name: GetNotificationPreferencesByUser :one

SELECT id, user_id, organization_id, email_enabled, push_enabled, in_app_enabled, notify_task_assigned, notify_task_reassigned, notify_task_approved, notify_task_rejected, notify_workflow_complete, notify_approval_overdue, notify_comments_added, quiet_hours_enabled, quiet_hours_start, quiet_hours_end, created_at, updated_at FROM notification_preferences
WHERE user_id = $1 AND organization_id = $2
`

type GetNotificationPreferencesByUserParams struct {
	UserID         string `json:"userId"`
	OrganizationID string `json:"organizationId"`
}

// Notification preferences queries
// Per-user notification settings (one row per user; user_id is UNIQUE).
func (q *Queries) GetNotificationPreferencesByUser(ctx context.Context, arg GetNotificationPreferencesByUserParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferencesByUser, arg.UserID, arg.OrganizationID)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.EmailEnabled,
		&i.PushEnabled,
		&i.InAppEnabled,
		&i.NotifyTaskAssigned,
		&i.NotifyTaskReassigned,
		&i.NotifyTaskApproved,
		&i.NotifyTaskRejected,
		&i.NotifyWorkflowComplete,
		&i.NotifyApprovalOverdue,
		&i.NotifyCommentsAdded,
		&i.QuietHoursEnabled,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (
    user_id, organization_id,
    email_enabled, push_enabled, in_app_enabled,
    notify_task_assigned, notify_task_reassigned, notify_task_approved,
    notify_task_rejected, notify_workflow_complete, notify_approval_overdue,
    notify_comments_added,
    quiet_hours_enabled, quiet_hours_start, quiet_hours_end
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (user_id) DO UPDATE SET
    organization_id          = EXCLUDED.organization_id,
    email_enabled            = EXCLUDED.email_enabled,
    push_enabled             = EXCLUDED.push_enabled,
    in_app_enabled           = EXCLUDED.in_app_enabled,
    notify_task_assigned     = EXCLUDED.notify_task_assigned,
    notify_task_reassigned   = EXCLUDED.notify_task_reassigned,
    notify_task_approved     = EXCLUDED.notify_task_approved,
    notify_task_rejected     = EXCLUDED.notify_task_rejected,
    notify_workflow_complete = EXCLUDED.notify_workflow_complete,
    notify_approval_overdue  = EXCLUDED.notify_approval_overdue,
    notify_comments_added    = EXCLUDED.notify_comments_added,
    quiet_hours_enabled      = EXCLUDED.quiet_hours_enabled,
    quiet_hours_start        = EXCLUDED.quiet_hours_start,
    quiet_hours_end          = EXCLUDED.quiet_hours_end,
    updated_at               = NOW()
RETURNING id, user_id, organization_id, email_enabled, push_enabled, in_app_enabled, notify_task_assigned, notify_task_reassigned, notify_task_approved, notify_task_rejected, notify_workflow_complete, notify_approval_overdue, notify_comments_added, quiet_hours_enabled, quiet_hours_start, quiet_hours_end, created_at, updated_at
`

type UpsertNotificationPreferencesParams struct {
	UserID                 string `json:"userId"`
	OrganizationID         string `json:"organizationId"`
	EmailEnabled           *bool  `json:"emailEnabled"`
	PushEnabled            *bool  `json:"pushEnabled"`
	InAppEnabled           *bool  `json:"inAppEnabled"`
	NotifyTaskAssigned     *bool  `json:"notifyTaskAssigned"`
	NotifyTaskReassigned   *bool  `json:"notifyTaskReassigned"`
	NotifyTaskApproved     *bool  `json:"notifyTaskApproved"`
	NotifyTaskRejected     *bool  `json:"notifyTaskRejected"`
	NotifyWorkflowComplete *bool  `json:"notifyWorkflowComplete"`
	NotifyApprovalOverdue  *bool  `json:"notifyApprovalOverdue"`
	NotifyCommentsAdded    *bool  `json:"notifyCommentsAdded"`
	QuietHoursEnabled      *bool  `json:"quietHoursEnabled"`
	QuietHoursStart        *int32 `json:"quietHoursStart"`
	QuietHoursEnd          *int32 `json:"quietHoursEnd"`
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences,
		arg.UserID,
		arg.OrganizationID,
		arg.EmailEnabled,
		arg.PushEnabled,
		arg.InAppEnabled,
		arg.NotifyTaskAssigned,
		arg.NotifyTaskReassigned,
		arg.NotifyTaskApproved,
		arg.NotifyTaskRejected,
		arg.NotifyWorkflowComplete,
		arg.NotifyApprovalOverdue,
		arg.NotifyCommentsAdded,
		arg.QuietHoursEnabled,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.EmailEnabled,
		&i.PushEnabled,
		&i.InAppEnabled,
		&i.NotifyTaskAssigned,
		&i.NotifyTaskReassigned,
		&i.NotifyTaskApproved,
		&i.NotifyTaskRejected,
		&i.NotifyWorkflowComplete,
		&i.NotifyApprovalOverdue,
		&i.NotifyCommentsAdded,
		&i.QuietHoursEnabled,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
