// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*) FROM organizations
WHERE ($1::bool IS NULL OR active = $1)
  AND ($2::text = '' OR (name ILIKE '%' || $2 || '%' OR slug ILIKE '%' || $2 || '%'))
`

type CountOrganizationsParams struct {
	Column1 bool   `json:"column1"`
	Column2 string `json:"column2"`
}

func (q *Queries) CountOrganizations(ctx context.Context, arg CountOrganizationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one

INSERT INTO organizations (
    id, name, slug, description, logo_url, primary_color, active, tagline, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, name, slug, description, logo_url, primary_color, active, tagline, created_by, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Slug         string  `json:"slug"`
	Description  *string `json:"description"`
	LogoUrl      *string `json:"logoUrl"`
	PrimaryColor *string `json:"primaryColor"`
	Active       *bool   `json:"active"`
	Tagline      *string `json:"tagline"`
	CreatedBy    *string `json:"createdBy"`
}

// Organization queries
// The organizations table has no deleted_at column; soft-delete uses active = false.
func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.LogoUrl,
		arg.PrimaryColor,
		arg.Active,
		arg.Tagline,
		arg.CreatedBy,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.Active,
		&i.Tagline,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, description, logo_url, primary_color, active, tagline, created_by, created_at, updated_at FROM organizations WHERE id = $1
`

type GetOrganizationByIDParams struct {
	ID string `json:"id"`
}

func (q *Queries) GetOrganizationByID(ctx context.Context, arg GetOrganizationByIDParams) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.Active,
		&i.Tagline,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, description, logo_url, primary_color, active, tagline, created_by, created_at, updated_at FROM organizations WHERE slug = $1
`

type GetOrganizationBySlugParams struct {
	Slug string `json:"slug"`
}

func (q *Queries) GetOrganizationBySlug(ctx context.Context, arg GetOrganizationBySlugParams) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.Active,
		&i.Tagline,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, slug, description, logo_url, primary_color, active, tagline, created_by, created_at, updated_at FROM organizations
WHERE ($1::bool IS NULL OR active = $1)
  AND ($2::text = '' OR (name ILIKE '%' || $2 || '%' OR slug ILIKE '%' || $2 || '%'))
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListOrganizationsParams struct {
	Column1 bool   `json:"column1"`
	Column2 string `json:"column2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.Active,
			&i.Tagline,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOrganization = `-- name: SoftDeleteOrganization :exec
UPDATE organizations SET active = false, updated_at = NOW() WHERE id = $1
`

type SoftDeleteOrganizationParams struct {
	ID string `json:"id"`
}

func (q *Queries) SoftDeleteOrganization(ctx context.Context, arg SoftDeleteOrganizationParams) error {
	_, err := q.db.Exec(ctx, softDeleteOrganization, arg.ID)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations SET
    name          = COALESCE($2, name),
    slug          = COALESCE($3, slug),
    description   = COALESCE($4, description),
    logo_url      = COALESCE($5, logo_url),
    primary_color = COALESCE($6, primary_color),
    tagline       = COALESCE($7, tagline),
    active        = COALESCE($8, active),
    updated_at    = NOW()
WHERE id = $1
RETURNING id, name, slug, description, logo_url, primary_color, active, tagline, created_by, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Slug         string  `json:"slug"`
	Description  *string `json:"description"`
	LogoUrl      *string `json:"logoUrl"`
	PrimaryColor *string `json:"primaryColor"`
	Tagline      *string `json:"tagline"`
	Active       *bool   `json:"active"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.LogoUrl,
		arg.PrimaryColor,
		arg.Tagline,
		arg.Active,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.Active,
		&i.Tagline,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
