// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_departments.sql

package db

import (
	"context"
)

const countDepartments = `-- name: CountDepartments :one
SELECT COUNT(*) FROM organization_departments
WHERE organization_id = $1
  AND ($2::bool IS NULL OR is_active = $2)
`

type CountDepartmentsParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        bool   `json:"column2"`
}

func (q *Queries) CountDepartments(ctx context.Context, arg CountDepartmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartments, arg.OrganizationID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :one

INSERT INTO organization_departments (
    id, organization_id, name, code, description, parent_id, manager_name, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, organization_id, name, code, description, parent_id, manager_name, is_active, created_at, updated_at
`

type CreateDepartmentParams struct {
	ID             string  `json:"id"`
	OrganizationID string  `json:"organizationId"`
	Name           string  `json:"name"`
	Code           *string `json:"code"`
	Description    *string `json:"description"`
	ParentID       *string `json:"parentId"`
	ManagerName    *string `json:"managerName"`
	IsActive       bool    `json:"isActive"`
}

// Organization departments queries
// Tree-structured departments scoped to an organization. No deleted_at column.
func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (OrganizationDepartment, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.ParentID,
		arg.ManagerName,
		arg.IsActive,
	)
	var i OrganizationDepartment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.ParentID,
		&i.ManagerName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM organization_departments WHERE id = $1
`

type DeleteDepartmentParams struct {
	ID string `json:"id"`
}

func (q *Queries) DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) error {
	_, err := q.db.Exec(ctx, deleteDepartment, arg.ID)
	return err
}

const getDepartmentByCode = `-- name: GetDepartmentByCode :one
SELECT id, organization_id, name, code, description, parent_id, manager_name, is_active, created_at, updated_at FROM organization_departments
WHERE organization_id = $1 AND code = $2
`

type GetDepartmentByCodeParams struct {
	OrganizationID string  `json:"organizationId"`
	Code           *string `json:"code"`
}

func (q *Queries) GetDepartmentByCode(ctx context.Context, arg GetDepartmentByCodeParams) (OrganizationDepartment, error) {
	row := q.db.QueryRow(ctx, getDepartmentByCode, arg.OrganizationID, arg.Code)
	var i OrganizationDepartment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.ParentID,
		&i.ManagerName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, organization_id, name, code, description, parent_id, manager_name, is_active, created_at, updated_at FROM organization_departments WHERE id = $1
`

type GetDepartmentByIDParams struct {
	ID string `json:"id"`
}

func (q *Queries) GetDepartmentByID(ctx context.Context, arg GetDepartmentByIDParams) (OrganizationDepartment, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, arg.ID)
	var i OrganizationDepartment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.ParentID,
		&i.ManagerName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDepartments = `-- name: ListActiveDepartments :many
SELECT id, organization_id, name, code, description, parent_id, manager_name, is_active, created_at, updated_at FROM organization_departments
WHERE organization_id = $1 AND is_active = true
ORDER BY name ASC
`

type ListActiveDepartmentsParams struct {
	OrganizationID string `json:"organizationId"`
}

func (q *Queries) ListActiveDepartments(ctx context.Context, arg ListActiveDepartmentsParams) ([]OrganizationDepartment, error) {
	rows, err := q.db.Query(ctx, listActiveDepartments, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationDepartment{}
	for rows.Next() {
		var i OrganizationDepartment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.ParentID,
			&i.ManagerName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, organization_id, name, code, description, parent_id, manager_name, is_active, created_at, updated_at FROM organization_departments
WHERE organization_id = $1
  AND ($2::bool IS NULL OR is_active = $2)
ORDER BY name ASC
LIMIT $3 OFFSET $4
`

type ListDepartmentsParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        bool   `json:"column2"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]OrganizationDepartment, error) {
	rows, err := q.db.Query(ctx, listDepartments,
		arg.OrganizationID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationDepartment{}
	for rows.Next() {
		var i OrganizationDepartment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.ParentID,
			&i.ManagerName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE organization_departments SET
    name         = COALESCE($2, name),
    code         = COALESCE($3, code),
    description  = COALESCE($4, description),
    parent_id    = COALESCE($5, parent_id),
    manager_name = COALESCE($6, manager_name),
    is_active    = COALESCE($7, is_active),
    updated_at   = NOW()
WHERE id = $1
RETURNING id, organization_id, name, code, description, parent_id, manager_name, is_active, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Code        *string `json:"code"`
	Description *string `json:"description"`
	ParentID    *string `json:"parentId"`
	ManagerName *string `json:"managerName"`
	IsActive    bool    `json:"isActive"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (OrganizationDepartment, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.ParentID,
		arg.ManagerName,
		arg.IsActive,
	)
	var i OrganizationDepartment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.ParentID,
		&i.ManagerName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
