// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserRole = `-- name: AssignUserRole :one
INSERT INTO user_organization_roles (
    user_id, organization_id, role_id, assigned_by
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, organization_id, role_id, assigned_by, assigned_at, active
`

type AssignUserRoleParams struct {
	UserID         string      `json:"userId"`
	OrganizationID string      `json:"organizationId"`
	RoleID         pgtype.UUID `json:"roleId"`
	AssignedBy     *string     `json:"assignedBy"`
}

// User role assignments
func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) (UserOrganizationRole, error) {
	row := q.db.QueryRow(ctx, assignUserRole,
		arg.UserID,
		arg.OrganizationID,
		arg.RoleID,
		arg.AssignedBy,
	)
	var i UserOrganizationRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.RoleID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.Active,
	)
	return i, err
}

const countCustomRoles = `-- name: CountCustomRoles :one
SELECT COUNT(*) FROM organization_roles
WHERE organization_id = $1 AND is_system_role = false AND active = true
`

type CountCustomRolesParams struct {
	OrganizationID *string `json:"organizationId"`
}

func (q *Queries) CountCustomRoles(ctx context.Context, arg CountCustomRolesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomRoles, arg.OrganizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationRoles = `-- name: CountOrganizationRoles :one
SELECT COUNT(*) FROM organization_roles
WHERE ((organization_id = $1 AND active = true) OR (organization_id IS NULL AND is_system_role = true AND active = true))
`

type CountOrganizationRolesParams struct {
	OrganizationID *string `json:"organizationId"`
}

func (q *Queries) CountOrganizationRoles(ctx context.Context, arg CountOrganizationRolesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationRoles, arg.OrganizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganizationRole = `-- name: CreateOrganizationRole :one

INSERT INTO organization_roles (
    organization_id, name, description, is_system_role, permissions, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at
`

type CreateOrganizationRoleParams struct {
	OrganizationID *string `json:"organizationId"`
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	IsSystemRole   *bool   `json:"isSystemRole"`
	Permissions    []byte  `json:"permissions"`
	CreatedBy      *string `json:"createdBy"`
}

// Enhanced RBAC with global system roles + org custom roles
func (q *Queries) CreateOrganizationRole(ctx context.Context, arg CreateOrganizationRoleParams) (OrganizationRole, error) {
	row := q.db.QueryRow(ctx, createOrganizationRole,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.IsSystemRole,
		arg.Permissions,
		arg.CreatedBy,
	)
	var i OrganizationRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.IsSystemRole,
		&i.Permissions,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateOrganizationRole = `-- name: DeactivateOrganizationRole :exec
UPDATE organization_roles SET
    active = false,
    updated_at = NOW()
WHERE id = $1 AND is_system_role = false
`

type DeactivateOrganizationRoleParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) DeactivateOrganizationRole(ctx context.Context, arg DeactivateOrganizationRoleParams) error {
	_, err := q.db.Exec(ctx, deactivateOrganizationRole, arg.ID)
	return err
}

const getOrganizationRoleByID = `-- name: GetOrganizationRoleByID :one
SELECT id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at FROM organization_roles WHERE id = $1 AND active = true
`

type GetOrganizationRoleByIDParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) GetOrganizationRoleByID(ctx context.Context, arg GetOrganizationRoleByIDParams) (OrganizationRole, error) {
	row := q.db.QueryRow(ctx, getOrganizationRoleByID, arg.ID)
	var i OrganizationRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.IsSystemRole,
		&i.Permissions,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationRoleByName = `-- name: GetOrganizationRoleByName :one
SELECT id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at FROM organization_roles
WHERE ((organization_id = $1 AND name = $2) OR (organization_id IS NULL AND is_system_role = true AND name = $2))
AND active = true
LIMIT 1
`

type GetOrganizationRoleByNameParams struct {
	OrganizationID *string `json:"organizationId"`
	Name           string  `json:"name"`
}

func (q *Queries) GetOrganizationRoleByName(ctx context.Context, arg GetOrganizationRoleByNameParams) (OrganizationRole, error) {
	row := q.db.QueryRow(ctx, getOrganizationRoleByName, arg.OrganizationID, arg.Name)
	var i OrganizationRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.IsSystemRole,
		&i.Permissions,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoleAssignments = `-- name: GetUserRoleAssignments :many
SELECT uor.id, uor.user_id, uor.organization_id, uor.role_id, uor.assigned_by, uor.assigned_at, uor.active, org_roles.name as role_name, org_roles.description as role_description
FROM user_organization_roles uor
INNER JOIN organization_roles org_roles ON uor.role_id = org_roles.id
WHERE uor.user_id = $1 AND uor.organization_id = $2 AND uor.active = true
`

type GetUserRoleAssignmentsParams struct {
	UserID         string `json:"userId"`
	OrganizationID string `json:"organizationId"`
}

type GetUserRoleAssignmentsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          string             `json:"userId"`
	OrganizationID  string             `json:"organizationId"`
	RoleID          pgtype.UUID        `json:"roleId"`
	AssignedBy      *string            `json:"assignedBy"`
	AssignedAt      pgtype.Timestamptz `json:"assignedAt"`
	Active          *bool              `json:"active"`
	RoleName        string             `json:"roleName"`
	RoleDescription *string            `json:"roleDescription"`
}

func (q *Queries) GetUserRoleAssignments(ctx context.Context, arg GetUserRoleAssignmentsParams) ([]GetUserRoleAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, getUserRoleAssignments, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRoleAssignmentsRow{}
	for rows.Next() {
		var i GetUserRoleAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationID,
			&i.RoleID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.Active,
			&i.RoleName,
			&i.RoleDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT org_roles.id, org_roles.organization_id, org_roles.name, org_roles.description, org_roles.is_system_role, org_roles.permissions, org_roles.active, org_roles.created_by, org_roles.created_at, org_roles.updated_at FROM organization_roles org_roles
INNER JOIN user_organization_roles uor ON org_roles.id = uor.role_id
WHERE uor.user_id = $1 AND uor.organization_id = $2 AND uor.active = true AND org_roles.active = true
`

type GetUserRolesParams struct {
	UserID         string `json:"userId"`
	OrganizationID string `json:"organizationId"`
}

func (q *Queries) GetUserRoles(ctx context.Context, arg GetUserRolesParams) ([]OrganizationRole, error) {
	rows, err := q.db.Query(ctx, getUserRoles, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationRole{}
	for rows.Next() {
		var i OrganizationRole
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.IsSystemRole,
			&i.Permissions,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomRoles = `-- name: ListCustomRoles :many
SELECT id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at FROM organization_roles
WHERE organization_id = $1 AND is_system_role = false AND active = true
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListCustomRolesParams struct {
	OrganizationID *string `json:"organizationId"`
	Limit          int32   `json:"limit"`
	Offset         int32   `json:"offset"`
}

func (q *Queries) ListCustomRoles(ctx context.Context, arg ListCustomRolesParams) ([]OrganizationRole, error) {
	rows, err := q.db.Query(ctx, listCustomRoles, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationRole{}
	for rows.Next() {
		var i OrganizationRole
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.IsSystemRole,
			&i.Permissions,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationRoles = `-- name: ListOrganizationRoles :many
SELECT id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at FROM organization_roles
WHERE (
    (organization_id = $1 AND active = true)
    OR
    (organization_id IS NULL AND is_system_role = true AND active = true)
)
ORDER BY is_system_role DESC, name ASC
LIMIT $2 OFFSET $3
`

type ListOrganizationRolesParams struct {
	OrganizationID *string `json:"organizationId"`
	Limit          int32   `json:"limit"`
	Offset         int32   `json:"offset"`
}

func (q *Queries) ListOrganizationRoles(ctx context.Context, arg ListOrganizationRolesParams) ([]OrganizationRole, error) {
	rows, err := q.db.Query(ctx, listOrganizationRoles, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationRole{}
	for rows.Next() {
		var i OrganizationRole
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.IsSystemRole,
			&i.Permissions,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemRoles = `-- name: ListSystemRoles :many
SELECT id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at FROM organization_roles
WHERE organization_id IS NULL AND is_system_role = true AND active = true
ORDER BY name ASC
`

func (q *Queries) ListSystemRoles(ctx context.Context) ([]OrganizationRole, error) {
	rows, err := q.db.Query(ctx, listSystemRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationRole{}
	for rows.Next() {
		var i OrganizationRole
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.IsSystemRole,
			&i.Permissions,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRole = `-- name: ListUsersWithRole :many
SELECT u.id, u.email, u.name, u.password, u.role, u.active, u.last_login, u.current_organization_id, u.is_super_admin, u.preferences, u.deleted_at, u.position, u.man_number, u.nrc_number, u.contact, u.mfa_enabled, u.is_ldap_user, u.must_change_password, u.created_at, u.updated_at, uor.assigned_at FROM users u
INNER JOIN user_organization_roles uor ON u.id = uor.user_id
WHERE uor.organization_id = $1 AND uor.role_id = $2 AND uor.active = true
ORDER BY u.name
LIMIT $3 OFFSET $4
`

type ListUsersWithRoleParams struct {
	OrganizationID string      `json:"organizationId"`
	RoleID         pgtype.UUID `json:"roleId"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type ListUsersWithRoleRow struct {
	ID                    string             `json:"id"`
	Email                 string             `json:"email"`
	Name                  string             `json:"name"`
	Password              string             `json:"password"`
	Role                  string             `json:"role"`
	Active                bool               `json:"active"`
	LastLogin             pgtype.Timestamp   `json:"lastLogin"`
	CurrentOrganizationID *string            `json:"currentOrganizationId"`
	IsSuperAdmin          bool               `json:"isSuperAdmin"`
	Preferences           []byte             `json:"preferences"`
	DeletedAt             pgtype.Timestamp   `json:"deletedAt"`
	Position              *string            `json:"position"`
	ManNumber             *string            `json:"manNumber"`
	NrcNumber             *string            `json:"nrcNumber"`
	Contact               *string            `json:"contact"`
	MfaEnabled            bool               `json:"mfaEnabled"`
	IsLdapUser            bool               `json:"isLdapUser"`
	MustChangePassword    bool               `json:"mustChangePassword"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
	AssignedAt            pgtype.Timestamptz `json:"assignedAt"`
}

func (q *Queries) ListUsersWithRole(ctx context.Context, arg ListUsersWithRoleParams) ([]ListUsersWithRoleRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithRole,
		arg.OrganizationID,
		arg.RoleID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithRoleRow{}
	for rows.Next() {
		var i ListUsersWithRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Password,
			&i.Role,
			&i.Active,
			&i.LastLogin,
			&i.CurrentOrganizationID,
			&i.IsSuperAdmin,
			&i.Preferences,
			&i.DeletedAt,
			&i.Position,
			&i.ManNumber,
			&i.NrcNumber,
			&i.Contact,
			&i.MfaEnabled,
			&i.IsLdapUser,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllUserRoles = `-- name: RemoveAllUserRoles :exec
UPDATE user_organization_roles SET
    active = false
WHERE user_id = $1 AND organization_id = $2
`

type RemoveAllUserRolesParams struct {
	UserID         string `json:"userId"`
	OrganizationID string `json:"organizationId"`
}

func (q *Queries) RemoveAllUserRoles(ctx context.Context, arg RemoveAllUserRolesParams) error {
	_, err := q.db.Exec(ctx, removeAllUserRoles, arg.UserID, arg.OrganizationID)
	return err
}

const removeUserRole = `-- name: RemoveUserRole :exec
UPDATE user_organization_roles SET
    active = false
WHERE user_id = $1 AND organization_id = $2 AND role_id = $3
`

type RemoveUserRoleParams struct {
	UserID         string      `json:"userId"`
	OrganizationID string      `json:"organizationId"`
	RoleID         pgtype.UUID `json:"roleId"`
}

func (q *Queries) RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error {
	_, err := q.db.Exec(ctx, removeUserRole, arg.UserID, arg.OrganizationID, arg.RoleID)
	return err
}

const updateOrganizationRole = `-- name: UpdateOrganizationRole :one
UPDATE organization_roles SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    permissions = COALESCE($4, permissions),
    updated_at = NOW()
WHERE id = $1 AND is_system_role = false
RETURNING id, organization_id, name, description, is_system_role, permissions, active, created_by, created_at, updated_at
`

type UpdateOrganizationRoleParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	Permissions []byte      `json:"permissions"`
}

func (q *Queries) UpdateOrganizationRole(ctx context.Context, arg UpdateOrganizationRoleParams) (OrganizationRole, error) {
	row := q.db.QueryRow(ctx, updateOrganizationRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Permissions,
	)
	var i OrganizationRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.IsSystemRole,
		&i.Permissions,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
