// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_branches.sql

package db

import (
	"context"
)

const countBranches = `-- name: CountBranches :one
SELECT COUNT(*) FROM organization_branches
WHERE organization_id = $1
  AND ($2::bool IS NULL OR is_active = $2)
`

type CountBranchesParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        bool   `json:"column2"`
}

func (q *Queries) CountBranches(ctx context.Context, arg CountBranchesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBranches, arg.OrganizationID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranch = `-- name: CreateBranch :one

INSERT INTO organization_branches (
    id, organization_id, name, code, province_id, town_id, address, manager_id, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, organization_id, name, code, province_id, town_id, address, manager_id, is_active, created_at, updated_at
`

type CreateBranchParams struct {
	ID             string  `json:"id"`
	OrganizationID string  `json:"organizationId"`
	Name           string  `json:"name"`
	Code           *string `json:"code"`
	ProvinceID     *string `json:"provinceId"`
	TownID         *string `json:"townId"`
	Address        *string `json:"address"`
	ManagerID      *string `json:"managerId"`
	IsActive       bool    `json:"isActive"`
}

// Organization branches queries
// Branches associated with an organization (province_id/town_id/manager_id).
func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (OrganizationBranch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Code,
		arg.ProvinceID,
		arg.TownID,
		arg.Address,
		arg.ManagerID,
		arg.IsActive,
	)
	var i OrganizationBranch
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Code,
		&i.ProvinceID,
		&i.TownID,
		&i.Address,
		&i.ManagerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBranch = `-- name: DeleteBranch :exec
DELETE FROM organization_branches WHERE id = $1
`

type DeleteBranchParams struct {
	ID string `json:"id"`
}

func (q *Queries) DeleteBranch(ctx context.Context, arg DeleteBranchParams) error {
	_, err := q.db.Exec(ctx, deleteBranch, arg.ID)
	return err
}

const getBranchByCode = `-- name: GetBranchByCode :one
SELECT id, organization_id, name, code, province_id, town_id, address, manager_id, is_active, created_at, updated_at FROM organization_branches
WHERE organization_id = $1 AND code = $2
`

type GetBranchByCodeParams struct {
	OrganizationID string  `json:"organizationId"`
	Code           *string `json:"code"`
}

func (q *Queries) GetBranchByCode(ctx context.Context, arg GetBranchByCodeParams) (OrganizationBranch, error) {
	row := q.db.QueryRow(ctx, getBranchByCode, arg.OrganizationID, arg.Code)
	var i OrganizationBranch
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Code,
		&i.ProvinceID,
		&i.TownID,
		&i.Address,
		&i.ManagerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBranchByID = `-- name: GetBranchByID :one
SELECT id, organization_id, name, code, province_id, town_id, address, manager_id, is_active, created_at, updated_at FROM organization_branches WHERE id = $1
`

type GetBranchByIDParams struct {
	ID string `json:"id"`
}

func (q *Queries) GetBranchByID(ctx context.Context, arg GetBranchByIDParams) (OrganizationBranch, error) {
	row := q.db.QueryRow(ctx, getBranchByID, arg.ID)
	var i OrganizationBranch
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Code,
		&i.ProvinceID,
		&i.TownID,
		&i.Address,
		&i.ManagerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBranches = `-- name: ListActiveBranches :many
SELECT id, organization_id, name, code, province_id, town_id, address, manager_id, is_active, created_at, updated_at FROM organization_branches
WHERE organization_id = $1 AND is_active = true
ORDER BY name ASC
`

type ListActiveBranchesParams struct {
	OrganizationID string `json:"organizationId"`
}

func (q *Queries) ListActiveBranches(ctx context.Context, arg ListActiveBranchesParams) ([]OrganizationBranch, error) {
	rows, err := q.db.Query(ctx, listActiveBranches, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationBranch{}
	for rows.Next() {
		var i OrganizationBranch
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Code,
			&i.ProvinceID,
			&i.TownID,
			&i.Address,
			&i.ManagerID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranches = `-- name: ListBranches :many
SELECT id, organization_id, name, code, province_id, town_id, address, manager_id, is_active, created_at, updated_at FROM organization_branches
WHERE organization_id = $1
  AND ($2::bool IS NULL OR is_active = $2)
ORDER BY name ASC
LIMIT $3 OFFSET $4
`

type ListBranchesParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        bool   `json:"column2"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListBranches(ctx context.Context, arg ListBranchesParams) ([]OrganizationBranch, error) {
	rows, err := q.db.Query(ctx, listBranches,
		arg.OrganizationID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationBranch{}
	for rows.Next() {
		var i OrganizationBranch
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Code,
			&i.ProvinceID,
			&i.TownID,
			&i.Address,
			&i.ManagerID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE organization_branches SET
    name        = COALESCE($2, name),
    code        = COALESCE($3, code),
    province_id = COALESCE($4, province_id),
    town_id     = COALESCE($5, town_id),
    address     = COALESCE($6, address),
    manager_id  = COALESCE($7, manager_id),
    is_active   = COALESCE($8, is_active),
    updated_at  = NOW()
WHERE id = $1
RETURNING id, organization_id, name, code, province_id, town_id, address, manager_id, is_active, created_at, updated_at
`

type UpdateBranchParams struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Code       *string `json:"code"`
	ProvinceID *string `json:"provinceId"`
	TownID     *string `json:"townId"`
	Address    *string `json:"address"`
	ManagerID  *string `json:"managerId"`
	IsActive   bool    `json:"isActive"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (OrganizationBranch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.ProvinceID,
		arg.TownID,
		arg.Address,
		arg.ManagerID,
		arg.IsActive,
	)
	var i OrganizationBranch
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Code,
		&i.ProvinceID,
		&i.TownID,
		&i.Address,
		&i.ManagerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
