// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_settings.sql

package db

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const getOrganizationSettings = `-- name: GetOrganizationSettings :one

SELECT id, organization_id, require_digital_signatures, default_approval_chain, currency, fiscal_year_start, enable_budget_validation, budget_variance_threshold, created_at, updated_at, procurement_flow FROM organization_settings WHERE organization_id = $1
`

type GetOrganizationSettingsParams struct {
	OrganizationID string `json:"organizationId"`
}

// Organization settings queries
// One row per organization (organization_id is UNIQUE).
func (q *Queries) GetOrganizationSettings(ctx context.Context, arg GetOrganizationSettingsParams) (OrganizationSetting, error) {
	row := q.db.QueryRow(ctx, getOrganizationSettings, arg.OrganizationID)
	var i OrganizationSetting
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RequireDigitalSignatures,
		&i.DefaultApprovalChain,
		&i.Currency,
		&i.FiscalYearStart,
		&i.EnableBudgetValidation,
		&i.BudgetVarianceThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcurementFlow,
	)
	return i, err
}

const upsertOrganizationSettings = `-- name: UpsertOrganizationSettings :one
INSERT INTO organization_settings (
    id, organization_id,
    require_digital_signatures, default_approval_chain, currency,
    fiscal_year_start, enable_budget_validation, budget_variance_threshold,
    procurement_flow
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (organization_id) DO UPDATE SET
    require_digital_signatures = EXCLUDED.require_digital_signatures,
    default_approval_chain     = EXCLUDED.default_approval_chain,
    currency                   = EXCLUDED.currency,
    fiscal_year_start          = EXCLUDED.fiscal_year_start,
    enable_budget_validation   = EXCLUDED.enable_budget_validation,
    budget_variance_threshold  = EXCLUDED.budget_variance_threshold,
    procurement_flow           = EXCLUDED.procurement_flow,
    updated_at                 = NOW()
RETURNING id, organization_id, require_digital_signatures, default_approval_chain, currency, fiscal_year_start, enable_budget_validation, budget_variance_threshold, created_at, updated_at, procurement_flow
`

type UpsertOrganizationSettingsParams struct {
	ID                       string           `json:"id"`
	OrganizationID           string           `json:"organizationId"`
	RequireDigitalSignatures *bool            `json:"requireDigitalSignatures"`
	DefaultApprovalChain     *string          `json:"defaultApprovalChain"`
	Currency                 *string          `json:"currency"`
	FiscalYearStart          *int32           `json:"fiscalYearStart"`
	EnableBudgetValidation   *bool            `json:"enableBudgetValidation"`
	BudgetVarianceThreshold  *decimal.Decimal `json:"budgetVarianceThreshold"`
	ProcurementFlow          *string          `json:"procurementFlow"`
}

func (q *Queries) UpsertOrganizationSettings(ctx context.Context, arg UpsertOrganizationSettingsParams) (OrganizationSetting, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationSettings,
		arg.ID,
		arg.OrganizationID,
		arg.RequireDigitalSignatures,
		arg.DefaultApprovalChain,
		arg.Currency,
		arg.FiscalYearStart,
		arg.EnableBudgetValidation,
		arg.BudgetVarianceThreshold,
		arg.ProcurementFlow,
	)
	var i OrganizationSetting
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RequireDigitalSignatures,
		&i.DefaultApprovalChain,
		&i.Currency,
		&i.FiscalYearStart,
		&i.EnableBudgetValidation,
		&i.BudgetVarianceThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcurementFlow,
	)
	return i, err
}
