// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :one

INSERT INTO organization_members (
    id, organization_id, user_id, role, department, department_id, title,
    branch_id, active, invited_at, joined_at, invited_by, custom_permissions
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, organization_id, user_id, role, department, department_id, title, branch_id, active, invited_at, joined_at, invited_by, custom_permissions, created_at, updated_at
`

type AddMemberParams struct {
	ID                string             `json:"id"`
	OrganizationID    string             `json:"organizationId"`
	UserID            string             `json:"userId"`
	Role              string             `json:"role"`
	Department        *string            `json:"department"`
	DepartmentID      *string            `json:"departmentId"`
	Title             *string            `json:"title"`
	BranchID          *string            `json:"branchId"`
	Active            *bool              `json:"active"`
	InvitedAt         pgtype.Timestamptz `json:"invitedAt"`
	JoinedAt          pgtype.Timestamptz `json:"joinedAt"`
	InvitedBy         *string            `json:"invitedBy"`
	CustomPermissions []byte             `json:"customPermissions"`
}

// Organization members queries
// Composite uniqueness on (organization_id, user_id) — see uk_org_user.
func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, addMember,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
		arg.Department,
		arg.DepartmentID,
		arg.Title,
		arg.BranchID,
		arg.Active,
		arg.InvitedAt,
		arg.JoinedAt,
		arg.InvitedBy,
		arg.CustomPermissions,
	)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Department,
		&i.DepartmentID,
		&i.Title,
		&i.BranchID,
		&i.Active,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.InvitedBy,
		&i.CustomPermissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countMembers = `-- name: CountMembers :one
SELECT COUNT(*) FROM organization_members
WHERE organization_id = $1
  AND ($2::bool IS NULL OR active = $2)
`

type CountMembersParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        bool   `json:"column2"`
}

func (q *Queries) CountMembers(ctx context.Context, arg CountMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, arg.OrganizationID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMember = `-- name: GetMember :one
SELECT id, organization_id, user_id, role, department, department_id, title, branch_id, active, invited_at, joined_at, invited_by, custom_permissions, created_at, updated_at FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	OrganizationID string `json:"organizationId"`
	UserID         string `json:"userId"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Department,
		&i.DepartmentID,
		&i.Title,
		&i.BranchID,
		&i.Active,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.InvitedBy,
		&i.CustomPermissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, organization_id, user_id, role, department, department_id, title, branch_id, active, invited_at, joined_at, invited_by, custom_permissions, created_at, updated_at FROM organization_members WHERE id = $1
`

type GetMemberByIDParams struct {
	ID string `json:"id"`
}

func (q *Queries) GetMemberByID(ctx context.Context, arg GetMemberByIDParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getMemberByID, arg.ID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Department,
		&i.DepartmentID,
		&i.Title,
		&i.BranchID,
		&i.Active,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.InvitedBy,
		&i.CustomPermissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, organization_id, user_id, role, department, department_id, title, branch_id, active, invited_at, joined_at, invited_by, custom_permissions, created_at, updated_at FROM organization_members
WHERE organization_id = $1
  AND ($2::bool IS NULL OR active = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListMembersParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        bool   `json:"column2"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]OrganizationMember, error) {
	rows, err := q.db.Query(ctx, listMembers,
		arg.OrganizationID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationMember{}
	for rows.Next() {
		var i OrganizationMember
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.Department,
			&i.DepartmentID,
			&i.Title,
			&i.BranchID,
			&i.Active,
			&i.InvitedAt,
			&i.JoinedAt,
			&i.InvitedBy,
			&i.CustomPermissions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT om.id, om.organization_id, om.user_id, om.role, om.department, om.department_id, om.title, om.branch_id, om.active, om.invited_at, om.joined_at, om.invited_by, om.custom_permissions, om.created_at, om.updated_at FROM organization_members om
WHERE om.user_id = $1 AND om.active = true
ORDER BY om.created_at DESC
`

type ListOrganizationsForUserParams struct {
	UserID string `json:"userId"`
}

func (q *Queries) ListOrganizationsForUser(ctx context.Context, arg ListOrganizationsForUserParams) ([]OrganizationMember, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForUser, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationMember{}
	for rows.Next() {
		var i OrganizationMember
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.Department,
			&i.DepartmentID,
			&i.Title,
			&i.BranchID,
			&i.Active,
			&i.InvitedAt,
			&i.JoinedAt,
			&i.InvitedBy,
			&i.CustomPermissions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM organization_members WHERE id = $1
`

type RemoveMemberParams struct {
	ID string `json:"id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.ID)
	return err
}

const removeMemberByUserOrg = `-- name: RemoveMemberByUserOrg :exec
DELETE FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type RemoveMemberByUserOrgParams struct {
	OrganizationID string `json:"organizationId"`
	UserID         string `json:"userId"`
}

func (q *Queries) RemoveMemberByUserOrg(ctx context.Context, arg RemoveMemberByUserOrgParams) error {
	_, err := q.db.Exec(ctx, removeMemberByUserOrg, arg.OrganizationID, arg.UserID)
	return err
}

const updateMember = `-- name: UpdateMember :one
UPDATE organization_members SET
    role               = COALESCE($2, role),
    department         = COALESCE($3, department),
    department_id      = COALESCE($4, department_id),
    title              = COALESCE($5, title),
    branch_id          = COALESCE($6, branch_id),
    active             = COALESCE($7, active),
    custom_permissions = COALESCE($8, custom_permissions),
    updated_at         = NOW()
WHERE id = $1
RETURNING id, organization_id, user_id, role, department, department_id, title, branch_id, active, invited_at, joined_at, invited_by, custom_permissions, created_at, updated_at
`

type UpdateMemberParams struct {
	ID                string  `json:"id"`
	Role              string  `json:"role"`
	Department        *string `json:"department"`
	DepartmentID      *string `json:"departmentId"`
	Title             *string `json:"title"`
	BranchID          *string `json:"branchId"`
	Active            *bool   `json:"active"`
	CustomPermissions []byte  `json:"customPermissions"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.Role,
		arg.Department,
		arg.DepartmentID,
		arg.Title,
		arg.BranchID,
		arg.Active,
		arg.CustomPermissions,
	)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Department,
		&i.DepartmentID,
		&i.Title,
		&i.BranchID,
		&i.Active,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.InvitedBy,
		&i.CustomPermissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :one
UPDATE organization_members
SET active = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, user_id, role, department, department_id, title, branch_id, active, invited_at, joined_at, invited_by, custom_permissions, created_at, updated_at
`

type UpdateMemberStatusParams struct {
	ID     string `json:"id"`
	Active *bool  `json:"active"`
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateMemberStatus, arg.ID, arg.Active)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Department,
		&i.DepartmentID,
		&i.Title,
		&i.BranchID,
		&i.Active,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.InvitedBy,
		&i.CustomPermissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
