// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_vouchers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

const countPaymentVouchers = `-- name: CountPaymentVouchers :one
SELECT COUNT(*) FROM payment_vouchers
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::text       = '' OR UPPER(status) = UPPER($2))
  AND ($3::text       = '' OR vendor_id     = $3)
  AND ($4::text       = '' OR department    = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
  AND ($7::text       = '' OR (title ILIKE '%' || $7 || '%' OR description ILIKE '%' || $7 || '%' OR document_number ILIKE '%' || $7 || '%'))
`

type CountPaymentVouchersParams struct {
	OrganizationID string             `json:"organizationId"`
	Column2        string             `json:"column2"`
	Column3        string             `json:"column3"`
	Column4        string             `json:"column4"`
	Column5        pgtype.Timestamptz `json:"column5"`
	Column6        pgtype.Timestamptz `json:"column6"`
	Column7        string             `json:"column7"`
}

func (q *Queries) CountPaymentVouchers(ctx context.Context, arg CountPaymentVouchersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentVouchers,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentVouchersAll = `-- name: CountPaymentVouchersAll :one
SELECT COUNT(*) FROM payment_vouchers
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status) = UPPER($2))
  AND ($3::text = '' OR vendor_id     = $3)
`

type CountPaymentVouchersAllParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
}

func (q *Queries) CountPaymentVouchersAll(ctx context.Context, arg CountPaymentVouchersAllParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentVouchersAll, arg.OrganizationID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentVouchersByVendor = `-- name: CountPaymentVouchersByVendor :one
SELECT COUNT(*) FROM payment_vouchers
WHERE organization_id = $1
  AND vendor_id       = $2
  AND deleted_at IS NULL
`

type CountPaymentVouchersByVendorParams struct {
	OrganizationID string  `json:"organizationId"`
	VendorID       *string `json:"vendorId"`
}

func (q *Queries) CountPaymentVouchersByVendor(ctx context.Context, arg CountPaymentVouchersByVendorParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentVouchersByVendor, arg.OrganizationID, arg.VendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentVouchersLimited = `-- name: CountPaymentVouchersLimited :one
SELECT COUNT(*) FROM payment_vouchers pv
WHERE pv.organization_id = $1
  AND ($2::text = '' OR UPPER(pv.status) = UPPER($2))
  AND ($3::text = '' OR pv.vendor_id     = $3)
  AND (
      pv.created_by = $4
      OR pv.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'payment_voucher'
            AND (
                wt.assigned_user_id        = $4
                OR LOWER(wt.assigned_role) = LOWER($5)
                OR wt.assigned_role        = ANY($6::text[])
                OR wt.claimed_by           = $4
            )
      )
  )
`

type CountPaymentVouchersLimitedParams struct {
	OrganizationID string   `json:"organizationId"`
	Column2        string   `json:"column2"`
	Column3        string   `json:"column3"`
	CreatedBy      *string  `json:"createdBy"`
	Lower          string   `json:"lower"`
	Column6        []string `json:"column6"`
}

func (q *Queries) CountPaymentVouchersLimited(ctx context.Context, arg CountPaymentVouchersLimitedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentVouchersLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.CreatedBy,
		arg.Lower,
		arg.Column6,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentVouchersProcurement = `-- name: CountPaymentVouchersProcurement :one
SELECT COUNT(*) FROM payment_vouchers pv
WHERE pv.organization_id = $1
  AND pv.linked_po IS NOT NULL
  AND pv.linked_po != ''
  AND ($2::text = '' OR UPPER(pv.status) = UPPER($2))
  AND ($3::text = '' OR pv.vendor_id     = $3)
`

type CountPaymentVouchersProcurementParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
}

func (q *Queries) CountPaymentVouchersProcurement(ctx context.Context, arg CountPaymentVouchersProcurementParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentVouchersProcurement, arg.OrganizationID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaymentVoucher = `-- name: CreatePaymentVoucher :one
INSERT INTO payment_vouchers (
    id, organization_id, document_number, vendor_id, invoice_number, status,
    amount, currency, payment_method, gl_code, description, approval_stage,
    linked_po, linked_grn, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, organization_id, document_number, vendor_id, invoice_number, status, amount, currency, payment_method, gl_code, description, approval_stage, approval_history, linked_po, title, department, department_id, priority, requested_by_name, requested_date, submitted_at, approved_at, paid_date, payment_due_date, budget_code, cost_center, project_code, tax_amount, withholding_tax_amount, paid_amount, source_purchase_order_number, source_requisition_number, bank_details, items, created_by, owner_id, action_history, metadata, deleted_at, created_at, updated_at, linked_grn
`

type CreatePaymentVoucherParams struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organizationId"`
	DocumentNumber string           `json:"documentNumber"`
	VendorID       *string          `json:"vendorId"`
	InvoiceNumber  *string          `json:"invoiceNumber"`
	Status         *string          `json:"status"`
	Amount         *decimal.Decimal `json:"amount"`
	Currency       *string          `json:"currency"`
	PaymentMethod  *string          `json:"paymentMethod"`
	GlCode         *string          `json:"glCode"`
	Description    *string          `json:"description"`
	ApprovalStage  *int32           `json:"approvalStage"`
	LinkedPo       *string          `json:"linkedPo"`
	LinkedGrn      *string          `json:"linkedGrn"`
	CreatedBy      *string          `json:"createdBy"`
}

func (q *Queries) CreatePaymentVoucher(ctx context.Context, arg CreatePaymentVoucherParams) (PaymentVoucher, error) {
	row := q.db.QueryRow(ctx, createPaymentVoucher,
		arg.ID,
		arg.OrganizationID,
		arg.DocumentNumber,
		arg.VendorID,
		arg.InvoiceNumber,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethod,
		arg.GlCode,
		arg.Description,
		arg.ApprovalStage,
		arg.LinkedPo,
		arg.LinkedGrn,
		arg.CreatedBy,
	)
	var i PaymentVoucher
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.GlCode,
		&i.Description,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedPo,
		&i.Title,
		&i.Department,
		&i.DepartmentID,
		&i.Priority,
		&i.RequestedByName,
		&i.RequestedDate,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.PaidDate,
		&i.PaymentDueDate,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.TaxAmount,
		&i.WithholdingTaxAmount,
		&i.PaidAmount,
		&i.SourcePurchaseOrderNumber,
		&i.SourceRequisitionNumber,
		&i.BankDetails,
		&i.Items,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedGrn,
	)
	return i, err
}

const getPaymentVoucherByID = `-- name: GetPaymentVoucherByID :one

SELECT id, organization_id, document_number, vendor_id, invoice_number, status, amount, currency, payment_method, gl_code, description, approval_stage, approval_history, linked_po, title, department, department_id, priority, requested_by_name, requested_date, submitted_at, approved_at, paid_date, payment_due_date, budget_code, cost_center, project_code, tax_amount, withholding_tax_amount, paid_amount, source_purchase_order_number, source_requisition_number, bank_details, items, created_by, owner_id, action_history, metadata, deleted_at, created_at, updated_at, linked_grn FROM payment_vouchers WHERE id = $1 AND deleted_at IS NULL
`

type GetPaymentVoucherByIDParams struct {
	ID string `json:"id"`
}

// Payment voucher read queries.
// Three scope variants:
//
//	All         → scope.CanViewAll
//	Procurement → scope.IsProcurement (linked_po != '' filter)
//	Limited     → default (owner + workflow_tasks involvement filter)
func (q *Queries) GetPaymentVoucherByID(ctx context.Context, arg GetPaymentVoucherByIDParams) (PaymentVoucher, error) {
	row := q.db.QueryRow(ctx, getPaymentVoucherByID, arg.ID)
	var i PaymentVoucher
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.GlCode,
		&i.Description,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedPo,
		&i.Title,
		&i.Department,
		&i.DepartmentID,
		&i.Priority,
		&i.RequestedByName,
		&i.RequestedDate,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.PaidDate,
		&i.PaymentDueDate,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.TaxAmount,
		&i.WithholdingTaxAmount,
		&i.PaidAmount,
		&i.SourcePurchaseOrderNumber,
		&i.SourceRequisitionNumber,
		&i.BankDetails,
		&i.Items,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedGrn,
	)
	return i, err
}

const getPaymentVoucherByNumber = `-- name: GetPaymentVoucherByNumber :one
SELECT id, organization_id, document_number, vendor_id, invoice_number, status, amount, currency, payment_method, gl_code, description, approval_stage, approval_history, linked_po, title, department, department_id, priority, requested_by_name, requested_date, submitted_at, approved_at, paid_date, payment_due_date, budget_code, cost_center, project_code, tax_amount, withholding_tax_amount, paid_amount, source_purchase_order_number, source_requisition_number, bank_details, items, created_by, owner_id, action_history, metadata, deleted_at, created_at, updated_at, linked_grn FROM payment_vouchers WHERE organization_id = $1 AND document_number = $2 AND deleted_at IS NULL
`

type GetPaymentVoucherByNumberParams struct {
	OrganizationID string `json:"organizationId"`
	DocumentNumber string `json:"documentNumber"`
}

func (q *Queries) GetPaymentVoucherByNumber(ctx context.Context, arg GetPaymentVoucherByNumberParams) (PaymentVoucher, error) {
	row := q.db.QueryRow(ctx, getPaymentVoucherByNumber, arg.OrganizationID, arg.DocumentNumber)
	var i PaymentVoucher
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.GlCode,
		&i.Description,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedPo,
		&i.Title,
		&i.Department,
		&i.DepartmentID,
		&i.Priority,
		&i.RequestedByName,
		&i.RequestedDate,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.PaidDate,
		&i.PaymentDueDate,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.TaxAmount,
		&i.WithholdingTaxAmount,
		&i.PaidAmount,
		&i.SourcePurchaseOrderNumber,
		&i.SourceRequisitionNumber,
		&i.BankDetails,
		&i.Items,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedGrn,
	)
	return i, err
}

const linkGRNToPaymentVoucher = `-- name: LinkGRNToPaymentVoucher :exec
UPDATE payment_vouchers SET linked_grn = $2, updated_at = NOW() WHERE id = $1
`

type LinkGRNToPaymentVoucherParams struct {
	ID        string  `json:"id"`
	LinkedGrn *string `json:"linkedGrn"`
}

func (q *Queries) LinkGRNToPaymentVoucher(ctx context.Context, arg LinkGRNToPaymentVoucherParams) error {
	_, err := q.db.Exec(ctx, linkGRNToPaymentVoucher, arg.ID, arg.LinkedGrn)
	return err
}

const linkPOToPaymentVoucher = `-- name: LinkPOToPaymentVoucher :exec
UPDATE payment_vouchers SET linked_po = $2, updated_at = NOW() WHERE id = $1
`

type LinkPOToPaymentVoucherParams struct {
	ID       string  `json:"id"`
	LinkedPo *string `json:"linkedPo"`
}

func (q *Queries) LinkPOToPaymentVoucher(ctx context.Context, arg LinkPOToPaymentVoucherParams) error {
	_, err := q.db.Exec(ctx, linkPOToPaymentVoucher, arg.ID, arg.LinkedPo)
	return err
}

const listPaymentVoucherIDsAll = `-- name: ListPaymentVoucherIDsAll :many
SELECT id FROM payment_vouchers
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status) = UPPER($2))
  AND ($3::text = '' OR vendor_id     = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListPaymentVoucherIDsAllParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListPaymentVoucherIDsAll(ctx context.Context, arg ListPaymentVoucherIDsAllParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPaymentVoucherIDsAll,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentVoucherIDsLimited = `-- name: ListPaymentVoucherIDsLimited :many
SELECT pv.id FROM payment_vouchers pv
WHERE pv.organization_id = $1
  AND ($2::text = '' OR UPPER(pv.status) = UPPER($2))
  AND ($3::text = '' OR pv.vendor_id     = $3)
  AND (
      pv.created_by = $4
      OR pv.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'payment_voucher'
            AND (
                wt.assigned_user_id        = $4
                OR LOWER(wt.assigned_role) = LOWER($5)
                OR wt.assigned_role        = ANY($6::text[])
                OR wt.claimed_by           = $4
            )
      )
  )
ORDER BY pv.created_at DESC
LIMIT $7 OFFSET $8
`

type ListPaymentVoucherIDsLimitedParams struct {
	OrganizationID string   `json:"organizationId"`
	Column2        string   `json:"column2"`
	Column3        string   `json:"column3"`
	CreatedBy      *string  `json:"createdBy"`
	Lower          string   `json:"lower"`
	Column6        []string `json:"column6"`
	Limit          int32    `json:"limit"`
	Offset         int32    `json:"offset"`
}

func (q *Queries) ListPaymentVoucherIDsLimited(ctx context.Context, arg ListPaymentVoucherIDsLimitedParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPaymentVoucherIDsLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.CreatedBy,
		arg.Lower,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentVoucherIDsProcurement = `-- name: ListPaymentVoucherIDsProcurement :many
SELECT pv.id FROM payment_vouchers pv
WHERE pv.organization_id = $1
  AND pv.linked_po IS NOT NULL
  AND pv.linked_po != ''
  AND ($2::text = '' OR UPPER(pv.status) = UPPER($2))
  AND ($3::text = '' OR pv.vendor_id     = $3)
ORDER BY pv.created_at DESC
LIMIT $4 OFFSET $5
`

type ListPaymentVoucherIDsProcurementParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListPaymentVoucherIDsProcurement(ctx context.Context, arg ListPaymentVoucherIDsProcurementParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPaymentVoucherIDsProcurement,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentVouchers = `-- name: ListPaymentVouchers :many
SELECT id, organization_id, document_number, vendor_id, invoice_number, status, amount, currency, payment_method, gl_code, description, approval_stage, approval_history, linked_po, title, department, department_id, priority, requested_by_name, requested_date, submitted_at, approved_at, paid_date, payment_due_date, budget_code, cost_center, project_code, tax_amount, withholding_tax_amount, paid_amount, source_purchase_order_number, source_requisition_number, bank_details, items, created_by, owner_id, action_history, metadata, deleted_at, created_at, updated_at, linked_grn FROM payment_vouchers
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::text       = '' OR UPPER(status) = UPPER($2))
  AND ($3::text       = '' OR vendor_id     = $3)
  AND ($4::text       = '' OR department    = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
  AND ($7::text       = '' OR (title ILIKE '%' || $7 || '%' OR description ILIKE '%' || $7 || '%' OR document_number ILIKE '%' || $7 || '%'))
ORDER BY created_at DESC
LIMIT $8 OFFSET $9
`

type ListPaymentVouchersParams struct {
	OrganizationID string             `json:"organizationId"`
	Column2        string             `json:"column2"`
	Column3        string             `json:"column3"`
	Column4        string             `json:"column4"`
	Column5        pgtype.Timestamptz `json:"column5"`
	Column6        pgtype.Timestamptz `json:"column6"`
	Column7        string             `json:"column7"`
	Limit          int32              `json:"limit"`
	Offset         int32              `json:"offset"`
}

func (q *Queries) ListPaymentVouchers(ctx context.Context, arg ListPaymentVouchersParams) ([]PaymentVoucher, error) {
	rows, err := q.db.Query(ctx, listPaymentVouchers,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentVoucher{}
	for rows.Next() {
		var i PaymentVoucher
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentNumber,
			&i.VendorID,
			&i.InvoiceNumber,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.PaymentMethod,
			&i.GlCode,
			&i.Description,
			&i.ApprovalStage,
			&i.ApprovalHistory,
			&i.LinkedPo,
			&i.Title,
			&i.Department,
			&i.DepartmentID,
			&i.Priority,
			&i.RequestedByName,
			&i.RequestedDate,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.PaidDate,
			&i.PaymentDueDate,
			&i.BudgetCode,
			&i.CostCenter,
			&i.ProjectCode,
			&i.TaxAmount,
			&i.WithholdingTaxAmount,
			&i.PaidAmount,
			&i.SourcePurchaseOrderNumber,
			&i.SourceRequisitionNumber,
			&i.BankDetails,
			&i.Items,
			&i.CreatedBy,
			&i.OwnerID,
			&i.ActionHistory,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LinkedGrn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentVouchersByVendor = `-- name: ListPaymentVouchersByVendor :many
SELECT id, organization_id, document_number, vendor_id, invoice_number, status, amount, currency, payment_method, gl_code, description, approval_stage, approval_history, linked_po, title, department, department_id, priority, requested_by_name, requested_date, submitted_at, approved_at, paid_date, payment_due_date, budget_code, cost_center, project_code, tax_amount, withholding_tax_amount, paid_amount, source_purchase_order_number, source_requisition_number, bank_details, items, created_by, owner_id, action_history, metadata, deleted_at, created_at, updated_at, linked_grn FROM payment_vouchers
WHERE organization_id = $1
  AND vendor_id       = $2
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListPaymentVouchersByVendorParams struct {
	OrganizationID string  `json:"organizationId"`
	VendorID       *string `json:"vendorId"`
	Limit          int32   `json:"limit"`
	Offset         int32   `json:"offset"`
}

func (q *Queries) ListPaymentVouchersByVendor(ctx context.Context, arg ListPaymentVouchersByVendorParams) ([]PaymentVoucher, error) {
	rows, err := q.db.Query(ctx, listPaymentVouchersByVendor,
		arg.OrganizationID,
		arg.VendorID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentVoucher{}
	for rows.Next() {
		var i PaymentVoucher
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentNumber,
			&i.VendorID,
			&i.InvoiceNumber,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.PaymentMethod,
			&i.GlCode,
			&i.Description,
			&i.ApprovalStage,
			&i.ApprovalHistory,
			&i.LinkedPo,
			&i.Title,
			&i.Department,
			&i.DepartmentID,
			&i.Priority,
			&i.RequestedByName,
			&i.RequestedDate,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.PaidDate,
			&i.PaymentDueDate,
			&i.BudgetCode,
			&i.CostCenter,
			&i.ProjectCode,
			&i.TaxAmount,
			&i.WithholdingTaxAmount,
			&i.PaidAmount,
			&i.SourcePurchaseOrderNumber,
			&i.SourceRequisitionNumber,
			&i.BankDetails,
			&i.Items,
			&i.CreatedBy,
			&i.OwnerID,
			&i.ActionHistory,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LinkedGrn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePV = `-- name: SoftDeletePV :exec
UPDATE payment_vouchers SET deleted_at = NOW() WHERE id = $1
`

type SoftDeletePVParams struct {
	ID string `json:"id"`
}

func (q *Queries) SoftDeletePV(ctx context.Context, arg SoftDeletePVParams) error {
	_, err := q.db.Exec(ctx, softDeletePV, arg.ID)
	return err
}

const softDeletePaymentVoucher = `-- name: SoftDeletePaymentVoucher :exec
UPDATE payment_vouchers SET deleted_at = NOW() WHERE id = $1
`

type SoftDeletePaymentVoucherParams struct {
	ID string `json:"id"`
}

func (q *Queries) SoftDeletePaymentVoucher(ctx context.Context, arg SoftDeletePaymentVoucherParams) error {
	_, err := q.db.Exec(ctx, softDeletePaymentVoucher, arg.ID)
	return err
}

const updatePVLinkedGRN = `-- name: UpdatePVLinkedGRN :exec
UPDATE payment_vouchers
SET linked_grn = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdatePVLinkedGRNParams struct {
	ID        string  `json:"id"`
	LinkedGrn *string `json:"linkedGrn"`
}

func (q *Queries) UpdatePVLinkedGRN(ctx context.Context, arg UpdatePVLinkedGRNParams) error {
	_, err := q.db.Exec(ctx, updatePVLinkedGRN, arg.ID, arg.LinkedGrn)
	return err
}

const updatePVLinkedPO = `-- name: UpdatePVLinkedPO :exec
UPDATE payment_vouchers
SET linked_po                    = $2,
    source_purchase_order_number = COALESCE($3, source_purchase_order_number),
    updated_at                   = NOW()
WHERE id = $1
`

type UpdatePVLinkedPOParams struct {
	ID                        string  `json:"id"`
	LinkedPo                  *string `json:"linkedPo"`
	SourcePurchaseOrderNumber *string `json:"sourcePurchaseOrderNumber"`
}

func (q *Queries) UpdatePVLinkedPO(ctx context.Context, arg UpdatePVLinkedPOParams) error {
	_, err := q.db.Exec(ctx, updatePVLinkedPO, arg.ID, arg.LinkedPo, arg.SourcePurchaseOrderNumber)
	return err
}

const updatePVStatus = `-- name: UpdatePVStatus :one
UPDATE payment_vouchers
SET status         = $2,
    approval_stage = COALESCE($3, approval_stage),
    updated_at     = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, document_number, vendor_id, invoice_number, status, amount, currency, payment_method, gl_code, description, approval_stage, approval_history, linked_po, title, department, department_id, priority, requested_by_name, requested_date, submitted_at, approved_at, paid_date, payment_due_date, budget_code, cost_center, project_code, tax_amount, withholding_tax_amount, paid_amount, source_purchase_order_number, source_requisition_number, bank_details, items, created_by, owner_id, action_history, metadata, deleted_at, created_at, updated_at, linked_grn
`

type UpdatePVStatusParams struct {
	ID            string  `json:"id"`
	Status        *string `json:"status"`
	ApprovalStage *int32  `json:"approvalStage"`
}

func (q *Queries) UpdatePVStatus(ctx context.Context, arg UpdatePVStatusParams) (PaymentVoucher, error) {
	row := q.db.QueryRow(ctx, updatePVStatus, arg.ID, arg.Status, arg.ApprovalStage)
	var i PaymentVoucher
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.GlCode,
		&i.Description,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedPo,
		&i.Title,
		&i.Department,
		&i.DepartmentID,
		&i.Priority,
		&i.RequestedByName,
		&i.RequestedDate,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.PaidDate,
		&i.PaymentDueDate,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.TaxAmount,
		&i.WithholdingTaxAmount,
		&i.PaidAmount,
		&i.SourcePurchaseOrderNumber,
		&i.SourceRequisitionNumber,
		&i.BankDetails,
		&i.Items,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedGrn,
	)
	return i, err
}

const updatePaymentVoucher = `-- name: UpdatePaymentVoucher :one
UPDATE payment_vouchers SET 
    vendor_id = COALESCE($2, vendor_id),
    invoice_number = COALESCE($3, invoice_number),
    status = COALESCE($4, status),
    amount = COALESCE($5, amount),
    payment_method = COALESCE($6, payment_method),
    gl_code = COALESCE($7, gl_code),
    description = COALESCE($8, description),
    approval_stage = COALESCE($9, approval_stage),
    linked_po = COALESCE($10, linked_po),
    linked_grn = COALESCE($11, linked_grn),
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, document_number, vendor_id, invoice_number, status, amount, currency, payment_method, gl_code, description, approval_stage, approval_history, linked_po, title, department, department_id, priority, requested_by_name, requested_date, submitted_at, approved_at, paid_date, payment_due_date, budget_code, cost_center, project_code, tax_amount, withholding_tax_amount, paid_amount, source_purchase_order_number, source_requisition_number, bank_details, items, created_by, owner_id, action_history, metadata, deleted_at, created_at, updated_at, linked_grn
`

type UpdatePaymentVoucherParams struct {
	ID            string           `json:"id"`
	VendorID      *string          `json:"vendorId"`
	InvoiceNumber *string          `json:"invoiceNumber"`
	Status        *string          `json:"status"`
	Amount        *decimal.Decimal `json:"amount"`
	PaymentMethod *string          `json:"paymentMethod"`
	GlCode        *string          `json:"glCode"`
	Description   *string          `json:"description"`
	ApprovalStage *int32           `json:"approvalStage"`
	LinkedPo      *string          `json:"linkedPo"`
	LinkedGrn     *string          `json:"linkedGrn"`
}

func (q *Queries) UpdatePaymentVoucher(ctx context.Context, arg UpdatePaymentVoucherParams) (PaymentVoucher, error) {
	row := q.db.QueryRow(ctx, updatePaymentVoucher,
		arg.ID,
		arg.VendorID,
		arg.InvoiceNumber,
		arg.Status,
		arg.Amount,
		arg.PaymentMethod,
		arg.GlCode,
		arg.Description,
		arg.ApprovalStage,
		arg.LinkedPo,
		arg.LinkedGrn,
	)
	var i PaymentVoucher
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.GlCode,
		&i.Description,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedPo,
		&i.Title,
		&i.Department,
		&i.DepartmentID,
		&i.Priority,
		&i.RequestedByName,
		&i.RequestedDate,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.PaidDate,
		&i.PaymentDueDate,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.TaxAmount,
		&i.WithholdingTaxAmount,
		&i.PaidAmount,
		&i.SourcePurchaseOrderNumber,
		&i.SourceRequisitionNumber,
		&i.BankDetails,
		&i.Items,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedGrn,
	)
	return i, err
}
