// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provinces_towns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProvinceByCode = `-- name: GetProvinceByCode :one
SELECT id, name, code FROM provinces WHERE code = $1
`

type GetProvinceByCodeParams struct {
	Code string `json:"code"`
}

func (q *Queries) GetProvinceByCode(ctx context.Context, arg GetProvinceByCodeParams) (Province, error) {
	row := q.db.QueryRow(ctx, getProvinceByCode, arg.Code)
	var i Province
	err := row.Scan(&i.ID, &i.Name, &i.Code)
	return i, err
}

const getProvinceByID = `-- name: GetProvinceByID :one
SELECT id, name, code FROM provinces WHERE id = $1
`

type GetProvinceByIDParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) GetProvinceByID(ctx context.Context, arg GetProvinceByIDParams) (Province, error) {
	row := q.db.QueryRow(ctx, getProvinceByID, arg.ID)
	var i Province
	err := row.Scan(&i.ID, &i.Name, &i.Code)
	return i, err
}

const getTownByID = `-- name: GetTownByID :one
SELECT id, province_id, name, code FROM towns WHERE id = $1
`

type GetTownByIDParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) GetTownByID(ctx context.Context, arg GetTownByIDParams) (Town, error) {
	row := q.db.QueryRow(ctx, getTownByID, arg.ID)
	var i Town
	err := row.Scan(
		&i.ID,
		&i.ProvinceID,
		&i.Name,
		&i.Code,
	)
	return i, err
}

const listProvinces = `-- name: ListProvinces :many

SELECT id, name, code FROM provinces ORDER BY name ASC
`

// Provinces and towns queries
// Reference (lookup) tables; read-only for application code.
func (q *Queries) ListProvinces(ctx context.Context) ([]Province, error) {
	rows, err := q.db.Query(ctx, listProvinces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Province{}
	for rows.Next() {
		var i Province
		if err := rows.Scan(&i.ID, &i.Name, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTowns = `-- name: ListTowns :many
SELECT id, province_id, name, code FROM towns ORDER BY name ASC
`

func (q *Queries) ListTowns(ctx context.Context) ([]Town, error) {
	rows, err := q.db.Query(ctx, listTowns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Town{}
	for rows.Next() {
		var i Town
		if err := rows.Scan(
			&i.ID,
			&i.ProvinceID,
			&i.Name,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTownsByProvince = `-- name: ListTownsByProvince :many
SELECT id, province_id, name, code FROM towns WHERE province_id = $1 ORDER BY name ASC
`

type ListTownsByProvinceParams struct {
	ProvinceID pgtype.UUID `json:"provinceId"`
}

func (q *Queries) ListTownsByProvince(ctx context.Context, arg ListTownsByProvinceParams) ([]Town, error) {
	rows, err := q.db.Query(ctx, listTownsByProvince, arg.ProvinceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Town{}
	for rows.Next() {
		var i Town
		if err := rows.Scan(
			&i.ID,
			&i.ProvinceID,
			&i.Name,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
