// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchase_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

const countPurchaseOrders = `-- name: CountPurchaseOrders :one
SELECT COUNT(*) FROM purchase_orders
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::text       = '' OR UPPER(status) = UPPER($2))
  AND ($3::text       = '' OR vendor_id     = $3)
  AND ($4::text       = '' OR department    = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
  AND ($7::text       = '' OR (title ILIKE '%' || $7 || '%' OR description ILIKE '%' || $7 || '%' OR document_number ILIKE '%' || $7 || '%'))
`

type CountPurchaseOrdersParams struct {
	OrganizationID string             `json:"organizationId"`
	Column2        string             `json:"column2"`
	Column3        string             `json:"column3"`
	Column4        string             `json:"column4"`
	Column5        pgtype.Timestamptz `json:"column5"`
	Column6        pgtype.Timestamptz `json:"column6"`
	Column7        string             `json:"column7"`
}

func (q *Queries) CountPurchaseOrders(ctx context.Context, arg CountPurchaseOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchaseOrders,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPurchaseOrdersAll = `-- name: CountPurchaseOrdersAll :one
SELECT COUNT(*) FROM purchase_orders
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status)    = UPPER($2))
  AND ($3::text = '' OR vendor_id        = $3)
`

type CountPurchaseOrdersAllParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
}

func (q *Queries) CountPurchaseOrdersAll(ctx context.Context, arg CountPurchaseOrdersAllParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchaseOrdersAll, arg.OrganizationID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPurchaseOrdersByVendor = `-- name: CountPurchaseOrdersByVendor :one
SELECT COUNT(*) FROM purchase_orders
WHERE organization_id = $1
  AND vendor_id       = $2
  AND deleted_at IS NULL
`

type CountPurchaseOrdersByVendorParams struct {
	OrganizationID string  `json:"organizationId"`
	VendorID       *string `json:"vendorId"`
}

func (q *Queries) CountPurchaseOrdersByVendor(ctx context.Context, arg CountPurchaseOrdersByVendorParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchaseOrdersByVendor, arg.OrganizationID, arg.VendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPurchaseOrdersLimited = `-- name: CountPurchaseOrdersLimited :one
SELECT COUNT(*) FROM purchase_orders po
WHERE po.organization_id = $1
  AND ($2::text = '' OR UPPER(po.status) = UPPER($2))
  AND ($3::text = '' OR po.vendor_id     = $3)
  AND (
      po.created_by = $4
      OR po.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'purchase_order'
            AND (
                wt.assigned_user_id        = $4
                OR LOWER(wt.assigned_role) = LOWER($5)
                OR wt.assigned_role        = ANY($6::text[])
                OR wt.claimed_by           = $4
            )
      )
  )
`

type CountPurchaseOrdersLimitedParams struct {
	OrganizationID string   `json:"organizationId"`
	Column2        string   `json:"column2"`
	Column3        string   `json:"column3"`
	CreatedBy      *string  `json:"createdBy"`
	Lower          string   `json:"lower"`
	Column6        []string `json:"column6"`
}

func (q *Queries) CountPurchaseOrdersLimited(ctx context.Context, arg CountPurchaseOrdersLimitedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchaseOrdersLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.CreatedBy,
		arg.Lower,
		arg.Column6,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO purchase_orders (
    id, organization_id, document_number, vendor_id, status, items, total_amount,
    currency, delivery_date, approval_stage, approval_history, linked_requisition,
    description, department, department_id, gl_code, title, priority, subtotal,
    tax, total, budget_code, cost_center, project_code, required_by_date,
    source_requisition_number, source_requisition_id, created_by, owner_id,
    action_history, metadata, estimated_cost, quotation_gate_overridden,
    bypass_justification, automation_used, auto_created_grn, procurement_flow
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32,
    $33, $34, $35, $36, $37
) RETURNING id, organization_id, document_number, vendor_id, status, items, total_amount, currency, delivery_date, approval_stage, approval_history, linked_requisition, description, department, department_id, gl_code, title, priority, subtotal, tax, total, budget_code, cost_center, project_code, required_by_date, source_requisition_number, source_requisition_id, created_by, owner_id, action_history, metadata, estimated_cost, quotation_gate_overridden, bypass_justification, automation_used, auto_created_grn, deleted_at, created_at, updated_at, procurement_flow
`

type CreatePurchaseOrderParams struct {
	ID                      string             `json:"id"`
	OrganizationID          string             `json:"organizationId"`
	DocumentNumber          string             `json:"documentNumber"`
	VendorID                *string            `json:"vendorId"`
	Status                  *string            `json:"status"`
	Items                   []byte             `json:"items"`
	TotalAmount             *decimal.Decimal   `json:"totalAmount"`
	Currency                *string            `json:"currency"`
	DeliveryDate            pgtype.Timestamptz `json:"deliveryDate"`
	ApprovalStage           *int32             `json:"approvalStage"`
	ApprovalHistory         []byte             `json:"approvalHistory"`
	LinkedRequisition       *string            `json:"linkedRequisition"`
	Description             *string            `json:"description"`
	Department              *string            `json:"department"`
	DepartmentID            *string            `json:"departmentId"`
	GlCode                  *string            `json:"glCode"`
	Title                   *string            `json:"title"`
	Priority                *string            `json:"priority"`
	Subtotal                *decimal.Decimal   `json:"subtotal"`
	Tax                     *decimal.Decimal   `json:"tax"`
	Total                   *decimal.Decimal   `json:"total"`
	BudgetCode              *string            `json:"budgetCode"`
	CostCenter              *string            `json:"costCenter"`
	ProjectCode             *string            `json:"projectCode"`
	RequiredByDate          pgtype.Timestamptz `json:"requiredByDate"`
	SourceRequisitionNumber *string            `json:"sourceRequisitionNumber"`
	SourceRequisitionID     *string            `json:"sourceRequisitionId"`
	CreatedBy               *string            `json:"createdBy"`
	OwnerID                 *string            `json:"ownerId"`
	ActionHistory           []byte             `json:"actionHistory"`
	Metadata                []byte             `json:"metadata"`
	EstimatedCost           decimal.Decimal    `json:"estimatedCost"`
	QuotationGateOverridden bool               `json:"quotationGateOverridden"`
	BypassJustification     string             `json:"bypassJustification"`
	AutomationUsed          *bool              `json:"automationUsed"`
	AutoCreatedGrn          []byte             `json:"autoCreatedGrn"`
	ProcurementFlow         *string            `json:"procurementFlow"`
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.ID,
		arg.OrganizationID,
		arg.DocumentNumber,
		arg.VendorID,
		arg.Status,
		arg.Items,
		arg.TotalAmount,
		arg.Currency,
		arg.DeliveryDate,
		arg.ApprovalStage,
		arg.ApprovalHistory,
		arg.LinkedRequisition,
		arg.Description,
		arg.Department,
		arg.DepartmentID,
		arg.GlCode,
		arg.Title,
		arg.Priority,
		arg.Subtotal,
		arg.Tax,
		arg.Total,
		arg.BudgetCode,
		arg.CostCenter,
		arg.ProjectCode,
		arg.RequiredByDate,
		arg.SourceRequisitionNumber,
		arg.SourceRequisitionID,
		arg.CreatedBy,
		arg.OwnerID,
		arg.ActionHistory,
		arg.Metadata,
		arg.EstimatedCost,
		arg.QuotationGateOverridden,
		arg.BypassJustification,
		arg.AutomationUsed,
		arg.AutoCreatedGrn,
		arg.ProcurementFlow,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.Status,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.DeliveryDate,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedRequisition,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.GlCode,
		&i.Title,
		&i.Priority,
		&i.Subtotal,
		&i.Tax,
		&i.Total,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.RequiredByDate,
		&i.SourceRequisitionNumber,
		&i.SourceRequisitionID,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.EstimatedCost,
		&i.QuotationGateOverridden,
		&i.BypassJustification,
		&i.AutomationUsed,
		&i.AutoCreatedGrn,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcurementFlow,
	)
	return i, err
}

const getPurchaseOrderByID = `-- name: GetPurchaseOrderByID :one

SELECT id, organization_id, document_number, vendor_id, status, items, total_amount, currency, delivery_date, approval_stage, approval_history, linked_requisition, description, department, department_id, gl_code, title, priority, subtotal, tax, total, budget_code, cost_center, project_code, required_by_date, source_requisition_number, source_requisition_id, created_by, owner_id, action_history, metadata, estimated_cost, quotation_gate_overridden, bypass_justification, automation_used, auto_created_grn, deleted_at, created_at, updated_at, procurement_flow FROM purchase_orders WHERE id = $1 AND deleted_at IS NULL
`

type GetPurchaseOrderByIDParams struct {
	ID string `json:"id"`
}

// Purchase order read queries.
// Both CanViewAll and IsProcurement return all POs (ApplyToQuery passes through for both).
// Only two scope variants needed: All and Limited.
func (q *Queries) GetPurchaseOrderByID(ctx context.Context, arg GetPurchaseOrderByIDParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrderByID, arg.ID)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.Status,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.DeliveryDate,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedRequisition,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.GlCode,
		&i.Title,
		&i.Priority,
		&i.Subtotal,
		&i.Tax,
		&i.Total,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.RequiredByDate,
		&i.SourceRequisitionNumber,
		&i.SourceRequisitionID,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.EstimatedCost,
		&i.QuotationGateOverridden,
		&i.BypassJustification,
		&i.AutomationUsed,
		&i.AutoCreatedGrn,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcurementFlow,
	)
	return i, err
}

const getPurchaseOrderByNumber = `-- name: GetPurchaseOrderByNumber :one
SELECT id, organization_id, document_number, vendor_id, status, items, total_amount, currency, delivery_date, approval_stage, approval_history, linked_requisition, description, department, department_id, gl_code, title, priority, subtotal, tax, total, budget_code, cost_center, project_code, required_by_date, source_requisition_number, source_requisition_id, created_by, owner_id, action_history, metadata, estimated_cost, quotation_gate_overridden, bypass_justification, automation_used, auto_created_grn, deleted_at, created_at, updated_at, procurement_flow FROM purchase_orders WHERE organization_id = $1 AND document_number = $2 AND deleted_at IS NULL
`

type GetPurchaseOrderByNumberParams struct {
	OrganizationID string `json:"organizationId"`
	DocumentNumber string `json:"documentNumber"`
}

func (q *Queries) GetPurchaseOrderByNumber(ctx context.Context, arg GetPurchaseOrderByNumberParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrderByNumber, arg.OrganizationID, arg.DocumentNumber)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.Status,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.DeliveryDate,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedRequisition,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.GlCode,
		&i.Title,
		&i.Priority,
		&i.Subtotal,
		&i.Tax,
		&i.Total,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.RequiredByDate,
		&i.SourceRequisitionNumber,
		&i.SourceRequisitionID,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.EstimatedCost,
		&i.QuotationGateOverridden,
		&i.BypassJustification,
		&i.AutomationUsed,
		&i.AutoCreatedGrn,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcurementFlow,
	)
	return i, err
}

const linkRequisitionToPO = `-- name: LinkRequisitionToPO :exec
UPDATE purchase_orders SET linked_requisition = $2, updated_at = NOW() WHERE id = $1
`

type LinkRequisitionToPOParams struct {
	ID                string  `json:"id"`
	LinkedRequisition *string `json:"linkedRequisition"`
}

func (q *Queries) LinkRequisitionToPO(ctx context.Context, arg LinkRequisitionToPOParams) error {
	_, err := q.db.Exec(ctx, linkRequisitionToPO, arg.ID, arg.LinkedRequisition)
	return err
}

const listPurchaseOrderIDsAll = `-- name: ListPurchaseOrderIDsAll :many
SELECT id FROM purchase_orders
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status)    = UPPER($2))
  AND ($3::text = '' OR vendor_id        = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListPurchaseOrderIDsAllParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListPurchaseOrderIDsAll(ctx context.Context, arg ListPurchaseOrderIDsAllParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderIDsAll,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrderIDsLimited = `-- name: ListPurchaseOrderIDsLimited :many
SELECT po.id FROM purchase_orders po
WHERE po.organization_id = $1
  AND ($2::text = '' OR UPPER(po.status) = UPPER($2))
  AND ($3::text = '' OR po.vendor_id     = $3)
  AND (
      po.created_by = $4
      OR po.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'purchase_order'
            AND (
                wt.assigned_user_id        = $4
                OR LOWER(wt.assigned_role) = LOWER($5)
                OR wt.assigned_role        = ANY($6::text[])
                OR wt.claimed_by           = $4
            )
      )
  )
ORDER BY po.created_at DESC
LIMIT $7 OFFSET $8
`

type ListPurchaseOrderIDsLimitedParams struct {
	OrganizationID string   `json:"organizationId"`
	Column2        string   `json:"column2"`
	Column3        string   `json:"column3"`
	CreatedBy      *string  `json:"createdBy"`
	Lower          string   `json:"lower"`
	Column6        []string `json:"column6"`
	Limit          int32    `json:"limit"`
	Offset         int32    `json:"offset"`
}

func (q *Queries) ListPurchaseOrderIDsLimited(ctx context.Context, arg ListPurchaseOrderIDsLimitedParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderIDsLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.CreatedBy,
		arg.Lower,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT id, organization_id, document_number, vendor_id, status, items, total_amount, currency, delivery_date, approval_stage, approval_history, linked_requisition, description, department, department_id, gl_code, title, priority, subtotal, tax, total, budget_code, cost_center, project_code, required_by_date, source_requisition_number, source_requisition_id, created_by, owner_id, action_history, metadata, estimated_cost, quotation_gate_overridden, bypass_justification, automation_used, auto_created_grn, deleted_at, created_at, updated_at, procurement_flow FROM purchase_orders
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::text       = '' OR UPPER(status) = UPPER($2))
  AND ($3::text       = '' OR vendor_id     = $3)
  AND ($4::text       = '' OR department    = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
  AND ($7::text       = '' OR (title ILIKE '%' || $7 || '%' OR description ILIKE '%' || $7 || '%' OR document_number ILIKE '%' || $7 || '%'))
ORDER BY created_at DESC
LIMIT $8 OFFSET $9
`

type ListPurchaseOrdersParams struct {
	OrganizationID string             `json:"organizationId"`
	Column2        string             `json:"column2"`
	Column3        string             `json:"column3"`
	Column4        string             `json:"column4"`
	Column5        pgtype.Timestamptz `json:"column5"`
	Column6        pgtype.Timestamptz `json:"column6"`
	Column7        string             `json:"column7"`
	Limit          int32              `json:"limit"`
	Offset         int32              `json:"offset"`
}

func (q *Queries) ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]PurchaseOrder, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrders,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurchaseOrder{}
	for rows.Next() {
		var i PurchaseOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentNumber,
			&i.VendorID,
			&i.Status,
			&i.Items,
			&i.TotalAmount,
			&i.Currency,
			&i.DeliveryDate,
			&i.ApprovalStage,
			&i.ApprovalHistory,
			&i.LinkedRequisition,
			&i.Description,
			&i.Department,
			&i.DepartmentID,
			&i.GlCode,
			&i.Title,
			&i.Priority,
			&i.Subtotal,
			&i.Tax,
			&i.Total,
			&i.BudgetCode,
			&i.CostCenter,
			&i.ProjectCode,
			&i.RequiredByDate,
			&i.SourceRequisitionNumber,
			&i.SourceRequisitionID,
			&i.CreatedBy,
			&i.OwnerID,
			&i.ActionHistory,
			&i.Metadata,
			&i.EstimatedCost,
			&i.QuotationGateOverridden,
			&i.BypassJustification,
			&i.AutomationUsed,
			&i.AutoCreatedGrn,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcurementFlow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrdersByVendor = `-- name: ListPurchaseOrdersByVendor :many
SELECT id, organization_id, document_number, vendor_id, status, items, total_amount, currency, delivery_date, approval_stage, approval_history, linked_requisition, description, department, department_id, gl_code, title, priority, subtotal, tax, total, budget_code, cost_center, project_code, required_by_date, source_requisition_number, source_requisition_id, created_by, owner_id, action_history, metadata, estimated_cost, quotation_gate_overridden, bypass_justification, automation_used, auto_created_grn, deleted_at, created_at, updated_at, procurement_flow FROM purchase_orders
WHERE organization_id = $1
  AND vendor_id       = $2
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListPurchaseOrdersByVendorParams struct {
	OrganizationID string  `json:"organizationId"`
	VendorID       *string `json:"vendorId"`
	Limit          int32   `json:"limit"`
	Offset         int32   `json:"offset"`
}

func (q *Queries) ListPurchaseOrdersByVendor(ctx context.Context, arg ListPurchaseOrdersByVendorParams) ([]PurchaseOrder, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrdersByVendor,
		arg.OrganizationID,
		arg.VendorID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurchaseOrder{}
	for rows.Next() {
		var i PurchaseOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentNumber,
			&i.VendorID,
			&i.Status,
			&i.Items,
			&i.TotalAmount,
			&i.Currency,
			&i.DeliveryDate,
			&i.ApprovalStage,
			&i.ApprovalHistory,
			&i.LinkedRequisition,
			&i.Description,
			&i.Department,
			&i.DepartmentID,
			&i.GlCode,
			&i.Title,
			&i.Priority,
			&i.Subtotal,
			&i.Tax,
			&i.Total,
			&i.BudgetCode,
			&i.CostCenter,
			&i.ProjectCode,
			&i.RequiredByDate,
			&i.SourceRequisitionNumber,
			&i.SourceRequisitionID,
			&i.CreatedBy,
			&i.OwnerID,
			&i.ActionHistory,
			&i.Metadata,
			&i.EstimatedCost,
			&i.QuotationGateOverridden,
			&i.BypassJustification,
			&i.AutomationUsed,
			&i.AutoCreatedGrn,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcurementFlow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePO = `-- name: SoftDeletePO :exec
UPDATE purchase_orders SET deleted_at = NOW() WHERE id = $1
`

type SoftDeletePOParams struct {
	ID string `json:"id"`
}

func (q *Queries) SoftDeletePO(ctx context.Context, arg SoftDeletePOParams) error {
	_, err := q.db.Exec(ctx, softDeletePO, arg.ID)
	return err
}

const softDeletePurchaseOrder = `-- name: SoftDeletePurchaseOrder :exec
UPDATE purchase_orders SET deleted_at = NOW() WHERE id = $1
`

type SoftDeletePurchaseOrderParams struct {
	ID string `json:"id"`
}

func (q *Queries) SoftDeletePurchaseOrder(ctx context.Context, arg SoftDeletePurchaseOrderParams) error {
	_, err := q.db.Exec(ctx, softDeletePurchaseOrder, arg.ID)
	return err
}

const updatePOLinkedGRN = `-- name: UpdatePOLinkedGRN :exec
UPDATE purchase_orders
SET auto_created_grn = $2,
    updated_at       = NOW()
WHERE id = $1
`

type UpdatePOLinkedGRNParams struct {
	ID             string `json:"id"`
	AutoCreatedGrn []byte `json:"autoCreatedGrn"`
}

func (q *Queries) UpdatePOLinkedGRN(ctx context.Context, arg UpdatePOLinkedGRNParams) error {
	_, err := q.db.Exec(ctx, updatePOLinkedGRN, arg.ID, arg.AutoCreatedGrn)
	return err
}

const updatePOLinkedRequisition = `-- name: UpdatePOLinkedRequisition :exec
UPDATE purchase_orders
SET linked_requisition       = $2,
    source_requisition_id     = COALESCE($3, source_requisition_id),
    source_requisition_number = COALESCE($4, source_requisition_number),
    updated_at                = NOW()
WHERE id = $1
`

type UpdatePOLinkedRequisitionParams struct {
	ID                      string  `json:"id"`
	LinkedRequisition       *string `json:"linkedRequisition"`
	SourceRequisitionID     *string `json:"sourceRequisitionId"`
	SourceRequisitionNumber *string `json:"sourceRequisitionNumber"`
}

func (q *Queries) UpdatePOLinkedRequisition(ctx context.Context, arg UpdatePOLinkedRequisitionParams) error {
	_, err := q.db.Exec(ctx, updatePOLinkedRequisition,
		arg.ID,
		arg.LinkedRequisition,
		arg.SourceRequisitionID,
		arg.SourceRequisitionNumber,
	)
	return err
}

const updatePOStatus = `-- name: UpdatePOStatus :one
UPDATE purchase_orders
SET status         = $2,
    approval_stage = COALESCE($3, approval_stage),
    updated_at     = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, document_number, vendor_id, status, items, total_amount, currency, delivery_date, approval_stage, approval_history, linked_requisition, description, department, department_id, gl_code, title, priority, subtotal, tax, total, budget_code, cost_center, project_code, required_by_date, source_requisition_number, source_requisition_id, created_by, owner_id, action_history, metadata, estimated_cost, quotation_gate_overridden, bypass_justification, automation_used, auto_created_grn, deleted_at, created_at, updated_at, procurement_flow
`

type UpdatePOStatusParams struct {
	ID            string  `json:"id"`
	Status        *string `json:"status"`
	ApprovalStage *int32  `json:"approvalStage"`
}

func (q *Queries) UpdatePOStatus(ctx context.Context, arg UpdatePOStatusParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, updatePOStatus, arg.ID, arg.Status, arg.ApprovalStage)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.Status,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.DeliveryDate,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedRequisition,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.GlCode,
		&i.Title,
		&i.Priority,
		&i.Subtotal,
		&i.Tax,
		&i.Total,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.RequiredByDate,
		&i.SourceRequisitionNumber,
		&i.SourceRequisitionID,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.EstimatedCost,
		&i.QuotationGateOverridden,
		&i.BypassJustification,
		&i.AutomationUsed,
		&i.AutoCreatedGrn,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcurementFlow,
	)
	return i, err
}

const updatePurchaseOrder = `-- name: UpdatePurchaseOrder :one
UPDATE purchase_orders SET 
    vendor_id = COALESCE($2, vendor_id),
    status = COALESCE($3, status),
    total_amount = COALESCE($4, total_amount),
    currency = COALESCE($5, currency),
    delivery_date = COALESCE($6, delivery_date),
    approval_stage = COALESCE($7, approval_stage),
    linked_requisition = COALESCE($8, linked_requisition),
    department = COALESCE($9, department),
    department_id = COALESCE($10, department_id),
    gl_code = COALESCE($11, gl_code),
    title = COALESCE($12, title),
    description = COALESCE($13, description),
    priority = COALESCE($14, priority),
    budget_code = COALESCE($15, budget_code),
    cost_center = COALESCE($16, cost_center),
    project_code = COALESCE($17, project_code),
    procurement_flow = COALESCE($18, procurement_flow),
    estimated_cost = COALESCE($19, estimated_cost),
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, document_number, vendor_id, status, items, total_amount, currency, delivery_date, approval_stage, approval_history, linked_requisition, description, department, department_id, gl_code, title, priority, subtotal, tax, total, budget_code, cost_center, project_code, required_by_date, source_requisition_number, source_requisition_id, created_by, owner_id, action_history, metadata, estimated_cost, quotation_gate_overridden, bypass_justification, automation_used, auto_created_grn, deleted_at, created_at, updated_at, procurement_flow
`

type UpdatePurchaseOrderParams struct {
	ID                string             `json:"id"`
	VendorID          *string            `json:"vendorId"`
	Status            *string            `json:"status"`
	TotalAmount       *decimal.Decimal   `json:"totalAmount"`
	Currency          *string            `json:"currency"`
	DeliveryDate      pgtype.Timestamptz `json:"deliveryDate"`
	ApprovalStage     *int32             `json:"approvalStage"`
	LinkedRequisition *string            `json:"linkedRequisition"`
	Department        *string            `json:"department"`
	DepartmentID      *string            `json:"departmentId"`
	GlCode            *string            `json:"glCode"`
	Title             *string            `json:"title"`
	Description       *string            `json:"description"`
	Priority          *string            `json:"priority"`
	BudgetCode        *string            `json:"budgetCode"`
	CostCenter        *string            `json:"costCenter"`
	ProjectCode       *string            `json:"projectCode"`
	ProcurementFlow   *string            `json:"procurementFlow"`
	EstimatedCost     decimal.Decimal    `json:"estimatedCost"`
}

func (q *Queries) UpdatePurchaseOrder(ctx context.Context, arg UpdatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, updatePurchaseOrder,
		arg.ID,
		arg.VendorID,
		arg.Status,
		arg.TotalAmount,
		arg.Currency,
		arg.DeliveryDate,
		arg.ApprovalStage,
		arg.LinkedRequisition,
		arg.Department,
		arg.DepartmentID,
		arg.GlCode,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.BudgetCode,
		arg.CostCenter,
		arg.ProjectCode,
		arg.ProcurementFlow,
		arg.EstimatedCost,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.VendorID,
		&i.Status,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.DeliveryDate,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.LinkedRequisition,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.GlCode,
		&i.Title,
		&i.Priority,
		&i.Subtotal,
		&i.Tax,
		&i.Total,
		&i.BudgetCode,
		&i.CostCenter,
		&i.ProjectCode,
		&i.RequiredByDate,
		&i.SourceRequisitionNumber,
		&i.SourceRequisitionID,
		&i.CreatedBy,
		&i.OwnerID,
		&i.ActionHistory,
		&i.Metadata,
		&i.EstimatedCost,
		&i.QuotationGateOverridden,
		&i.BypassJustification,
		&i.AutomationUsed,
		&i.AutoCreatedGrn,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcurementFlow,
	)
	return i, err
}
