// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	ActivateUser(ctx context.Context, arg ActivateUserParams) error
	ActivateWorkflow(ctx context.Context, arg ActivateWorkflowParams) (Workflow, error)
	// Organization members queries
	// Composite uniqueness on (organization_id, user_id) — see uk_org_user.
	AddMember(ctx context.Context, arg AddMemberParams) (OrganizationMember, error)
	// User role assignments
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) (UserOrganizationRole, error)
	ClaimTask(ctx context.Context, arg ClaimTaskParams) (WorkflowTask, error)
	CleanupExpiredLockouts(ctx context.Context) error
	CountActiveSessions(ctx context.Context) (int64, error)
	CountActiveUsers(ctx context.Context) (int64, error)
	CountActiveWorkflows(ctx context.Context, arg CountActiveWorkflowsParams) (int64, error)
	CountActivityLogs(ctx context.Context, arg CountActivityLogsParams) (int64, error)
	CountActivityLogsByUser(ctx context.Context, arg CountActivityLogsByUserParams) (int64, error)
	CountAssignmentsByWorkflow(ctx context.Context, arg CountAssignmentsByWorkflowParams) (int64, error)
	CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error)
	// Audit log queries
	// Uses empty-string = skip-filter pattern to avoid nullable params.
	// All queries return the full row (no preloads needed for audit logs).
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountBranches(ctx context.Context, arg CountBranchesParams) (int64, error)
	CountBudgets(ctx context.Context, arg CountBudgetsParams) (int64, error)
	CountCategories(ctx context.Context, arg CountCategoriesParams) (int64, error)
	CountCategoryBudgetCodes(ctx context.Context, arg CountCategoryBudgetCodesParams) (int64, error)
	CountCustomRoles(ctx context.Context, arg CountCustomRolesParams) (int64, error)
	CountDepartments(ctx context.Context, arg CountDepartmentsParams) (int64, error)
	CountDocumentAuditLogs(ctx context.Context, arg CountDocumentAuditLogsParams) (int64, error)
	CountDocuments(ctx context.Context, arg CountDocumentsParams) (int64, error)
	CountGRNs(ctx context.Context, arg CountGRNsParams) (int64, error)
	CountGRNsAll(ctx context.Context, arg CountGRNsAllParams) (int64, error)
	CountGRNsByPO(ctx context.Context, arg CountGRNsByPOParams) (int64, error)
	CountGRNsLimited(ctx context.Context, arg CountGRNsLimitedParams) (int64, error)
	CountImpersonationLogs(ctx context.Context, arg CountImpersonationLogsParams) (int64, error)
	CountMembers(ctx context.Context, arg CountMembersParams) (int64, error)
	CountNotifications(ctx context.Context, arg CountNotificationsParams) (int64, error)
	CountOrganizationRoles(ctx context.Context, arg CountOrganizationRolesParams) (int64, error)
	CountOrganizations(ctx context.Context, arg CountOrganizationsParams) (int64, error)
	CountPaymentVouchers(ctx context.Context, arg CountPaymentVouchersParams) (int64, error)
	CountPaymentVouchersAll(ctx context.Context, arg CountPaymentVouchersAllParams) (int64, error)
	CountPaymentVouchersByVendor(ctx context.Context, arg CountPaymentVouchersByVendorParams) (int64, error)
	CountPaymentVouchersLimited(ctx context.Context, arg CountPaymentVouchersLimitedParams) (int64, error)
	CountPaymentVouchersProcurement(ctx context.Context, arg CountPaymentVouchersProcurementParams) (int64, error)
	CountPendingApprovalDocuments(ctx context.Context, arg CountPendingApprovalDocumentsParams) (int64, error)
	CountPurchaseOrders(ctx context.Context, arg CountPurchaseOrdersParams) (int64, error)
	CountPurchaseOrdersAll(ctx context.Context, arg CountPurchaseOrdersAllParams) (int64, error)
	CountPurchaseOrdersByVendor(ctx context.Context, arg CountPurchaseOrdersByVendorParams) (int64, error)
	CountPurchaseOrdersLimited(ctx context.Context, arg CountPurchaseOrdersLimitedParams) (int64, error)
	CountRequisitions(ctx context.Context, arg CountRequisitionsParams) (int64, error)
	CountRequisitionsAll(ctx context.Context, arg CountRequisitionsAllParams) (int64, error)
	CountRequisitionsByRequester(ctx context.Context, arg CountRequisitionsByRequesterParams) (int64, error)
	CountRequisitionsLimited(ctx context.Context, arg CountRequisitionsLimitedParams) (int64, error)
	CountRequisitionsProcurement(ctx context.Context, arg CountRequisitionsProcurementParams) (int64, error)
	CountTasksByAssignee(ctx context.Context, arg CountTasksByAssigneeParams) (int64, error)
	CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error)
	CountUserActiveSessions(ctx context.Context, arg CountUserActiveSessionsParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountVendors(ctx context.Context, arg CountVendorsParams) (int64, error)
	CountWorkflows(ctx context.Context, arg CountWorkflowsParams) (int64, error)
	CountWorkflowsByDocumentType(ctx context.Context, arg CountWorkflowsByDocumentTypeParams) (int64, error)
	CountWorkflowsByOrg(ctx context.Context, arg CountWorkflowsByOrgParams) (int64, error)
	CreateAccountLockout(ctx context.Context, arg CreateAccountLockoutParams) (AccountLockout, error)
	// User activity log queries
	// No FK on user_id (intentional, see migration 023) so queries are scope-only.
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (UserActivityLog, error)
	// Stage approval record queries
	// Audit-trail rows for approve/reject/return decisions on workflow tasks.
	CreateApprovalRecord(ctx context.Context, arg CreateApprovalRecordParams) (StageApprovalRecord, error)
	// Workflow assignment queries
	// An assignment binds an entity (e.g. a requisition) to a specific workflow version.
	CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (WorkflowAssignment, error)
	// Organization branches queries
	// Branches associated with an organization (province_id/town_id/manager_id).
	CreateBranch(ctx context.Context, arg CreateBranchParams) (OrganizationBranch, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	// Category budget code queries
	// Many-to-one mapping of GL/budget codes per category. No deleted_at column.
	CreateCategoryBudgetCode(ctx context.Context, arg CreateCategoryBudgetCodeParams) (CategoryBudgetCode, error)
	// Organization departments queries
	// Tree-structured departments scoped to an organization. No deleted_at column.
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (OrganizationDepartment, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateGRN(ctx context.Context, arg CreateGRNParams) (GoodsReceivedNote, error)
	// Impersonation log queries
	// Tracks platform/admin user impersonation events. id is TEXT not UUID.
	CreateImpersonationLog(ctx context.Context, arg CreateImpersonationLogParams) (ImpersonationLog, error)
	CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) (LoginAttempt, error)
	// Notification queries
	// User-scoped notification CRUD operations and bulk-update helpers.
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// Organization queries
	// The organizations table has no deleted_at column; soft-delete uses active = false.
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	// Enhanced RBAC with global system roles + org custom roles
	CreateOrganizationRole(ctx context.Context, arg CreateOrganizationRoleParams) (OrganizationRole, error)
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error)
	CreatePaymentVoucher(ctx context.Context, arg CreatePaymentVoucherParams) (PaymentVoucher, error)
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error)
	CreateRequisition(ctx context.Context, arg CreateRequisitionParams) (Requisition, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Workflow task queries
	// Tasks emitted per workflow stage. Optimistic-locking via version column on update.
	CreateTask(ctx context.Context, arg CreateTaskParams) (WorkflowTask, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	DeactivateOrganizationRole(ctx context.Context, arg DeactivateOrganizationRoleParams) error
	DeactivateUser(ctx context.Context, arg DeactivateUserParams) error
	DeactivateWorkflow(ctx context.Context, arg DeactivateWorkflowParams) (Workflow, error)
	DeleteBranch(ctx context.Context, arg DeleteBranchParams) error
	DeleteCategoryBudgetCode(ctx context.Context, arg DeleteCategoryBudgetCodeParams) error
	DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) error
	DeleteExpiredPasswordResets(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeleteNotificationPreferences(ctx context.Context, arg DeleteNotificationPreferencesParams) error
	DeleteOldActivityLogs(ctx context.Context, arg DeleteOldActivityLogsParams) error
	DeleteOldLoginAttempts(ctx context.Context, arg DeleteOldLoginAttemptsParams) error
	DeleteOldNotifications(ctx context.Context, arg DeleteOldNotificationsParams) error
	DeletePasswordResetsByUserID(ctx context.Context, arg DeletePasswordResetsByUserIDParams) error
	DeleteSession(ctx context.Context, arg DeleteSessionParams) error
	DeleteSessionByRefreshToken(ctx context.Context, arg DeleteSessionByRefreshTokenParams) error
	DeleteSessionsByUserID(ctx context.Context, arg DeleteSessionsByUserIDParams) error
	DeleteUsedPasswordResets(ctx context.Context) error
	DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) error
	ExpireStaleClaims(ctx context.Context) error
	GetAccountLockoutByEmail(ctx context.Context, arg GetAccountLockoutByEmailParams) (AccountLockout, error)
	GetAccountLockoutHistory(ctx context.Context, arg GetAccountLockoutHistoryParams) ([]AccountLockout, error)
	GetActiveAccountLockout(ctx context.Context, arg GetActiveAccountLockoutParams) (AccountLockout, error)
	GetActivityLogByID(ctx context.Context, arg GetActivityLogByIDParams) (UserActivityLog, error)
	GetApprovalRecordByID(ctx context.Context, arg GetApprovalRecordByIDParams) (StageApprovalRecord, error)
	GetAssignmentByEntity(ctx context.Context, arg GetAssignmentByEntityParams) (WorkflowAssignment, error)
	GetAssignmentByID(ctx context.Context, arg GetAssignmentByIDParams) (WorkflowAssignment, error)
	GetBranchByCode(ctx context.Context, arg GetBranchByCodeParams) (OrganizationBranch, error)
	GetBranchByID(ctx context.Context, arg GetBranchByIDParams) (OrganizationBranch, error)
	GetBudgetByCode(ctx context.Context, arg GetBudgetByCodeParams) (Budget, error)
	// Budget queries
	// Organization-scoped budget CRUD operations
	GetBudgetByID(ctx context.Context, arg GetBudgetByIDParams) (Budget, error)
	GetCategoryBudgetCodeByID(ctx context.Context, arg GetCategoryBudgetCodeByIDParams) (CategoryBudgetCode, error)
	// Category queries
	// Organization-scoped category CRUD operations
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error)
	GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error)
	GetDefaultWorkflowByDocumentType(ctx context.Context, arg GetDefaultWorkflowByDocumentTypeParams) (Workflow, error)
	GetDepartmentByCode(ctx context.Context, arg GetDepartmentByCodeParams) (OrganizationDepartment, error)
	GetDepartmentByID(ctx context.Context, arg GetDepartmentByIDParams) (OrganizationDepartment, error)
	// Documents queries
	// Generic documents table (NOT typed docs like requisitions, POs, etc.)
	// Organization-scoped CRUD with soft-delete via deleted_at IS NULL.
	GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (Document, error)
	GetDocumentByNumber(ctx context.Context, arg GetDocumentByNumberParams) (Document, error)
	GetDocumentStatsByDepartment(ctx context.Context, arg GetDocumentStatsByDepartmentParams) ([]GetDocumentStatsByDepartmentRow, error)
	GetDocumentStatsByStatus(ctx context.Context, arg GetDocumentStatsByStatusParams) ([]GetDocumentStatsByStatusRow, error)
	GetDocumentStatsByType(ctx context.Context, arg GetDocumentStatsByTypeParams) ([]GetDocumentStatsByTypeRow, error)
	GetGRNByDocumentNumber(ctx context.Context, arg GetGRNByDocumentNumberParams) (GoodsReceivedNote, error)
	// Goods received note read queries.
	// Both CanViewAll and IsProcurement use the unfiltered path (ApplyToQuery passes through).
	// Limited adds owner (created_by OR received_by) + workflow_tasks involvement.
	GetGRNByID(ctx context.Context, arg GetGRNByIDParams) (GoodsReceivedNote, error)
	GetImpersonationLogByID(ctx context.Context, arg GetImpersonationLogByIDParams) (ImpersonationLog, error)
	GetImpersonationLogByJTI(ctx context.Context, arg GetImpersonationLogByJTIParams) (ImpersonationLog, error)
	GetLinkedGRNByPONumber(ctx context.Context, arg GetLinkedGRNByPONumberParams) (GoodsReceivedNote, error)
	// Documents extra: cross-document link lookups
	// Used to fetch the related typed-document for a given document number/id.
	GetLinkedPOByRequisition(ctx context.Context, arg GetLinkedPOByRequisitionParams) (PurchaseOrder, error)
	GetLinkedPOByRequisitionNumber(ctx context.Context, arg GetLinkedPOByRequisitionNumberParams) (PurchaseOrder, error)
	// Batch enrichment queries for document cross-linking.
	// These replace the existing config.DB.Raw(DISTINCT ON...) calls in the list handlers.
	// pgx/v5 encodes []string natively for the ANY($n::text[]) array parameter.
	GetLinkedPOsForRequisitions(ctx context.Context, arg GetLinkedPOsForRequisitionsParams) ([]GetLinkedPOsForRequisitionsRow, error)
	GetLinkedPVByGRNNumber(ctx context.Context, arg GetLinkedPVByGRNNumberParams) (PaymentVoucher, error)
	GetLinkedPVByPONumber(ctx context.Context, arg GetLinkedPVByPONumberParams) (PaymentVoucher, error)
	GetLinkedPVsForPurchaseOrders(ctx context.Context, arg GetLinkedPVsForPurchaseOrdersParams) ([]GetLinkedPVsForPurchaseOrdersRow, error)
	GetLoginAttemptsByEmail(ctx context.Context, arg GetLoginAttemptsByEmailParams) ([]LoginAttempt, error)
	GetLoginAttemptsByUser(ctx context.Context, arg GetLoginAttemptsByUserParams) ([]LoginAttempt, error)
	GetMember(ctx context.Context, arg GetMemberParams) (OrganizationMember, error)
	GetMemberByID(ctx context.Context, arg GetMemberByIDParams) (OrganizationMember, error)
	GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (Notification, error)
	// Notification preferences queries
	// Per-user notification settings (one row per user; user_id is UNIQUE).
	GetNotificationPreferencesByUser(ctx context.Context, arg GetNotificationPreferencesByUserParams) (NotificationPreference, error)
	GetOrganizationByID(ctx context.Context, arg GetOrganizationByIDParams) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, arg GetOrganizationBySlugParams) (Organization, error)
	GetOrganizationRoleByID(ctx context.Context, arg GetOrganizationRoleByIDParams) (OrganizationRole, error)
	GetOrganizationRoleByName(ctx context.Context, arg GetOrganizationRoleByNameParams) (OrganizationRole, error)
	// Organization settings queries
	// One row per organization (organization_id is UNIQUE).
	GetOrganizationSettings(ctx context.Context, arg GetOrganizationSettingsParams) (OrganizationSetting, error)
	GetPasswordResetByToken(ctx context.Context, arg GetPasswordResetByTokenParams) (PasswordReset, error)
	// Payment voucher read queries.
	// Three scope variants:
	//   All         → scope.CanViewAll
	//   Procurement → scope.IsProcurement (linked_po != '' filter)
	//   Limited     → default (owner + workflow_tasks involvement filter)
	GetPaymentVoucherByID(ctx context.Context, arg GetPaymentVoucherByIDParams) (PaymentVoucher, error)
	GetPaymentVoucherByNumber(ctx context.Context, arg GetPaymentVoucherByNumberParams) (PaymentVoucher, error)
	GetProvinceByCode(ctx context.Context, arg GetProvinceByCodeParams) (Province, error)
	GetProvinceByID(ctx context.Context, arg GetProvinceByIDParams) (Province, error)
	// Purchase order read queries.
	// Both CanViewAll and IsProcurement return all POs (ApplyToQuery passes through for both).
	// Only two scope variants needed: All and Limited.
	GetPurchaseOrderByID(ctx context.Context, arg GetPurchaseOrderByIDParams) (PurchaseOrder, error)
	GetPurchaseOrderByNumber(ctx context.Context, arg GetPurchaseOrderByNumberParams) (PurchaseOrder, error)
	GetRecentFailedAttempts(ctx context.Context, arg GetRecentFailedAttemptsParams) (int64, error)
	GetRecentFailedAttemptsByIP(ctx context.Context, arg GetRecentFailedAttemptsByIPParams) (int64, error)
	// Requisition read queries.
	// List queries return only `id`; the handler fetches full data via GORM with Preload
	// to avoid complex pgtype↔model conversions. This keeps mappers unchanged.
	// Three scope variants per list/count pair:
	//   All         → scope.CanViewAll
	//   Procurement → scope.IsProcurement (workflow_assignments subquery filter)
	//   Limited     → default (owner + workflow_tasks involvement filter)
	GetRequisitionByID(ctx context.Context, arg GetRequisitionByIDParams) (Requisition, error)
	GetRequisitionByNumber(ctx context.Context, arg GetRequisitionByNumberParams) (Requisition, error)
	GetRequisitionByPONumber(ctx context.Context, arg GetRequisitionByPONumberParams) (Requisition, error)
	GetSessionByRefreshToken(ctx context.Context, arg GetSessionByRefreshTokenParams) (Session, error)
	GetSessionsByUserID(ctx context.Context, arg GetSessionsByUserIDParams) ([]Session, error)
	GetTaskByAssignment(ctx context.Context, arg GetTaskByAssignmentParams) (WorkflowTask, error)
	GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (WorkflowTask, error)
	GetTownByID(ctx context.Context, arg GetTownByIDParams) (Town, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	// Enhanced user queries with security features
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	GetUserRoleAssignments(ctx context.Context, arg GetUserRoleAssignmentsParams) ([]GetUserRoleAssignmentsRow, error)
	GetUserRoles(ctx context.Context, arg GetUserRolesParams) ([]OrganizationRole, error)
	GetVendorByCode(ctx context.Context, arg GetVendorByCodeParams) (Vendor, error)
	// Vendor queries
	// Organization-scoped vendor CRUD operations
	GetVendorByID(ctx context.Context, arg GetVendorByIDParams) (Vendor, error)
	GetWorkflowByID(ctx context.Context, arg GetWorkflowByIDParams) (Workflow, error)
	LinkGRNToPaymentVoucher(ctx context.Context, arg LinkGRNToPaymentVoucherParams) error
	LinkPOToPaymentVoucher(ctx context.Context, arg LinkPOToPaymentVoucherParams) error
	LinkPVToGRN(ctx context.Context, arg LinkPVToGRNParams) error
	LinkRequisitionToPO(ctx context.Context, arg LinkRequisitionToPOParams) error
	ListActiveBranches(ctx context.Context, arg ListActiveBranchesParams) ([]OrganizationBranch, error)
	ListActiveCategories(ctx context.Context, arg ListActiveCategoriesParams) ([]Category, error)
	ListActiveDepartments(ctx context.Context, arg ListActiveDepartmentsParams) ([]OrganizationDepartment, error)
	ListActiveImpersonations(ctx context.Context) ([]ImpersonationLog, error)
	ListActiveVendors(ctx context.Context, arg ListActiveVendorsParams) ([]Vendor, error)
	ListActiveWorkflows(ctx context.Context, arg ListActiveWorkflowsParams) ([]Workflow, error)
	ListActiveWorkflowsByDocumentType(ctx context.Context, arg ListActiveWorkflowsByDocumentTypeParams) ([]Workflow, error)
	ListActivityLogsByOrg(ctx context.Context, arg ListActivityLogsByOrgParams) ([]UserActivityLog, error)
	ListActivityLogsByUser(ctx context.Context, arg ListActivityLogsByUserParams) ([]UserActivityLog, error)
	ListApprovalRecordsByApprover(ctx context.Context, arg ListApprovalRecordsByApproverParams) ([]StageApprovalRecord, error)
	ListApprovalRecordsByAssignment(ctx context.Context, arg ListApprovalRecordsByAssignmentParams) ([]StageApprovalRecord, error)
	ListApprovalRecordsByTask(ctx context.Context, arg ListApprovalRecordsByTaskParams) ([]StageApprovalRecord, error)
	ListAssignmentsByEntity(ctx context.Context, arg ListAssignmentsByEntityParams) ([]WorkflowAssignment, error)
	ListAssignmentsByWorkflow(ctx context.Context, arg ListAssignmentsByWorkflowParams) ([]WorkflowAssignment, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditLog, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListBranches(ctx context.Context, arg ListBranchesParams) ([]OrganizationBranch, error)
	ListBudgets(ctx context.Context, arg ListBudgetsParams) ([]Budget, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListCategoryBudgetCodesByCategory(ctx context.Context, arg ListCategoryBudgetCodesByCategoryParams) ([]CategoryBudgetCode, error)
	ListCustomRoles(ctx context.Context, arg ListCustomRolesParams) ([]OrganizationRole, error)
	ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]OrganizationDepartment, error)
	ListDocumentAuditLogs(ctx context.Context, arg ListDocumentAuditLogsParams) ([]AuditLog, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error)
	ListGRNIDsAll(ctx context.Context, arg ListGRNIDsAllParams) ([]string, error)
	ListGRNIDsLimited(ctx context.Context, arg ListGRNIDsLimitedParams) ([]string, error)
	ListGRNs(ctx context.Context, arg ListGRNsParams) ([]GoodsReceivedNote, error)
	ListGRNsByPO(ctx context.Context, arg ListGRNsByPOParams) ([]GoodsReceivedNote, error)
	ListImpersonationLogs(ctx context.Context, arg ListImpersonationLogsParams) ([]ImpersonationLog, error)
	ListMembers(ctx context.Context, arg ListMembersParams) ([]OrganizationMember, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListOrganizationRoles(ctx context.Context, arg ListOrganizationRolesParams) ([]OrganizationRole, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListOrganizationsForUser(ctx context.Context, arg ListOrganizationsForUserParams) ([]OrganizationMember, error)
	ListPaymentVoucherIDsAll(ctx context.Context, arg ListPaymentVoucherIDsAllParams) ([]string, error)
	ListPaymentVoucherIDsLimited(ctx context.Context, arg ListPaymentVoucherIDsLimitedParams) ([]string, error)
	ListPaymentVoucherIDsProcurement(ctx context.Context, arg ListPaymentVoucherIDsProcurementParams) ([]string, error)
	ListPaymentVouchers(ctx context.Context, arg ListPaymentVouchersParams) ([]PaymentVoucher, error)
	ListPaymentVouchersByVendor(ctx context.Context, arg ListPaymentVouchersByVendorParams) ([]PaymentVoucher, error)
	// Provinces and towns queries
	// Reference (lookup) tables; read-only for application code.
	ListProvinces(ctx context.Context) ([]Province, error)
	ListPurchaseOrderIDsAll(ctx context.Context, arg ListPurchaseOrderIDsAllParams) ([]string, error)
	ListPurchaseOrderIDsLimited(ctx context.Context, arg ListPurchaseOrderIDsLimitedParams) ([]string, error)
	ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]PurchaseOrder, error)
	ListPurchaseOrdersByVendor(ctx context.Context, arg ListPurchaseOrdersByVendorParams) ([]PurchaseOrder, error)
	ListRecentDocuments(ctx context.Context, arg ListRecentDocumentsParams) ([]Document, error)
	ListRequisitionIDsAll(ctx context.Context, arg ListRequisitionIDsAllParams) ([]string, error)
	ListRequisitionIDsLimited(ctx context.Context, arg ListRequisitionIDsLimitedParams) ([]string, error)
	ListRequisitionIDsProcurement(ctx context.Context, arg ListRequisitionIDsProcurementParams) ([]string, error)
	ListRequisitions(ctx context.Context, arg ListRequisitionsParams) ([]Requisition, error)
	ListRequisitionsByRequester(ctx context.Context, arg ListRequisitionsByRequesterParams) ([]Requisition, error)
	ListSystemRoles(ctx context.Context) ([]OrganizationRole, error)
	ListTasksByAssignee(ctx context.Context, arg ListTasksByAssigneeParams) ([]WorkflowTask, error)
	ListTasksByEntity(ctx context.Context, arg ListTasksByEntityParams) ([]WorkflowTask, error)
	ListTowns(ctx context.Context) ([]Town, error)
	ListTownsByProvince(ctx context.Context, arg ListTownsByProvinceParams) ([]Town, error)
	ListUnsentNotifications(ctx context.Context, arg ListUnsentNotificationsParams) ([]Notification, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByOrganization(ctx context.Context, arg ListUsersByOrganizationParams) ([]User, error)
	ListUsersWithDeleted(ctx context.Context, arg ListUsersWithDeletedParams) ([]User, error)
	ListUsersWithRole(ctx context.Context, arg ListUsersWithRoleParams) ([]ListUsersWithRoleRow, error)
	ListVendors(ctx context.Context, arg ListVendorsParams) ([]Vendor, error)
	ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error)
	ListWorkflowsByDocumentType(ctx context.Context, arg ListWorkflowsByDocumentTypeParams) ([]Workflow, error)
	ListWorkflowsByOrg(ctx context.Context, arg ListWorkflowsByOrgParams) ([]Workflow, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) error
	MarkNotificationsReadBulk(ctx context.Context, arg MarkNotificationsReadBulkParams) error
	MarkPasswordResetAsUsed(ctx context.Context, arg MarkPasswordResetAsUsedParams) error
	ReleaseBudget(ctx context.Context, arg ReleaseBudgetParams) (Budget, error)
	ReleaseTaskClaim(ctx context.Context, arg ReleaseTaskClaimParams) error
	RemoveAllUserRoles(ctx context.Context, arg RemoveAllUserRolesParams) error
	RemoveMember(ctx context.Context, arg RemoveMemberParams) error
	RemoveMemberByUserOrg(ctx context.Context, arg RemoveMemberByUserOrgParams) error
	RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error
	ReserveBudget(ctx context.Context, arg ReserveBudgetParams) (Budget, error)
	RevokeImpersonationLog(ctx context.Context, arg RevokeImpersonationLogParams) error
	SoftDeleteBudget(ctx context.Context, arg SoftDeleteBudgetParams) error
	SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) error
	SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) error
	SoftDeleteGRN(ctx context.Context, arg SoftDeleteGRNParams) error
	SoftDeleteOrganization(ctx context.Context, arg SoftDeleteOrganizationParams) error
	SoftDeletePO(ctx context.Context, arg SoftDeletePOParams) error
	SoftDeletePV(ctx context.Context, arg SoftDeletePVParams) error
	SoftDeletePaymentVoucher(ctx context.Context, arg SoftDeletePaymentVoucherParams) error
	SoftDeletePurchaseOrder(ctx context.Context, arg SoftDeletePurchaseOrderParams) error
	SoftDeleteRequisition(ctx context.Context, arg SoftDeleteRequisitionParams) error
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error
	SoftDeleteVendor(ctx context.Context, arg SoftDeleteVendorParams) error
	SoftDeleteWorkflow(ctx context.Context, arg SoftDeleteWorkflowParams) error
	SubmitRequisition(ctx context.Context, arg SubmitRequisitionParams) (Requisition, error)
	UnlockAccount(ctx context.Context, arg UnlockAccountParams) error
	UnlockAccountByEmail(ctx context.Context, arg UnlockAccountByEmailParams) error
	UpdateAssignmentStatus(ctx context.Context, arg UpdateAssignmentStatusParams) (WorkflowAssignment, error)
	UpdateBranch(ctx context.Context, arg UpdateBranchParams) (OrganizationBranch, error)
	UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error)
	UpdateBudgetAllocatedAmount(ctx context.Context, arg UpdateBudgetAllocatedAmountParams) (Budget, error)
	UpdateBudgetRemainingAmount(ctx context.Context, arg UpdateBudgetRemainingAmountParams) (Budget, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryBudgetCode(ctx context.Context, arg UpdateCategoryBudgetCodeParams) (CategoryBudgetCode, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (OrganizationDepartment, error)
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error)
	UpdateGRN(ctx context.Context, arg UpdateGRNParams) (GoodsReceivedNote, error)
	UpdateGRNLinkedPV(ctx context.Context, arg UpdateGRNLinkedPVParams) error
	UpdateGRNStatus(ctx context.Context, arg UpdateGRNStatusParams) (GoodsReceivedNote, error)
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (OrganizationMember, error)
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (OrganizationMember, error)
	UpdateNotificationActionTaken(ctx context.Context, arg UpdateNotificationActionTakenParams) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateOrganizationRole(ctx context.Context, arg UpdateOrganizationRoleParams) (OrganizationRole, error)
	UpdatePOLinkedGRN(ctx context.Context, arg UpdatePOLinkedGRNParams) error
	UpdatePOLinkedRequisition(ctx context.Context, arg UpdatePOLinkedRequisitionParams) error
	UpdatePOStatus(ctx context.Context, arg UpdatePOStatusParams) (PurchaseOrder, error)
	UpdatePVLinkedGRN(ctx context.Context, arg UpdatePVLinkedGRNParams) error
	UpdatePVLinkedPO(ctx context.Context, arg UpdatePVLinkedPOParams) error
	UpdatePVStatus(ctx context.Context, arg UpdatePVStatusParams) (PaymentVoucher, error)
	UpdatePaymentVoucher(ctx context.Context, arg UpdatePaymentVoucherParams) (PaymentVoucher, error)
	UpdatePurchaseOrder(ctx context.Context, arg UpdatePurchaseOrderParams) (PurchaseOrder, error)
	UpdateRequisition(ctx context.Context, arg UpdateRequisitionParams) (Requisition, error)
	UpdateRequisitionStatus(ctx context.Context, arg UpdateRequisitionStatusParams) (Requisition, error)
	UpdateSessionRefreshToken(ctx context.Context, arg UpdateSessionRefreshTokenParams) (int64, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (WorkflowTask, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error)
	UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error)
	UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error)
	UpsertOrganizationSettings(ctx context.Context, arg UpsertOrganizationSettingsParams) (OrganizationSetting, error)
}

var _ Querier = (*Queries)(nil)
