// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requisitions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

const countRequisitions = `-- name: CountRequisitions :one
SELECT COUNT(*) FROM requisitions
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::text       = '' OR UPPER(status) = UPPER($2))
  AND ($3::text       = '' OR requester_id  = $3)
  AND ($4::text       = '' OR department    = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
  AND ($7::text       = '' OR (title ILIKE '%' || $7 || '%' OR description ILIKE '%' || $7 || '%' OR document_number ILIKE '%' || $7 || '%'))
`

type CountRequisitionsParams struct {
	OrganizationID string             `json:"organizationId"`
	Column2        string             `json:"column2"`
	Column3        string             `json:"column3"`
	Column4        string             `json:"column4"`
	Column5        pgtype.Timestamptz `json:"column5"`
	Column6        pgtype.Timestamptz `json:"column6"`
	Column7        string             `json:"column7"`
}

func (q *Queries) CountRequisitions(ctx context.Context, arg CountRequisitionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequisitions,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequisitionsAll = `-- name: CountRequisitionsAll :one
SELECT COUNT(*) FROM requisitions
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status)     = UPPER($2))
  AND ($3::text = '' OR department        = $3)
  AND ($4::text = '' OR priority          = $4)
`

type CountRequisitionsAllParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Column4        string `json:"column4"`
}

func (q *Queries) CountRequisitionsAll(ctx context.Context, arg CountRequisitionsAllParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequisitionsAll,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequisitionsByRequester = `-- name: CountRequisitionsByRequester :one
SELECT COUNT(*) FROM requisitions
WHERE organization_id = $1
  AND requester_id    = $2
  AND deleted_at IS NULL
`

type CountRequisitionsByRequesterParams struct {
	OrganizationID string `json:"organizationId"`
	RequesterID    string `json:"requesterId"`
}

func (q *Queries) CountRequisitionsByRequester(ctx context.Context, arg CountRequisitionsByRequesterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequisitionsByRequester, arg.OrganizationID, arg.RequesterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequisitionsLimited = `-- name: CountRequisitionsLimited :one
SELECT COUNT(*) FROM requisitions r
WHERE r.organization_id = $1
  AND ($2::text = '' OR UPPER(r.status)     = UPPER($2))
  AND ($3::text = '' OR r.department        = $3)
  AND ($4::text = '' OR r.priority          = $4)
  AND (
      r.requester_id = $5
      OR r.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'requisition'
            AND (
                wt.assigned_user_id        = $5
                OR LOWER(wt.assigned_role) = LOWER($6)
                OR wt.assigned_role        = ANY($7::text[])
                OR wt.claimed_by           = $5
            )
      )
  )
`

type CountRequisitionsLimitedParams struct {
	OrganizationID string   `json:"organizationId"`
	Column2        string   `json:"column2"`
	Column3        string   `json:"column3"`
	Column4        string   `json:"column4"`
	RequesterID    string   `json:"requesterId"`
	Lower          string   `json:"lower"`
	Column7        []string `json:"column7"`
}

func (q *Queries) CountRequisitionsLimited(ctx context.Context, arg CountRequisitionsLimitedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequisitionsLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.RequesterID,
		arg.Lower,
		arg.Column7,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequisitionsProcurement = `-- name: CountRequisitionsProcurement :one
SELECT COUNT(*) FROM requisitions r
WHERE r.organization_id = $1
  AND ($2::text = '' OR UPPER(r.status)   = UPPER($2))
  AND ($3::text = '' OR r.department      = $3)
  AND ($4::text = '' OR r.priority        = $4)
  AND r.id IN (
      SELECT wa.entity_id
      FROM workflow_assignments wa
      JOIN workflows w ON w.id = wa.workflow_id
      WHERE wa.entity_type     = 'requisition'
        AND wa.organization_id = $1
        AND (
            w.conditions->>'routingType' IS NULL OR
            w.conditions->>'routingType' = ''   OR
            w.conditions->>'routingType' = 'procurement'
        )
  )
`

type CountRequisitionsProcurementParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Column4        string `json:"column4"`
}

func (q *Queries) CountRequisitionsProcurement(ctx context.Context, arg CountRequisitionsProcurementParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequisitionsProcurement,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRequisition = `-- name: CreateRequisition :one
INSERT INTO requisitions (
    id, organization_id, document_number, requester_id, title, description,
    department, department_id, status, priority, total_amount, currency,
    approval_stage, category_id, preferred_vendor_id, is_estimate, budget_code,
    source_of_funds, required_by_date, cost_center, project_code, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22
) RETURNING id, organization_id, document_number, requester_id, title, description, department, department_id, status, priority, items, total_amount, currency, approval_stage, approval_history, action_history, category_id, preferred_vendor_id, is_estimate, required_by_date, cost_center, project_code, budget_code, source_of_funds, created_by, created_by_name, created_by_role, metadata, automation_used, auto_created_po, deleted_at, created_at, updated_at
`

type CreateRequisitionParams struct {
	ID                string             `json:"id"`
	OrganizationID    string             `json:"organizationId"`
	DocumentNumber    string             `json:"documentNumber"`
	RequesterID       string             `json:"requesterId"`
	Title             string             `json:"title"`
	Description       *string            `json:"description"`
	Department        *string            `json:"department"`
	DepartmentID      *string            `json:"departmentId"`
	Status            *string            `json:"status"`
	Priority          *string            `json:"priority"`
	TotalAmount       *decimal.Decimal   `json:"totalAmount"`
	Currency          *string            `json:"currency"`
	ApprovalStage     *int32             `json:"approvalStage"`
	CategoryID        *string            `json:"categoryId"`
	PreferredVendorID *string            `json:"preferredVendorId"`
	IsEstimate        *bool              `json:"isEstimate"`
	BudgetCode        *string            `json:"budgetCode"`
	SourceOfFunds     *string            `json:"sourceOfFunds"`
	RequiredByDate    pgtype.Timestamptz `json:"requiredByDate"`
	CostCenter        *string            `json:"costCenter"`
	ProjectCode       *string            `json:"projectCode"`
	CreatedBy         *string            `json:"createdBy"`
}

func (q *Queries) CreateRequisition(ctx context.Context, arg CreateRequisitionParams) (Requisition, error) {
	row := q.db.QueryRow(ctx, createRequisition,
		arg.ID,
		arg.OrganizationID,
		arg.DocumentNumber,
		arg.RequesterID,
		arg.Title,
		arg.Description,
		arg.Department,
		arg.DepartmentID,
		arg.Status,
		arg.Priority,
		arg.TotalAmount,
		arg.Currency,
		arg.ApprovalStage,
		arg.CategoryID,
		arg.PreferredVendorID,
		arg.IsEstimate,
		arg.BudgetCode,
		arg.SourceOfFunds,
		arg.RequiredByDate,
		arg.CostCenter,
		arg.ProjectCode,
		arg.CreatedBy,
	)
	var i Requisition
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.RequesterID,
		&i.Title,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.Priority,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.ActionHistory,
		&i.CategoryID,
		&i.PreferredVendorID,
		&i.IsEstimate,
		&i.RequiredByDate,
		&i.CostCenter,
		&i.ProjectCode,
		&i.BudgetCode,
		&i.SourceOfFunds,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedByRole,
		&i.Metadata,
		&i.AutomationUsed,
		&i.AutoCreatedPo,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequisitionByID = `-- name: GetRequisitionByID :one

SELECT id, organization_id, document_number, requester_id, title, description, department, department_id, status, priority, items, total_amount, currency, approval_stage, approval_history, action_history, category_id, preferred_vendor_id, is_estimate, required_by_date, cost_center, project_code, budget_code, source_of_funds, created_by, created_by_name, created_by_role, metadata, automation_used, auto_created_po, deleted_at, created_at, updated_at FROM requisitions WHERE id = $1 AND deleted_at IS NULL
`

type GetRequisitionByIDParams struct {
	ID string `json:"id"`
}

// Requisition read queries.
// List queries return only `id`; the handler fetches full data via GORM with Preload
// to avoid complex pgtype↔model conversions. This keeps mappers unchanged.
// Three scope variants per list/count pair:
//
//	All         → scope.CanViewAll
//	Procurement → scope.IsProcurement (workflow_assignments subquery filter)
//	Limited     → default (owner + workflow_tasks involvement filter)
func (q *Queries) GetRequisitionByID(ctx context.Context, arg GetRequisitionByIDParams) (Requisition, error) {
	row := q.db.QueryRow(ctx, getRequisitionByID, arg.ID)
	var i Requisition
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.RequesterID,
		&i.Title,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.Priority,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.ActionHistory,
		&i.CategoryID,
		&i.PreferredVendorID,
		&i.IsEstimate,
		&i.RequiredByDate,
		&i.CostCenter,
		&i.ProjectCode,
		&i.BudgetCode,
		&i.SourceOfFunds,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedByRole,
		&i.Metadata,
		&i.AutomationUsed,
		&i.AutoCreatedPo,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequisitionByNumber = `-- name: GetRequisitionByNumber :one
SELECT id, organization_id, document_number, requester_id, title, description, department, department_id, status, priority, items, total_amount, currency, approval_stage, approval_history, action_history, category_id, preferred_vendor_id, is_estimate, required_by_date, cost_center, project_code, budget_code, source_of_funds, created_by, created_by_name, created_by_role, metadata, automation_used, auto_created_po, deleted_at, created_at, updated_at FROM requisitions WHERE organization_id = $1 AND document_number = $2 AND deleted_at IS NULL
`

type GetRequisitionByNumberParams struct {
	OrganizationID string `json:"organizationId"`
	DocumentNumber string `json:"documentNumber"`
}

func (q *Queries) GetRequisitionByNumber(ctx context.Context, arg GetRequisitionByNumberParams) (Requisition, error) {
	row := q.db.QueryRow(ctx, getRequisitionByNumber, arg.OrganizationID, arg.DocumentNumber)
	var i Requisition
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.RequesterID,
		&i.Title,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.Priority,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.ActionHistory,
		&i.CategoryID,
		&i.PreferredVendorID,
		&i.IsEstimate,
		&i.RequiredByDate,
		&i.CostCenter,
		&i.ProjectCode,
		&i.BudgetCode,
		&i.SourceOfFunds,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedByRole,
		&i.Metadata,
		&i.AutomationUsed,
		&i.AutoCreatedPo,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRequisitionIDsAll = `-- name: ListRequisitionIDsAll :many
SELECT id FROM requisitions
WHERE organization_id = $1
  AND ($2::text = '' OR UPPER(status)     = UPPER($2))
  AND ($3::text = '' OR department        = $3)
  AND ($4::text = '' OR priority          = $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListRequisitionIDsAllParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Column4        string `json:"column4"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListRequisitionIDsAll(ctx context.Context, arg ListRequisitionIDsAllParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRequisitionIDsAll,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequisitionIDsLimited = `-- name: ListRequisitionIDsLimited :many
SELECT r.id FROM requisitions r
WHERE r.organization_id = $1
  AND ($2::text = '' OR UPPER(r.status)     = UPPER($2))
  AND ($3::text = '' OR r.department        = $3)
  AND ($4::text = '' OR r.priority          = $4)
  AND (
      r.requester_id = $5
      OR r.id IN (
          SELECT wt.entity_id FROM workflow_tasks wt
          WHERE wt.organization_id = $1
            AND wt.entity_type     = 'requisition'
            AND (
                wt.assigned_user_id        = $5
                OR LOWER(wt.assigned_role) = LOWER($6)
                OR wt.assigned_role        = ANY($7::text[])
                OR wt.claimed_by           = $5
            )
      )
  )
ORDER BY r.created_at DESC
LIMIT $8 OFFSET $9
`

type ListRequisitionIDsLimitedParams struct {
	OrganizationID string   `json:"organizationId"`
	Column2        string   `json:"column2"`
	Column3        string   `json:"column3"`
	Column4        string   `json:"column4"`
	RequesterID    string   `json:"requesterId"`
	Lower          string   `json:"lower"`
	Column7        []string `json:"column7"`
	Limit          int32    `json:"limit"`
	Offset         int32    `json:"offset"`
}

func (q *Queries) ListRequisitionIDsLimited(ctx context.Context, arg ListRequisitionIDsLimitedParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRequisitionIDsLimited,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.RequesterID,
		arg.Lower,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequisitionIDsProcurement = `-- name: ListRequisitionIDsProcurement :many
SELECT r.id FROM requisitions r
WHERE r.organization_id = $1
  AND ($2::text = '' OR UPPER(r.status)   = UPPER($2))
  AND ($3::text = '' OR r.department      = $3)
  AND ($4::text = '' OR r.priority        = $4)
  AND r.id IN (
      SELECT wa.entity_id
      FROM workflow_assignments wa
      JOIN workflows w ON w.id = wa.workflow_id
      WHERE wa.entity_type     = 'requisition'
        AND wa.organization_id = $1
        AND (
            w.conditions->>'routingType' IS NULL OR
            w.conditions->>'routingType' = ''   OR
            w.conditions->>'routingType' = 'procurement'
        )
  )
ORDER BY r.created_at DESC
LIMIT $5 OFFSET $6
`

type ListRequisitionIDsProcurementParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Column4        string `json:"column4"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListRequisitionIDsProcurement(ctx context.Context, arg ListRequisitionIDsProcurementParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRequisitionIDsProcurement,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequisitions = `-- name: ListRequisitions :many
SELECT id, organization_id, document_number, requester_id, title, description, department, department_id, status, priority, items, total_amount, currency, approval_stage, approval_history, action_history, category_id, preferred_vendor_id, is_estimate, required_by_date, cost_center, project_code, budget_code, source_of_funds, created_by, created_by_name, created_by_role, metadata, automation_used, auto_created_po, deleted_at, created_at, updated_at FROM requisitions
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::text       = '' OR UPPER(status) = UPPER($2))
  AND ($3::text       = '' OR requester_id  = $3)
  AND ($4::text       = '' OR department    = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
  AND ($7::text       = '' OR (title ILIKE '%' || $7 || '%' OR description ILIKE '%' || $7 || '%' OR document_number ILIKE '%' || $7 || '%'))
ORDER BY created_at DESC
LIMIT $8 OFFSET $9
`

type ListRequisitionsParams struct {
	OrganizationID string             `json:"organizationId"`
	Column2        string             `json:"column2"`
	Column3        string             `json:"column3"`
	Column4        string             `json:"column4"`
	Column5        pgtype.Timestamptz `json:"column5"`
	Column6        pgtype.Timestamptz `json:"column6"`
	Column7        string             `json:"column7"`
	Limit          int32              `json:"limit"`
	Offset         int32              `json:"offset"`
}

func (q *Queries) ListRequisitions(ctx context.Context, arg ListRequisitionsParams) ([]Requisition, error) {
	rows, err := q.db.Query(ctx, listRequisitions,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Requisition{}
	for rows.Next() {
		var i Requisition
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentNumber,
			&i.RequesterID,
			&i.Title,
			&i.Description,
			&i.Department,
			&i.DepartmentID,
			&i.Status,
			&i.Priority,
			&i.Items,
			&i.TotalAmount,
			&i.Currency,
			&i.ApprovalStage,
			&i.ApprovalHistory,
			&i.ActionHistory,
			&i.CategoryID,
			&i.PreferredVendorID,
			&i.IsEstimate,
			&i.RequiredByDate,
			&i.CostCenter,
			&i.ProjectCode,
			&i.BudgetCode,
			&i.SourceOfFunds,
			&i.CreatedBy,
			&i.CreatedByName,
			&i.CreatedByRole,
			&i.Metadata,
			&i.AutomationUsed,
			&i.AutoCreatedPo,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequisitionsByRequester = `-- name: ListRequisitionsByRequester :many
SELECT id, organization_id, document_number, requester_id, title, description, department, department_id, status, priority, items, total_amount, currency, approval_stage, approval_history, action_history, category_id, preferred_vendor_id, is_estimate, required_by_date, cost_center, project_code, budget_code, source_of_funds, created_by, created_by_name, created_by_role, metadata, automation_used, auto_created_po, deleted_at, created_at, updated_at FROM requisitions
WHERE organization_id = $1
  AND requester_id    = $2
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListRequisitionsByRequesterParams struct {
	OrganizationID string `json:"organizationId"`
	RequesterID    string `json:"requesterId"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListRequisitionsByRequester(ctx context.Context, arg ListRequisitionsByRequesterParams) ([]Requisition, error) {
	rows, err := q.db.Query(ctx, listRequisitionsByRequester,
		arg.OrganizationID,
		arg.RequesterID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Requisition{}
	for rows.Next() {
		var i Requisition
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DocumentNumber,
			&i.RequesterID,
			&i.Title,
			&i.Description,
			&i.Department,
			&i.DepartmentID,
			&i.Status,
			&i.Priority,
			&i.Items,
			&i.TotalAmount,
			&i.Currency,
			&i.ApprovalStage,
			&i.ApprovalHistory,
			&i.ActionHistory,
			&i.CategoryID,
			&i.PreferredVendorID,
			&i.IsEstimate,
			&i.RequiredByDate,
			&i.CostCenter,
			&i.ProjectCode,
			&i.BudgetCode,
			&i.SourceOfFunds,
			&i.CreatedBy,
			&i.CreatedByName,
			&i.CreatedByRole,
			&i.Metadata,
			&i.AutomationUsed,
			&i.AutoCreatedPo,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRequisition = `-- name: SoftDeleteRequisition :exec
UPDATE requisitions SET deleted_at = NOW() WHERE id = $1
`

type SoftDeleteRequisitionParams struct {
	ID string `json:"id"`
}

func (q *Queries) SoftDeleteRequisition(ctx context.Context, arg SoftDeleteRequisitionParams) error {
	_, err := q.db.Exec(ctx, softDeleteRequisition, arg.ID)
	return err
}

const submitRequisition = `-- name: SubmitRequisition :one
UPDATE requisitions
SET status         = 'submitted',
    approval_stage = 1,
    updated_at     = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, document_number, requester_id, title, description, department, department_id, status, priority, items, total_amount, currency, approval_stage, approval_history, action_history, category_id, preferred_vendor_id, is_estimate, required_by_date, cost_center, project_code, budget_code, source_of_funds, created_by, created_by_name, created_by_role, metadata, automation_used, auto_created_po, deleted_at, created_at, updated_at
`

type SubmitRequisitionParams struct {
	ID string `json:"id"`
}

func (q *Queries) SubmitRequisition(ctx context.Context, arg SubmitRequisitionParams) (Requisition, error) {
	row := q.db.QueryRow(ctx, submitRequisition, arg.ID)
	var i Requisition
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.RequesterID,
		&i.Title,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.Priority,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.ActionHistory,
		&i.CategoryID,
		&i.PreferredVendorID,
		&i.IsEstimate,
		&i.RequiredByDate,
		&i.CostCenter,
		&i.ProjectCode,
		&i.BudgetCode,
		&i.SourceOfFunds,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedByRole,
		&i.Metadata,
		&i.AutomationUsed,
		&i.AutoCreatedPo,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRequisition = `-- name: UpdateRequisition :one
UPDATE requisitions SET 
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    department = COALESCE($4, department),
    department_id = COALESCE($5, department_id),
    status = COALESCE($6, status),
    priority = COALESCE($7, priority),
    total_amount = COALESCE($8, total_amount),
    currency = COALESCE($9, currency),
    approval_stage = COALESCE($10, approval_stage),
    category_id = COALESCE($11, category_id),
    preferred_vendor_id = COALESCE($12, preferred_vendor_id),
    is_estimate = COALESCE($13, is_estimate),
    budget_code = COALESCE($14, budget_code),
    source_of_funds = COALESCE($15, source_of_funds),
    required_by_date = COALESCE($16, required_by_date),
    cost_center = COALESCE($17, cost_center),
    project_code = COALESCE($18, project_code),
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, document_number, requester_id, title, description, department, department_id, status, priority, items, total_amount, currency, approval_stage, approval_history, action_history, category_id, preferred_vendor_id, is_estimate, required_by_date, cost_center, project_code, budget_code, source_of_funds, created_by, created_by_name, created_by_role, metadata, automation_used, auto_created_po, deleted_at, created_at, updated_at
`

type UpdateRequisitionParams struct {
	ID                string             `json:"id"`
	Title             string             `json:"title"`
	Description       *string            `json:"description"`
	Department        *string            `json:"department"`
	DepartmentID      *string            `json:"departmentId"`
	Status            *string            `json:"status"`
	Priority          *string            `json:"priority"`
	TotalAmount       *decimal.Decimal   `json:"totalAmount"`
	Currency          *string            `json:"currency"`
	ApprovalStage     *int32             `json:"approvalStage"`
	CategoryID        *string            `json:"categoryId"`
	PreferredVendorID *string            `json:"preferredVendorId"`
	IsEstimate        *bool              `json:"isEstimate"`
	BudgetCode        *string            `json:"budgetCode"`
	SourceOfFunds     *string            `json:"sourceOfFunds"`
	RequiredByDate    pgtype.Timestamptz `json:"requiredByDate"`
	CostCenter        *string            `json:"costCenter"`
	ProjectCode       *string            `json:"projectCode"`
}

func (q *Queries) UpdateRequisition(ctx context.Context, arg UpdateRequisitionParams) (Requisition, error) {
	row := q.db.QueryRow(ctx, updateRequisition,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Department,
		arg.DepartmentID,
		arg.Status,
		arg.Priority,
		arg.TotalAmount,
		arg.Currency,
		arg.ApprovalStage,
		arg.CategoryID,
		arg.PreferredVendorID,
		arg.IsEstimate,
		arg.BudgetCode,
		arg.SourceOfFunds,
		arg.RequiredByDate,
		arg.CostCenter,
		arg.ProjectCode,
	)
	var i Requisition
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.RequesterID,
		&i.Title,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.Priority,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.ActionHistory,
		&i.CategoryID,
		&i.PreferredVendorID,
		&i.IsEstimate,
		&i.RequiredByDate,
		&i.CostCenter,
		&i.ProjectCode,
		&i.BudgetCode,
		&i.SourceOfFunds,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedByRole,
		&i.Metadata,
		&i.AutomationUsed,
		&i.AutoCreatedPo,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRequisitionStatus = `-- name: UpdateRequisitionStatus :one
UPDATE requisitions
SET status         = $2,
    approval_stage = COALESCE($3, approval_stage),
    updated_at     = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, document_number, requester_id, title, description, department, department_id, status, priority, items, total_amount, currency, approval_stage, approval_history, action_history, category_id, preferred_vendor_id, is_estimate, required_by_date, cost_center, project_code, budget_code, source_of_funds, created_by, created_by_name, created_by_role, metadata, automation_used, auto_created_po, deleted_at, created_at, updated_at
`

type UpdateRequisitionStatusParams struct {
	ID            string  `json:"id"`
	Status        *string `json:"status"`
	ApprovalStage *int32  `json:"approvalStage"`
}

func (q *Queries) UpdateRequisitionStatus(ctx context.Context, arg UpdateRequisitionStatusParams) (Requisition, error) {
	row := q.db.QueryRow(ctx, updateRequisitionStatus, arg.ID, arg.Status, arg.ApprovalStage)
	var i Requisition
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentNumber,
		&i.RequesterID,
		&i.Title,
		&i.Description,
		&i.Department,
		&i.DepartmentID,
		&i.Status,
		&i.Priority,
		&i.Items,
		&i.TotalAmount,
		&i.Currency,
		&i.ApprovalStage,
		&i.ApprovalHistory,
		&i.ActionHistory,
		&i.CategoryID,
		&i.PreferredVendorID,
		&i.IsEstimate,
		&i.RequiredByDate,
		&i.CostCenter,
		&i.ProjectCode,
		&i.BudgetCode,
		&i.SourceOfFunds,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedByRole,
		&i.Metadata,
		&i.AutomationUsed,
		&i.AutoCreatedPo,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
