// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSessions = `-- name: CountActiveSessions :one
SELECT COUNT(*) FROM sessions WHERE expires_at > NOW()
`

func (q *Queries) CountActiveSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserActiveSessions = `-- name: CountUserActiveSessions :one
SELECT COUNT(*) FROM sessions 
WHERE user_id = $1 AND expires_at > NOW()
`

type CountUserActiveSessionsParams struct {
	UserID string `json:"userId"`
}

func (q *Queries) CountUserActiveSessions(ctx context.Context, arg CountUserActiveSessionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserActiveSessions, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, refresh_token, ip_address, user_agent, expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, refresh_token, ip_address, user_agent, expires_at, created_at, updated_at
`

type CreateSessionParams struct {
	UserID       string             `json:"userId"`
	RefreshToken string             `json:"refreshToken"`
	IpAddress    *string            `json:"ipAddress"`
	UserAgent    *string            `json:"userAgent"`
	ExpiresAt    pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshToken,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

type DeleteSessionParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.ID)
	return err
}

const deleteSessionByRefreshToken = `-- name: DeleteSessionByRefreshToken :exec
DELETE FROM sessions WHERE refresh_token = $1
`

type DeleteSessionByRefreshTokenParams struct {
	RefreshToken string `json:"refreshToken"`
}

func (q *Queries) DeleteSessionByRefreshToken(ctx context.Context, arg DeleteSessionByRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, deleteSessionByRefreshToken, arg.RefreshToken)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions WHERE user_id = $1
`

type DeleteSessionsByUserIDParams struct {
	UserID string `json:"userId"`
}

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, arg DeleteSessionsByUserIDParams) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserID, arg.UserID)
	return err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, refresh_token, ip_address, user_agent, expires_at, created_at, updated_at FROM sessions 
WHERE refresh_token = $1 AND expires_at > NOW()
`

type GetSessionByRefreshTokenParams struct {
	RefreshToken string `json:"refreshToken"`
}

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, arg GetSessionByRefreshTokenParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, arg.RefreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionsByUserID = `-- name: GetSessionsByUserID :many
SELECT id, user_id, refresh_token, ip_address, user_agent, expires_at, created_at, updated_at FROM sessions 
WHERE user_id = $1 AND expires_at > NOW()
ORDER BY created_at DESC
`

type GetSessionsByUserIDParams struct {
	UserID string `json:"userId"`
}

func (q *Queries) GetSessionsByUserID(ctx context.Context, arg GetSessionsByUserIDParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsByUserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshToken,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionRefreshToken = `-- name: UpdateSessionRefreshToken :execrows
UPDATE sessions 
SET refresh_token = $2, expires_at = $3, updated_at = NOW()
WHERE id = $1 AND refresh_token = $4
`

type UpdateSessionRefreshTokenParams struct {
	ID             pgtype.UUID        `json:"id"`
	RefreshToken   string             `json:"refreshToken"`
	ExpiresAt      pgtype.Timestamptz `json:"expiresAt"`
	RefreshToken_2 string             `json:"refreshToken2"`
}

func (q *Queries) UpdateSessionRefreshToken(ctx context.Context, arg UpdateSessionRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSessionRefreshToken,
		arg.ID,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.RefreshToken_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
