// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stage_approval_records.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApprovalRecord = `-- name: CreateApprovalRecord :one

INSERT INTO stage_approval_records (
    id, organization_id, workflow_task_id, stage_number, approver_id,
    approver_name, approver_role, man_number, position, action, comments,
    signature, approved_at, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, organization_id, workflow_task_id, stage_number, approver_id, approver_name, approver_role, man_number, position, action, comments, signature, approved_at, ip_address, user_agent, created_at
`

type CreateApprovalRecordParams struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organizationId"`
	WorkflowTaskID string             `json:"workflowTaskId"`
	StageNumber    int32              `json:"stageNumber"`
	ApproverID     string             `json:"approverId"`
	ApproverName   string             `json:"approverName"`
	ApproverRole   string             `json:"approverRole"`
	ManNumber      string             `json:"manNumber"`
	Position       string             `json:"position"`
	Action         string             `json:"action"`
	Comments       *string            `json:"comments"`
	Signature      *string            `json:"signature"`
	ApprovedAt     pgtype.Timestamptz `json:"approvedAt"`
	IpAddress      *string            `json:"ipAddress"`
	UserAgent      *string            `json:"userAgent"`
}

// Stage approval record queries
// Audit-trail rows for approve/reject/return decisions on workflow tasks.
func (q *Queries) CreateApprovalRecord(ctx context.Context, arg CreateApprovalRecordParams) (StageApprovalRecord, error) {
	row := q.db.QueryRow(ctx, createApprovalRecord,
		arg.ID,
		arg.OrganizationID,
		arg.WorkflowTaskID,
		arg.StageNumber,
		arg.ApproverID,
		arg.ApproverName,
		arg.ApproverRole,
		arg.ManNumber,
		arg.Position,
		arg.Action,
		arg.Comments,
		arg.Signature,
		arg.ApprovedAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i StageApprovalRecord
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkflowTaskID,
		&i.StageNumber,
		&i.ApproverID,
		&i.ApproverName,
		&i.ApproverRole,
		&i.ManNumber,
		&i.Position,
		&i.Action,
		&i.Comments,
		&i.Signature,
		&i.ApprovedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getApprovalRecordByID = `-- name: GetApprovalRecordByID :one
SELECT id, organization_id, workflow_task_id, stage_number, approver_id, approver_name, approver_role, man_number, position, action, comments, signature, approved_at, ip_address, user_agent, created_at FROM stage_approval_records WHERE id = $1
`

type GetApprovalRecordByIDParams struct {
	ID string `json:"id"`
}

func (q *Queries) GetApprovalRecordByID(ctx context.Context, arg GetApprovalRecordByIDParams) (StageApprovalRecord, error) {
	row := q.db.QueryRow(ctx, getApprovalRecordByID, arg.ID)
	var i StageApprovalRecord
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkflowTaskID,
		&i.StageNumber,
		&i.ApproverID,
		&i.ApproverName,
		&i.ApproverRole,
		&i.ManNumber,
		&i.Position,
		&i.Action,
		&i.Comments,
		&i.Signature,
		&i.ApprovedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovalRecordsByApprover = `-- name: ListApprovalRecordsByApprover :many
SELECT id, organization_id, workflow_task_id, stage_number, approver_id, approver_name, approver_role, man_number, position, action, comments, signature, approved_at, ip_address, user_agent, created_at FROM stage_approval_records
WHERE organization_id = $1 AND approver_id = $2
ORDER BY approved_at DESC
LIMIT $3 OFFSET $4
`

type ListApprovalRecordsByApproverParams struct {
	OrganizationID string `json:"organizationId"`
	ApproverID     string `json:"approverId"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListApprovalRecordsByApprover(ctx context.Context, arg ListApprovalRecordsByApproverParams) ([]StageApprovalRecord, error) {
	rows, err := q.db.Query(ctx, listApprovalRecordsByApprover,
		arg.OrganizationID,
		arg.ApproverID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StageApprovalRecord{}
	for rows.Next() {
		var i StageApprovalRecord
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkflowTaskID,
			&i.StageNumber,
			&i.ApproverID,
			&i.ApproverName,
			&i.ApproverRole,
			&i.ManNumber,
			&i.Position,
			&i.Action,
			&i.Comments,
			&i.Signature,
			&i.ApprovedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalRecordsByAssignment = `-- name: ListApprovalRecordsByAssignment :many
SELECT sar.id, sar.organization_id, sar.workflow_task_id, sar.stage_number, sar.approver_id, sar.approver_name, sar.approver_role, sar.man_number, sar.position, sar.action, sar.comments, sar.signature, sar.approved_at, sar.ip_address, sar.user_agent, sar.created_at
FROM stage_approval_records sar
INNER JOIN workflow_tasks wt ON wt.id = sar.workflow_task_id
WHERE wt.workflow_assignment_id = $1
ORDER BY sar.approved_at DESC
`

type ListApprovalRecordsByAssignmentParams struct {
	WorkflowAssignmentID string `json:"workflowAssignmentId"`
}

func (q *Queries) ListApprovalRecordsByAssignment(ctx context.Context, arg ListApprovalRecordsByAssignmentParams) ([]StageApprovalRecord, error) {
	rows, err := q.db.Query(ctx, listApprovalRecordsByAssignment, arg.WorkflowAssignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StageApprovalRecord{}
	for rows.Next() {
		var i StageApprovalRecord
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkflowTaskID,
			&i.StageNumber,
			&i.ApproverID,
			&i.ApproverName,
			&i.ApproverRole,
			&i.ManNumber,
			&i.Position,
			&i.Action,
			&i.Comments,
			&i.Signature,
			&i.ApprovedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalRecordsByTask = `-- name: ListApprovalRecordsByTask :many
SELECT id, organization_id, workflow_task_id, stage_number, approver_id, approver_name, approver_role, man_number, position, action, comments, signature, approved_at, ip_address, user_agent, created_at FROM stage_approval_records
WHERE workflow_task_id = $1
ORDER BY approved_at DESC
`

type ListApprovalRecordsByTaskParams struct {
	WorkflowTaskID string `json:"workflowTaskId"`
}

func (q *Queries) ListApprovalRecordsByTask(ctx context.Context, arg ListApprovalRecordsByTaskParams) ([]StageApprovalRecord, error) {
	rows, err := q.db.Query(ctx, listApprovalRecordsByTask, arg.WorkflowTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StageApprovalRecord{}
	for rows.Next() {
		var i StageApprovalRecord
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkflowTaskID,
			&i.StageNumber,
			&i.ApproverID,
			&i.ApproverName,
			&i.ApproverRole,
			&i.ManNumber,
			&i.Position,
			&i.Action,
			&i.Comments,
			&i.Signature,
			&i.ApprovedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
