// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_activity_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivityLogs = `-- name: CountActivityLogs :one
SELECT COUNT(*) FROM user_activity_logs
WHERE ($1::text       = '' OR organization_id = $1)
  AND ($2::text       = '' OR user_id         = $2)
  AND ($3::text       = '' OR action_type     = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)
`

type CountActivityLogsParams struct {
	Column1 string             `json:"column1"`
	Column2 string             `json:"column2"`
	Column3 string             `json:"column3"`
	Column4 pgtype.Timestamptz `json:"column4"`
	Column5 pgtype.Timestamptz `json:"column5"`
}

func (q *Queries) CountActivityLogs(ctx context.Context, arg CountActivityLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivityLogsByUser = `-- name: CountActivityLogsByUser :one
SELECT COUNT(*) FROM user_activity_logs
WHERE user_id = $1
  AND ($2::text       = '' OR action_type = $2)
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz IS NULL OR created_at <= $4)
`

type CountActivityLogsByUserParams struct {
	UserID  string             `json:"userId"`
	Column2 string             `json:"column2"`
	Column3 pgtype.Timestamptz `json:"column3"`
	Column4 pgtype.Timestamptz `json:"column4"`
}

func (q *Queries) CountActivityLogsByUser(ctx context.Context, arg CountActivityLogsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityLogsByUser,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :one

INSERT INTO user_activity_logs (
    id, user_id, organization_id, action_type, resource_type, resource_id,
    ip_address, user_agent, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, organization_id, action_type, resource_type, resource_id, ip_address, user_agent, metadata, created_at
`

type CreateActivityLogParams struct {
	ID             pgtype.UUID `json:"id"`
	UserID         string      `json:"userId"`
	OrganizationID *string     `json:"organizationId"`
	ActionType     string      `json:"actionType"`
	ResourceType   *string     `json:"resourceType"`
	ResourceID     *string     `json:"resourceId"`
	IpAddress      *string     `json:"ipAddress"`
	UserAgent      *string     `json:"userAgent"`
	Metadata       []byte      `json:"metadata"`
}

// User activity log queries
// No FK on user_id (intentional, see migration 023) so queries are scope-only.
func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (UserActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.ID,
		arg.UserID,
		arg.OrganizationID,
		arg.ActionType,
		arg.ResourceType,
		arg.ResourceID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	var i UserActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.ActionType,
		&i.ResourceType,
		&i.ResourceID,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldActivityLogs = `-- name: DeleteOldActivityLogs :exec
DELETE FROM user_activity_logs WHERE created_at < $1
`

type DeleteOldActivityLogsParams struct {
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) DeleteOldActivityLogs(ctx context.Context, arg DeleteOldActivityLogsParams) error {
	_, err := q.db.Exec(ctx, deleteOldActivityLogs, arg.CreatedAt)
	return err
}

const getActivityLogByID = `-- name: GetActivityLogByID :one
SELECT id, user_id, organization_id, action_type, resource_type, resource_id, ip_address, user_agent, metadata, created_at FROM user_activity_logs WHERE id = $1
`

type GetActivityLogByIDParams struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) GetActivityLogByID(ctx context.Context, arg GetActivityLogByIDParams) (UserActivityLog, error) {
	row := q.db.QueryRow(ctx, getActivityLogByID, arg.ID)
	var i UserActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.ActionType,
		&i.ResourceType,
		&i.ResourceID,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityLogsByOrg = `-- name: ListActivityLogsByOrg :many
SELECT id, user_id, organization_id, action_type, resource_type, resource_id, ip_address, user_agent, metadata, created_at FROM user_activity_logs
WHERE organization_id = $1
  AND ($2::text       = '' OR action_type = $2)
  AND ($3::text       = '' OR user_id     = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)
ORDER BY created_at DESC
LIMIT $6 OFFSET $7
`

type ListActivityLogsByOrgParams struct {
	OrganizationID *string            `json:"organizationId"`
	Column2        string             `json:"column2"`
	Column3        string             `json:"column3"`
	Column4        pgtype.Timestamptz `json:"column4"`
	Column5        pgtype.Timestamptz `json:"column5"`
	Limit          int32              `json:"limit"`
	Offset         int32              `json:"offset"`
}

func (q *Queries) ListActivityLogsByOrg(ctx context.Context, arg ListActivityLogsByOrgParams) ([]UserActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByOrg,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserActivityLog{}
	for rows.Next() {
		var i UserActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationID,
			&i.ActionType,
			&i.ResourceType,
			&i.ResourceID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogsByUser = `-- name: ListActivityLogsByUser :many
SELECT id, user_id, organization_id, action_type, resource_type, resource_id, ip_address, user_agent, metadata, created_at FROM user_activity_logs
WHERE user_id = $1
  AND ($2::text       = '' OR action_type = $2)
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz IS NULL OR created_at <= $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListActivityLogsByUserParams struct {
	UserID  string             `json:"userId"`
	Column2 string             `json:"column2"`
	Column3 pgtype.Timestamptz `json:"column3"`
	Column4 pgtype.Timestamptz `json:"column4"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
}

func (q *Queries) ListActivityLogsByUser(ctx context.Context, arg ListActivityLogsByUserParams) ([]UserActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByUser,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserActivityLog{}
	for rows.Next() {
		var i UserActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationID,
			&i.ActionType,
			&i.ResourceType,
			&i.ResourceID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
