// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_enhanced.sql

package db

import (
	"context"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users SET 
    active = true,
    updated_at = NOW()
WHERE id = $1
`

type ActivateUserParams struct {
	ID string `json:"id"`
}

func (q *Queries) ActivateUser(ctx context.Context, arg ActivateUserParams) error {
	_, err := q.db.Exec(ctx, activateUser, arg.ID)
	return err
}

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) FROM users WHERE active = true AND deleted_at IS NULL
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, name, password, role, active, current_organization_id, is_super_admin,
    must_change_password, position, man_number, nrc_number, contact
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, email, name, password, role, active, last_login, current_organization_id, is_super_admin, preferences, deleted_at, position, man_number, nrc_number, contact, mfa_enabled, is_ldap_user, must_change_password, created_at, updated_at
`

type CreateUserParams struct {
	ID                    string  `json:"id"`
	Email                 string  `json:"email"`
	Name                  string  `json:"name"`
	Password              string  `json:"password"`
	Role                  string  `json:"role"`
	Active                bool    `json:"active"`
	CurrentOrganizationID *string `json:"currentOrganizationId"`
	IsSuperAdmin          bool    `json:"isSuperAdmin"`
	MustChangePassword    bool    `json:"mustChangePassword"`
	Position              *string `json:"position"`
	ManNumber             *string `json:"manNumber"`
	NrcNumber             *string `json:"nrcNumber"`
	Contact               *string `json:"contact"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Password,
		arg.Role,
		arg.Active,
		arg.CurrentOrganizationID,
		arg.IsSuperAdmin,
		arg.MustChangePassword,
		arg.Position,
		arg.ManNumber,
		arg.NrcNumber,
		arg.Contact,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.LastLogin,
		&i.CurrentOrganizationID,
		&i.IsSuperAdmin,
		&i.Preferences,
		&i.DeletedAt,
		&i.Position,
		&i.ManNumber,
		&i.NrcNumber,
		&i.Contact,
		&i.MfaEnabled,
		&i.IsLdapUser,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET 
    active = false,
    updated_at = NOW()
WHERE id = $1
`

type DeactivateUserParams struct {
	ID string `json:"id"`
}

func (q *Queries) DeactivateUser(ctx context.Context, arg DeactivateUserParams) error {
	_, err := q.db.Exec(ctx, deactivateUser, arg.ID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password, role, active, last_login, current_organization_id, is_super_admin, preferences, deleted_at, position, man_number, nrc_number, contact, mfa_enabled, is_ldap_user, must_change_password, created_at, updated_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	Email string `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.LastLogin,
		&i.CurrentOrganizationID,
		&i.IsSuperAdmin,
		&i.Preferences,
		&i.DeletedAt,
		&i.Position,
		&i.ManNumber,
		&i.NrcNumber,
		&i.Contact,
		&i.MfaEnabled,
		&i.IsLdapUser,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, name, password, role, active, last_login, current_organization_id, is_super_admin, preferences, deleted_at, position, man_number, nrc_number, contact, mfa_enabled, is_ldap_user, must_change_password, created_at, updated_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDParams struct {
	ID string `json:"id"`
}

// Enhanced user queries with security features
func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.LastLogin,
		&i.CurrentOrganizationID,
		&i.IsSuperAdmin,
		&i.Preferences,
		&i.DeletedAt,
		&i.Position,
		&i.ManNumber,
		&i.NrcNumber,
		&i.Contact,
		&i.MfaEnabled,
		&i.IsLdapUser,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, password, role, active, last_login, current_organization_id, is_super_admin, preferences, deleted_at, position, man_number, nrc_number, contact, mfa_enabled, is_ldap_user, must_change_password, created_at, updated_at FROM users 
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Password,
			&i.Role,
			&i.Active,
			&i.LastLogin,
			&i.CurrentOrganizationID,
			&i.IsSuperAdmin,
			&i.Preferences,
			&i.DeletedAt,
			&i.Position,
			&i.ManNumber,
			&i.NrcNumber,
			&i.Contact,
			&i.MfaEnabled,
			&i.IsLdapUser,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByOrganization = `-- name: ListUsersByOrganization :many
SELECT u.id, u.email, u.name, u.password, u.role, u.active, u.last_login, u.current_organization_id, u.is_super_admin, u.preferences, u.deleted_at, u.position, u.man_number, u.nrc_number, u.contact, u.mfa_enabled, u.is_ldap_user, u.must_change_password, u.created_at, u.updated_at FROM users u
INNER JOIN organization_members om ON u.id = om.user_id
WHERE om.organization_id = $1 AND om.active = true AND u.deleted_at IS NULL
ORDER BY u.name
LIMIT $2 OFFSET $3
`

type ListUsersByOrganizationParams struct {
	OrganizationID string `json:"organizationId"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListUsersByOrganization(ctx context.Context, arg ListUsersByOrganizationParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Password,
			&i.Role,
			&i.Active,
			&i.LastLogin,
			&i.CurrentOrganizationID,
			&i.IsSuperAdmin,
			&i.Preferences,
			&i.DeletedAt,
			&i.Position,
			&i.ManNumber,
			&i.NrcNumber,
			&i.Contact,
			&i.MfaEnabled,
			&i.IsLdapUser,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithDeleted = `-- name: ListUsersWithDeleted :many
SELECT id, email, name, password, role, active, last_login, current_organization_id, is_super_admin, preferences, deleted_at, position, man_number, nrc_number, contact, mfa_enabled, is_ldap_user, must_change_password, created_at, updated_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersWithDeletedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsersWithDeleted(ctx context.Context, arg ListUsersWithDeletedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersWithDeleted, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Password,
			&i.Role,
			&i.Active,
			&i.LastLogin,
			&i.CurrentOrganizationID,
			&i.IsSuperAdmin,
			&i.Preferences,
			&i.DeletedAt,
			&i.Position,
			&i.ManNumber,
			&i.NrcNumber,
			&i.Contact,
			&i.MfaEnabled,
			&i.IsLdapUser,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = NOW() WHERE id = $1
`

type SoftDeleteUserParams struct {
	ID string `json:"id"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteUser, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET 
    name = COALESCE($2, name),
    email = COALESCE($3, email),
    role = COALESCE($4, role),
    active = COALESCE($5, active),
    current_organization_id = COALESCE($6, current_organization_id),
    is_super_admin = COALESCE($7, is_super_admin),
    must_change_password = COALESCE($8, must_change_password),
    position = COALESCE($9, position),
    man_number = COALESCE($10, man_number),
    nrc_number = COALESCE($11, nrc_number),
    contact = COALESCE($12, contact),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, password, role, active, last_login, current_organization_id, is_super_admin, preferences, deleted_at, position, man_number, nrc_number, contact, mfa_enabled, is_ldap_user, must_change_password, created_at, updated_at
`

type UpdateUserParams struct {
	ID                    string  `json:"id"`
	Name                  string  `json:"name"`
	Email                 string  `json:"email"`
	Role                  string  `json:"role"`
	Active                bool    `json:"active"`
	CurrentOrganizationID *string `json:"currentOrganizationId"`
	IsSuperAdmin          bool    `json:"isSuperAdmin"`
	MustChangePassword    bool    `json:"mustChangePassword"`
	Position              *string `json:"position"`
	ManNumber             *string `json:"manNumber"`
	NrcNumber             *string `json:"nrcNumber"`
	Contact               *string `json:"contact"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Active,
		arg.CurrentOrganizationID,
		arg.IsSuperAdmin,
		arg.MustChangePassword,
		arg.Position,
		arg.ManNumber,
		arg.NrcNumber,
		arg.Contact,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.LastLogin,
		&i.CurrentOrganizationID,
		&i.IsSuperAdmin,
		&i.Preferences,
		&i.DeletedAt,
		&i.Position,
		&i.ManNumber,
		&i.NrcNumber,
		&i.Contact,
		&i.MfaEnabled,
		&i.IsLdapUser,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET 
    last_login = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserLastLoginParams struct {
	ID string `json:"id"`
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET 
    password = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       string `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}
