// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vendors.sql

package db

import (
	"context"
)

const countVendors = `-- name: CountVendors :one
SELECT COUNT(*) FROM vendors 
WHERE organization_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR name ILIKE $2)
  AND ($3::text = '' OR UPPER(active) = UPPER($3))
`

type CountVendorsParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
}

func (q *Queries) CountVendors(ctx context.Context, arg CountVendorsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVendors, arg.OrganizationID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (
    id, organization_id, name, vendor_code, email, phone, country, city,
    bank_account, bank_name, account_name, account_number, branch_code,
    swift_code, contact_person, physical_address, tax_id, active, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
) RETURNING id, organization_id, vendor_code, name, email, phone, country, city, bank_account, bank_name, account_name, account_number, branch_code, swift_code, contact_person, physical_address, tax_id, active, deleted_at, created_by, created_at, updated_at
`

type CreateVendorParams struct {
	ID              string  `json:"id"`
	OrganizationID  string  `json:"organizationId"`
	Name            string  `json:"name"`
	VendorCode      string  `json:"vendorCode"`
	Email           *string `json:"email"`
	Phone           *string `json:"phone"`
	Country         *string `json:"country"`
	City            *string `json:"city"`
	BankAccount     *string `json:"bankAccount"`
	BankName        string  `json:"bankName"`
	AccountName     string  `json:"accountName"`
	AccountNumber   string  `json:"accountNumber"`
	BranchCode      string  `json:"branchCode"`
	SwiftCode       string  `json:"swiftCode"`
	ContactPerson   string  `json:"contactPerson"`
	PhysicalAddress string  `json:"physicalAddress"`
	TaxID           *string `json:"taxId"`
	Active          *bool   `json:"active"`
	CreatedBy       *string `json:"createdBy"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, createVendor,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.VendorCode,
		arg.Email,
		arg.Phone,
		arg.Country,
		arg.City,
		arg.BankAccount,
		arg.BankName,
		arg.AccountName,
		arg.AccountNumber,
		arg.BranchCode,
		arg.SwiftCode,
		arg.ContactPerson,
		arg.PhysicalAddress,
		arg.TaxID,
		arg.Active,
		arg.CreatedBy,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VendorCode,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.City,
		&i.BankAccount,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
		&i.BranchCode,
		&i.SwiftCode,
		&i.ContactPerson,
		&i.PhysicalAddress,
		&i.TaxID,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorByCode = `-- name: GetVendorByCode :one
SELECT id, organization_id, vendor_code, name, email, phone, country, city, bank_account, bank_name, account_name, account_number, branch_code, swift_code, contact_person, physical_address, tax_id, active, deleted_at, created_by, created_at, updated_at FROM vendors WHERE organization_id = $1 AND vendor_code = $2 AND deleted_at IS NULL
`

type GetVendorByCodeParams struct {
	OrganizationID string `json:"organizationId"`
	VendorCode     string `json:"vendorCode"`
}

func (q *Queries) GetVendorByCode(ctx context.Context, arg GetVendorByCodeParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByCode, arg.OrganizationID, arg.VendorCode)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VendorCode,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.City,
		&i.BankAccount,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
		&i.BranchCode,
		&i.SwiftCode,
		&i.ContactPerson,
		&i.PhysicalAddress,
		&i.TaxID,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorByID = `-- name: GetVendorByID :one

SELECT id, organization_id, vendor_code, name, email, phone, country, city, bank_account, bank_name, account_name, account_number, branch_code, swift_code, contact_person, physical_address, tax_id, active, deleted_at, created_by, created_at, updated_at FROM vendors WHERE id = $1 AND deleted_at IS NULL
`

type GetVendorByIDParams struct {
	ID string `json:"id"`
}

// Vendor queries
// Organization-scoped vendor CRUD operations
func (q *Queries) GetVendorByID(ctx context.Context, arg GetVendorByIDParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByID, arg.ID)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VendorCode,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.City,
		&i.BankAccount,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
		&i.BranchCode,
		&i.SwiftCode,
		&i.ContactPerson,
		&i.PhysicalAddress,
		&i.TaxID,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveVendors = `-- name: ListActiveVendors :many
SELECT id, organization_id, vendor_code, name, email, phone, country, city, bank_account, bank_name, account_name, account_number, branch_code, swift_code, contact_person, physical_address, tax_id, active, deleted_at, created_by, created_at, updated_at FROM vendors 
WHERE organization_id = $1 AND deleted_at IS NULL AND active = true
ORDER BY name ASC
`

type ListActiveVendorsParams struct {
	OrganizationID string `json:"organizationId"`
}

func (q *Queries) ListActiveVendors(ctx context.Context, arg ListActiveVendorsParams) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, listActiveVendors, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.VendorCode,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Country,
			&i.City,
			&i.BankAccount,
			&i.BankName,
			&i.AccountName,
			&i.AccountNumber,
			&i.BranchCode,
			&i.SwiftCode,
			&i.ContactPerson,
			&i.PhysicalAddress,
			&i.TaxID,
			&i.Active,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendors = `-- name: ListVendors :many
SELECT id, organization_id, vendor_code, name, email, phone, country, city, bank_account, bank_name, account_name, account_number, branch_code, swift_code, contact_person, physical_address, tax_id, active, deleted_at, created_by, created_at, updated_at FROM vendors 
WHERE organization_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR name ILIKE $2)
  AND ($3::text = '' OR UPPER(active) = UPPER($3))
ORDER BY name ASC
LIMIT $4 OFFSET $5
`

type ListVendorsParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        string `json:"column2"`
	Column3        string `json:"column3"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListVendors(ctx context.Context, arg ListVendorsParams) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, listVendors,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.VendorCode,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Country,
			&i.City,
			&i.BankAccount,
			&i.BankName,
			&i.AccountName,
			&i.AccountNumber,
			&i.BranchCode,
			&i.SwiftCode,
			&i.ContactPerson,
			&i.PhysicalAddress,
			&i.TaxID,
			&i.Active,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVendor = `-- name: SoftDeleteVendor :exec
UPDATE vendors SET deleted_at = NOW() WHERE id = $1
`

type SoftDeleteVendorParams struct {
	ID string `json:"id"`
}

func (q *Queries) SoftDeleteVendor(ctx context.Context, arg SoftDeleteVendorParams) error {
	_, err := q.db.Exec(ctx, softDeleteVendor, arg.ID)
	return err
}

const updateVendor = `-- name: UpdateVendor :one
UPDATE vendors SET 
    name = COALESCE($2, name),
    vendor_code = COALESCE($3, vendor_code),
    email = COALESCE($4, email),
    phone = COALESCE($5, phone),
    country = COALESCE($6, country),
    city = COALESCE($7, city),
    bank_account = COALESCE($8, bank_account),
    bank_name = COALESCE($9, bank_name),
    account_name = COALESCE($10, account_name),
    account_number = COALESCE($11, account_number),
    branch_code = COALESCE($12, branch_code),
    swift_code = COALESCE($13, swift_code),
    contact_person = COALESCE($14, contact_person),
    physical_address = COALESCE($15, physical_address),
    tax_id = COALESCE($16, tax_id),
    active = COALESCE($17, active),
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, vendor_code, name, email, phone, country, city, bank_account, bank_name, account_name, account_number, branch_code, swift_code, contact_person, physical_address, tax_id, active, deleted_at, created_by, created_at, updated_at
`

type UpdateVendorParams struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	VendorCode      string  `json:"vendorCode"`
	Email           *string `json:"email"`
	Phone           *string `json:"phone"`
	Country         *string `json:"country"`
	City            *string `json:"city"`
	BankAccount     *string `json:"bankAccount"`
	BankName        string  `json:"bankName"`
	AccountName     string  `json:"accountName"`
	AccountNumber   string  `json:"accountNumber"`
	BranchCode      string  `json:"branchCode"`
	SwiftCode       string  `json:"swiftCode"`
	ContactPerson   string  `json:"contactPerson"`
	PhysicalAddress string  `json:"physicalAddress"`
	TaxID           *string `json:"taxId"`
	Active          *bool   `json:"active"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, updateVendor,
		arg.ID,
		arg.Name,
		arg.VendorCode,
		arg.Email,
		arg.Phone,
		arg.Country,
		arg.City,
		arg.BankAccount,
		arg.BankName,
		arg.AccountName,
		arg.AccountNumber,
		arg.BranchCode,
		arg.SwiftCode,
		arg.ContactPerson,
		arg.PhysicalAddress,
		arg.TaxID,
		arg.Active,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.VendorCode,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.City,
		&i.BankAccount,
		&i.BankName,
		&i.AccountName,
		&i.AccountNumber,
		&i.BranchCode,
		&i.SwiftCode,
		&i.ContactPerson,
		&i.PhysicalAddress,
		&i.TaxID,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
