// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimTask = `-- name: ClaimTask :one
UPDATE workflow_tasks
SET claimed_by   = $2,
    claimed_at   = NOW(),
    claim_expiry = $3,
    updated_by   = $2,
    version      = version + 1,
    updated_at   = NOW()
WHERE id = $1
  AND (claimed_by IS NULL OR claim_expiry < NOW())
RETURNING id, organization_id, workflow_assignment_id, entity_id, entity_type, stage_number, stage_name, assignment_type, assigned_role, assigned_user_id, status, priority, claimed_at, claimed_by, claim_expiry, completed_at, due_date, version, updated_by, created_at, updated_at
`

type ClaimTaskParams struct {
	ID          string             `json:"id"`
	ClaimedBy   *string            `json:"claimedBy"`
	ClaimExpiry pgtype.Timestamptz `json:"claimExpiry"`
}

func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) (WorkflowTask, error) {
	row := q.db.QueryRow(ctx, claimTask, arg.ID, arg.ClaimedBy, arg.ClaimExpiry)
	var i WorkflowTask
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkflowAssignmentID,
		&i.EntityID,
		&i.EntityType,
		&i.StageNumber,
		&i.StageName,
		&i.AssignmentType,
		&i.AssignedRole,
		&i.AssignedUserID,
		&i.Status,
		&i.Priority,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.ClaimExpiry,
		&i.CompletedAt,
		&i.DueDate,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countTasksByAssignee = `-- name: CountTasksByAssignee :one
SELECT COUNT(*) FROM workflow_tasks
WHERE organization_id = $1
  AND (assigned_user_id = $2 OR claimed_by = $2)
  AND ($3::text[] IS NULL OR status = ANY($3::text[]))
`

type CountTasksByAssigneeParams struct {
	OrganizationID string   `json:"organizationId"`
	AssignedUserID *string  `json:"assignedUserId"`
	Column3        []string `json:"column3"`
}

func (q *Queries) CountTasksByAssignee(ctx context.Context, arg CountTasksByAssigneeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByAssignee, arg.OrganizationID, arg.AssignedUserID, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO workflow_tasks (
    id, organization_id, workflow_assignment_id, entity_id, entity_type,
    stage_number, stage_name, assignment_type, assigned_role, assigned_user_id,
    status, priority, due_date, version, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, 1, $14
) RETURNING id, organization_id, workflow_assignment_id, entity_id, entity_type, stage_number, stage_name, assignment_type, assigned_role, assigned_user_id, status, priority, claimed_at, claimed_by, claim_expiry, completed_at, due_date, version, updated_by, created_at, updated_at
`

type CreateTaskParams struct {
	ID                   string             `json:"id"`
	OrganizationID       string             `json:"organizationId"`
	WorkflowAssignmentID string             `json:"workflowAssignmentId"`
	EntityID             string             `json:"entityId"`
	EntityType           string             `json:"entityType"`
	StageNumber          int32              `json:"stageNumber"`
	StageName            string             `json:"stageName"`
	AssignmentType       *string            `json:"assignmentType"`
	AssignedRole         *string            `json:"assignedRole"`
	AssignedUserID       *string            `json:"assignedUserId"`
	Status               *string            `json:"status"`
	Priority             *string            `json:"priority"`
	DueDate              pgtype.Timestamptz `json:"dueDate"`
	UpdatedBy            *string            `json:"updatedBy"`
}

// Workflow task queries
// Tasks emitted per workflow stage. Optimistic-locking via version column on update.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (WorkflowTask, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.OrganizationID,
		arg.WorkflowAssignmentID,
		arg.EntityID,
		arg.EntityType,
		arg.StageNumber,
		arg.StageName,
		arg.AssignmentType,
		arg.AssignedRole,
		arg.AssignedUserID,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.UpdatedBy,
	)
	var i WorkflowTask
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkflowAssignmentID,
		&i.EntityID,
		&i.EntityType,
		&i.StageNumber,
		&i.StageName,
		&i.AssignmentType,
		&i.AssignedRole,
		&i.AssignedUserID,
		&i.Status,
		&i.Priority,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.ClaimExpiry,
		&i.CompletedAt,
		&i.DueDate,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireStaleClaims = `-- name: ExpireStaleClaims :exec
UPDATE workflow_tasks
SET claimed_by   = NULL,
    claimed_at   = NULL,
    claim_expiry = NULL,
    updated_at   = NOW()
WHERE claimed_by IS NOT NULL
  AND claim_expiry IS NOT NULL
  AND claim_expiry < NOW()
`

func (q *Queries) ExpireStaleClaims(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireStaleClaims)
	return err
}

const getTaskByAssignment = `-- name: GetTaskByAssignment :one
SELECT id, organization_id, workflow_assignment_id, entity_id, entity_type, stage_number, stage_name, assignment_type, assigned_role, assigned_user_id, status, priority, claimed_at, claimed_by, claim_expiry, completed_at, due_date, version, updated_by, created_at, updated_at FROM workflow_tasks
WHERE workflow_assignment_id = $1 AND stage_number = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetTaskByAssignmentParams struct {
	WorkflowAssignmentID string `json:"workflowAssignmentId"`
	StageNumber          int32  `json:"stageNumber"`
}

func (q *Queries) GetTaskByAssignment(ctx context.Context, arg GetTaskByAssignmentParams) (WorkflowTask, error) {
	row := q.db.QueryRow(ctx, getTaskByAssignment, arg.WorkflowAssignmentID, arg.StageNumber)
	var i WorkflowTask
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkflowAssignmentID,
		&i.EntityID,
		&i.EntityType,
		&i.StageNumber,
		&i.StageName,
		&i.AssignmentType,
		&i.AssignedRole,
		&i.AssignedUserID,
		&i.Status,
		&i.Priority,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.ClaimExpiry,
		&i.CompletedAt,
		&i.DueDate,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, organization_id, workflow_assignment_id, entity_id, entity_type, stage_number, stage_name, assignment_type, assigned_role, assigned_user_id, status, priority, claimed_at, claimed_by, claim_expiry, completed_at, due_date, version, updated_by, created_at, updated_at FROM workflow_tasks WHERE id = $1
`

type GetTaskByIDParams struct {
	ID string `json:"id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (WorkflowTask, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID)
	var i WorkflowTask
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkflowAssignmentID,
		&i.EntityID,
		&i.EntityType,
		&i.StageNumber,
		&i.StageName,
		&i.AssignmentType,
		&i.AssignedRole,
		&i.AssignedUserID,
		&i.Status,
		&i.Priority,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.ClaimExpiry,
		&i.CompletedAt,
		&i.DueDate,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByAssignee = `-- name: ListTasksByAssignee :many
SELECT id, organization_id, workflow_assignment_id, entity_id, entity_type, stage_number, stage_name, assignment_type, assigned_role, assigned_user_id, status, priority, claimed_at, claimed_by, claim_expiry, completed_at, due_date, version, updated_by, created_at, updated_at FROM workflow_tasks
WHERE organization_id = $1
  AND (assigned_user_id = $2 OR claimed_by = $2)
  AND ($3::text[] IS NULL OR status = ANY($3::text[]))
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListTasksByAssigneeParams struct {
	OrganizationID string   `json:"organizationId"`
	AssignedUserID *string  `json:"assignedUserId"`
	Column3        []string `json:"column3"`
	Limit          int32    `json:"limit"`
	Offset         int32    `json:"offset"`
}

func (q *Queries) ListTasksByAssignee(ctx context.Context, arg ListTasksByAssigneeParams) ([]WorkflowTask, error) {
	rows, err := q.db.Query(ctx, listTasksByAssignee,
		arg.OrganizationID,
		arg.AssignedUserID,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowTask{}
	for rows.Next() {
		var i WorkflowTask
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkflowAssignmentID,
			&i.EntityID,
			&i.EntityType,
			&i.StageNumber,
			&i.StageName,
			&i.AssignmentType,
			&i.AssignedRole,
			&i.AssignedUserID,
			&i.Status,
			&i.Priority,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.ClaimExpiry,
			&i.CompletedAt,
			&i.DueDate,
			&i.Version,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByEntity = `-- name: ListTasksByEntity :many
SELECT id, organization_id, workflow_assignment_id, entity_id, entity_type, stage_number, stage_name, assignment_type, assigned_role, assigned_user_id, status, priority, claimed_at, claimed_by, claim_expiry, completed_at, due_date, version, updated_by, created_at, updated_at FROM workflow_tasks
WHERE organization_id = $1
  AND entity_id   = $2
  AND entity_type = $3
ORDER BY stage_number ASC, created_at DESC
`

type ListTasksByEntityParams struct {
	OrganizationID string `json:"organizationId"`
	EntityID       string `json:"entityId"`
	EntityType     string `json:"entityType"`
}

func (q *Queries) ListTasksByEntity(ctx context.Context, arg ListTasksByEntityParams) ([]WorkflowTask, error) {
	rows, err := q.db.Query(ctx, listTasksByEntity, arg.OrganizationID, arg.EntityID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowTask{}
	for rows.Next() {
		var i WorkflowTask
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkflowAssignmentID,
			&i.EntityID,
			&i.EntityType,
			&i.StageNumber,
			&i.StageName,
			&i.AssignmentType,
			&i.AssignedRole,
			&i.AssignedUserID,
			&i.Status,
			&i.Priority,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.ClaimExpiry,
			&i.CompletedAt,
			&i.DueDate,
			&i.Version,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTaskClaim = `-- name: ReleaseTaskClaim :exec
UPDATE workflow_tasks
SET claimed_by   = NULL,
    claimed_at   = NULL,
    claim_expiry = NULL,
    updated_at   = NOW()
WHERE id = $1
`

type ReleaseTaskClaimParams struct {
	ID string `json:"id"`
}

func (q *Queries) ReleaseTaskClaim(ctx context.Context, arg ReleaseTaskClaimParams) error {
	_, err := q.db.Exec(ctx, releaseTaskClaim, arg.ID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE workflow_tasks
SET status       = $2,
    completed_at = CASE WHEN $2 IN ('approved','rejected','completed') THEN NOW() ELSE completed_at END,
    updated_by   = $3,
    version      = version + 1,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, organization_id, workflow_assignment_id, entity_id, entity_type, stage_number, stage_name, assignment_type, assigned_role, assigned_user_id, status, priority, claimed_at, claimed_by, claim_expiry, completed_at, due_date, version, updated_by, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID        string  `json:"id"`
	Status    *string `json:"status"`
	UpdatedBy *string `json:"updatedBy"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (WorkflowTask, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Status, arg.UpdatedBy)
	var i WorkflowTask
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkflowAssignmentID,
		&i.EntityID,
		&i.EntityType,
		&i.StageNumber,
		&i.StageName,
		&i.AssignmentType,
		&i.AssignedRole,
		&i.AssignedUserID,
		&i.Status,
		&i.Priority,
		&i.ClaimedAt,
		&i.ClaimedBy,
		&i.ClaimExpiry,
		&i.CompletedAt,
		&i.DueDate,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
