// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateWorkflow = `-- name: ActivateWorkflow :one
UPDATE workflows
SET is_active = true,
    updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at
`

type ActivateWorkflowParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID string      `json:"organizationId"`
}

func (q *Queries) ActivateWorkflow(ctx context.Context, arg ActivateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, activateWorkflow, arg.ID, arg.OrganizationID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.EntityType,
		&i.Version,
		&i.Stages,
		&i.Conditions,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveWorkflows = `-- name: CountActiveWorkflows :one
SELECT COUNT(*) FROM workflows
WHERE organization_id = $1 AND is_active = true
`

type CountActiveWorkflowsParams struct {
	OrganizationID string `json:"organizationId"`
}

func (q *Queries) CountActiveWorkflows(ctx context.Context, arg CountActiveWorkflowsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWorkflows, arg.OrganizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkflows = `-- name: CountWorkflows :one
SELECT COUNT(*) FROM workflows
WHERE organization_id = $1
`

type CountWorkflowsParams struct {
	OrganizationID string `json:"organizationId"`
}

func (q *Queries) CountWorkflows(ctx context.Context, arg CountWorkflowsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflows, arg.OrganizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkflowsByDocumentType = `-- name: CountWorkflowsByDocumentType :one
SELECT COUNT(*) FROM workflows
WHERE organization_id = $1 AND document_type = $2
`

type CountWorkflowsByDocumentTypeParams struct {
	OrganizationID string `json:"organizationId"`
	DocumentType   string `json:"documentType"`
}

func (q *Queries) CountWorkflowsByDocumentType(ctx context.Context, arg CountWorkflowsByDocumentTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflowsByDocumentType, arg.OrganizationID, arg.DocumentType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkflowsByOrg = `-- name: CountWorkflowsByOrg :one
SELECT COUNT(*) FROM workflows
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::bool IS NULL OR is_active     = $2)
  AND ($3::text = ''   OR document_type  = $3)
`

type CountWorkflowsByOrgParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        bool   `json:"column2"`
	Column3        string `json:"column3"`
}

func (q *Queries) CountWorkflowsByOrg(ctx context.Context, arg CountWorkflowsByOrgParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflowsByOrg, arg.OrganizationID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (
    id,
    organization_id,
    name,
    description,
    document_type,
    stages,
    is_active,
    created_by,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, NOW(), NOW()
)
RETURNING id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at
`

type CreateWorkflowParams struct {
	OrganizationID string          `json:"organizationId"`
	Name           string          `json:"name"`
	Description    *string         `json:"description"`
	DocumentType   string          `json:"documentType"`
	Stages         json.RawMessage `json:"stages"`
	IsActive       *bool           `json:"isActive"`
	CreatedBy      *string         `json:"createdBy"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.DocumentType,
		arg.Stages,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.EntityType,
		&i.Version,
		&i.Stages,
		&i.Conditions,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateWorkflow = `-- name: DeactivateWorkflow :one
UPDATE workflows
SET is_active = false,
    updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at
`

type DeactivateWorkflowParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID string      `json:"organizationId"`
}

func (q *Queries) DeactivateWorkflow(ctx context.Context, arg DeactivateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, deactivateWorkflow, arg.ID, arg.OrganizationID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.EntityType,
		&i.Version,
		&i.Stages,
		&i.Conditions,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows
WHERE id = $1 AND organization_id = $2
`

type DeleteWorkflowParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID string      `json:"organizationId"`
}

func (q *Queries) DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, arg.ID, arg.OrganizationID)
	return err
}

const getDefaultWorkflowByDocumentType = `-- name: GetDefaultWorkflowByDocumentType :one
SELECT id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at FROM workflows
WHERE organization_id = $1 AND document_type = $2 AND is_active = true
ORDER BY created_at DESC
LIMIT 1
`

type GetDefaultWorkflowByDocumentTypeParams struct {
	OrganizationID string `json:"organizationId"`
	DocumentType   string `json:"documentType"`
}

func (q *Queries) GetDefaultWorkflowByDocumentType(ctx context.Context, arg GetDefaultWorkflowByDocumentTypeParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getDefaultWorkflowByDocumentType, arg.OrganizationID, arg.DocumentType)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.EntityType,
		&i.Version,
		&i.Stages,
		&i.Conditions,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at FROM workflows
WHERE id = $1 AND organization_id = $2
`

type GetWorkflowByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID string      `json:"organizationId"`
}

func (q *Queries) GetWorkflowByID(ctx context.Context, arg GetWorkflowByIDParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByID, arg.ID, arg.OrganizationID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.EntityType,
		&i.Version,
		&i.Stages,
		&i.Conditions,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWorkflows = `-- name: ListActiveWorkflows :many
SELECT id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at FROM workflows
WHERE organization_id = $1 AND is_active = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveWorkflowsParams struct {
	OrganizationID string `json:"organizationId"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListActiveWorkflows(ctx context.Context, arg ListActiveWorkflowsParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listActiveWorkflows, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.DocumentType,
			&i.EntityType,
			&i.Version,
			&i.Stages,
			&i.Conditions,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveWorkflowsByDocumentType = `-- name: ListActiveWorkflowsByDocumentType :many
SELECT id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at FROM workflows
WHERE organization_id = $1 AND document_type = $2 AND is_active = true
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListActiveWorkflowsByDocumentTypeParams struct {
	OrganizationID string `json:"organizationId"`
	DocumentType   string `json:"documentType"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListActiveWorkflowsByDocumentType(ctx context.Context, arg ListActiveWorkflowsByDocumentTypeParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listActiveWorkflowsByDocumentType,
		arg.OrganizationID,
		arg.DocumentType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.DocumentType,
			&i.EntityType,
			&i.Version,
			&i.Stages,
			&i.Conditions,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at FROM workflows
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkflowsParams struct {
	OrganizationID string `json:"organizationId"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.DocumentType,
			&i.EntityType,
			&i.Version,
			&i.Stages,
			&i.Conditions,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsByDocumentType = `-- name: ListWorkflowsByDocumentType :many
SELECT id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at FROM workflows
WHERE organization_id = $1 AND document_type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListWorkflowsByDocumentTypeParams struct {
	OrganizationID string `json:"organizationId"`
	DocumentType   string `json:"documentType"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListWorkflowsByDocumentType(ctx context.Context, arg ListWorkflowsByDocumentTypeParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflowsByDocumentType,
		arg.OrganizationID,
		arg.DocumentType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.DocumentType,
			&i.EntityType,
			&i.Version,
			&i.Stages,
			&i.Conditions,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsByOrg = `-- name: ListWorkflowsByOrg :many
SELECT id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at FROM workflows
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND ($2::bool IS NULL OR is_active     = $2)
  AND ($3::text = ''   OR document_type  = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListWorkflowsByOrgParams struct {
	OrganizationID string `json:"organizationId"`
	Column2        bool   `json:"column2"`
	Column3        string `json:"column3"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListWorkflowsByOrg(ctx context.Context, arg ListWorkflowsByOrgParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflowsByOrg,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.DocumentType,
			&i.EntityType,
			&i.Version,
			&i.Stages,
			&i.Conditions,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkflow = `-- name: SoftDeleteWorkflow :exec
UPDATE workflows
SET deleted_at = NOW(),
    is_active  = false,
    updated_at = NOW()
WHERE id = $1 AND organization_id = $2
`

type SoftDeleteWorkflowParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID string      `json:"organizationId"`
}

func (q *Queries) SoftDeleteWorkflow(ctx context.Context, arg SoftDeleteWorkflowParams) error {
	_, err := q.db.Exec(ctx, softDeleteWorkflow, arg.ID, arg.OrganizationID)
	return err
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows
SET name = $3,
    description = $4,
    stages = $5,
    updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, description, document_type, entity_type, version, stages, conditions, is_active, is_default, created_by, deleted_at, created_at, updated_at
`

type UpdateWorkflowParams struct {
	ID             pgtype.UUID     `json:"id"`
	OrganizationID string          `json:"organizationId"`
	Name           string          `json:"name"`
	Description    *string         `json:"description"`
	Stages         json.RawMessage `json:"stages"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Stages,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DocumentType,
		&i.EntityType,
		&i.Version,
		&i.Stages,
		&i.Conditions,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
