// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_assignments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAssignmentsByWorkflow = `-- name: CountAssignmentsByWorkflow :one
SELECT COUNT(*) FROM workflow_assignments
WHERE organization_id = $1 AND workflow_id = $2
`

type CountAssignmentsByWorkflowParams struct {
	OrganizationID string      `json:"organizationId"`
	WorkflowID     pgtype.UUID `json:"workflowId"`
}

func (q *Queries) CountAssignmentsByWorkflow(ctx context.Context, arg CountAssignmentsByWorkflowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignmentsByWorkflow, arg.OrganizationID, arg.WorkflowID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssignment = `-- name: CreateAssignment :one

INSERT INTO workflow_assignments (
    id, organization_id, entity_id, entity_type, workflow_id, workflow_version,
    current_stage, status, stage_history, assigned_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, organization_id, entity_id, entity_type, workflow_id, workflow_version, current_stage, status, stage_history, assigned_at, assigned_by, completed_at, created_at, updated_at
`

type CreateAssignmentParams struct {
	ID              string      `json:"id"`
	OrganizationID  string      `json:"organizationId"`
	EntityID        string      `json:"entityId"`
	EntityType      string      `json:"entityType"`
	WorkflowID      pgtype.UUID `json:"workflowId"`
	WorkflowVersion int32       `json:"workflowVersion"`
	CurrentStage    *int32      `json:"currentStage"`
	Status          *string     `json:"status"`
	StageHistory    []byte      `json:"stageHistory"`
	AssignedBy      string      `json:"assignedBy"`
}

// Workflow assignment queries
// An assignment binds an entity (e.g. a requisition) to a specific workflow version.
func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (WorkflowAssignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.ID,
		arg.OrganizationID,
		arg.EntityID,
		arg.EntityType,
		arg.WorkflowID,
		arg.WorkflowVersion,
		arg.CurrentStage,
		arg.Status,
		arg.StageHistory,
		arg.AssignedBy,
	)
	var i WorkflowAssignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntityID,
		&i.EntityType,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.CurrentStage,
		&i.Status,
		&i.StageHistory,
		&i.AssignedAt,
		&i.AssignedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentByEntity = `-- name: GetAssignmentByEntity :one
SELECT id, organization_id, entity_id, entity_type, workflow_id, workflow_version, current_stage, status, stage_history, assigned_at, assigned_by, completed_at, created_at, updated_at FROM workflow_assignments
WHERE organization_id = $1
  AND entity_id       = $2
  AND entity_type     = $3
ORDER BY created_at DESC
LIMIT 1
`

type GetAssignmentByEntityParams struct {
	OrganizationID string `json:"organizationId"`
	EntityID       string `json:"entityId"`
	EntityType     string `json:"entityType"`
}

func (q *Queries) GetAssignmentByEntity(ctx context.Context, arg GetAssignmentByEntityParams) (WorkflowAssignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentByEntity, arg.OrganizationID, arg.EntityID, arg.EntityType)
	var i WorkflowAssignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntityID,
		&i.EntityType,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.CurrentStage,
		&i.Status,
		&i.StageHistory,
		&i.AssignedAt,
		&i.AssignedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT id, organization_id, entity_id, entity_type, workflow_id, workflow_version, current_stage, status, stage_history, assigned_at, assigned_by, completed_at, created_at, updated_at FROM workflow_assignments WHERE id = $1
`

type GetAssignmentByIDParams struct {
	ID string `json:"id"`
}

func (q *Queries) GetAssignmentByID(ctx context.Context, arg GetAssignmentByIDParams) (WorkflowAssignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentByID, arg.ID)
	var i WorkflowAssignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntityID,
		&i.EntityType,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.CurrentStage,
		&i.Status,
		&i.StageHistory,
		&i.AssignedAt,
		&i.AssignedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignmentsByEntity = `-- name: ListAssignmentsByEntity :many
SELECT id, organization_id, entity_id, entity_type, workflow_id, workflow_version, current_stage, status, stage_history, assigned_at, assigned_by, completed_at, created_at, updated_at FROM workflow_assignments
WHERE organization_id = $1
  AND entity_id       = $2
  AND entity_type     = $3
ORDER BY created_at DESC
`

type ListAssignmentsByEntityParams struct {
	OrganizationID string `json:"organizationId"`
	EntityID       string `json:"entityId"`
	EntityType     string `json:"entityType"`
}

func (q *Queries) ListAssignmentsByEntity(ctx context.Context, arg ListAssignmentsByEntityParams) ([]WorkflowAssignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByEntity, arg.OrganizationID, arg.EntityID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowAssignment{}
	for rows.Next() {
		var i WorkflowAssignment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EntityID,
			&i.EntityType,
			&i.WorkflowID,
			&i.WorkflowVersion,
			&i.CurrentStage,
			&i.Status,
			&i.StageHistory,
			&i.AssignedAt,
			&i.AssignedBy,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentsByWorkflow = `-- name: ListAssignmentsByWorkflow :many
SELECT id, organization_id, entity_id, entity_type, workflow_id, workflow_version, current_stage, status, stage_history, assigned_at, assigned_by, completed_at, created_at, updated_at FROM workflow_assignments
WHERE organization_id = $1 AND workflow_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAssignmentsByWorkflowParams struct {
	OrganizationID string      `json:"organizationId"`
	WorkflowID     pgtype.UUID `json:"workflowId"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListAssignmentsByWorkflow(ctx context.Context, arg ListAssignmentsByWorkflowParams) ([]WorkflowAssignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByWorkflow,
		arg.OrganizationID,
		arg.WorkflowID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowAssignment{}
	for rows.Next() {
		var i WorkflowAssignment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EntityID,
			&i.EntityType,
			&i.WorkflowID,
			&i.WorkflowVersion,
			&i.CurrentStage,
			&i.Status,
			&i.StageHistory,
			&i.AssignedAt,
			&i.AssignedBy,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignmentStatus = `-- name: UpdateAssignmentStatus :one
UPDATE workflow_assignments
SET status        = $2,
    current_stage = COALESCE($3, current_stage),
    stage_history = COALESCE($4, stage_history),
    completed_at  = CASE WHEN $2 IN ('completed','approved','rejected','cancelled') THEN NOW() ELSE completed_at END,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, organization_id, entity_id, entity_type, workflow_id, workflow_version, current_stage, status, stage_history, assigned_at, assigned_by, completed_at, created_at, updated_at
`

type UpdateAssignmentStatusParams struct {
	ID           string  `json:"id"`
	Status       *string `json:"status"`
	CurrentStage *int32  `json:"currentStage"`
	StageHistory []byte  `json:"stageHistory"`
}

func (q *Queries) UpdateAssignmentStatus(ctx context.Context, arg UpdateAssignmentStatusParams) (WorkflowAssignment, error) {
	row := q.db.QueryRow(ctx, updateAssignmentStatus,
		arg.ID,
		arg.Status,
		arg.CurrentStage,
		arg.StageHistory,
	)
	var i WorkflowAssignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntityID,
		&i.EntityType,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.CurrentStage,
		&i.Status,
		&i.StageHistory,
		&i.AssignedAt,
		&i.AssignedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
