/**
 * Goods Received Note (GRN) Types
 * Aligned with backend models and database schema
 */

// Import shared types from core
import type {
  ItemCondition,
  QualityIssueType,
  QualityIssueSeverity,
} from "./core";

// ============================================================================
// CORE GRN TYPES
// ============================================================================

export interface GRNItem {
  id?: string; // Optional for new items
  description: string;
  quantityOrdered: number;
  quantityReceived: number;
  variance: number;
  condition: string; // good, damaged, missing
  notes?: string;
}

export interface QualityIssue {
  id?: string; // Optional for new issues, generated by backend
  itemDescription: string;
  issueType: string; // damaged, missing, wrong_item, quality_issue
  description: string;
  severity: string; // low, medium, high
}

export interface GoodsReceivedNote {
  // Core fields
  id: string;
  organizationId: string;
  documentNumber: string;
  poDocumentNumber: string;
  status: "DRAFT" | "PENDING" | "CONFIRMED" | "REJECTED" | "APPROVED" | "COMPLETED" | "CANCELLED"; // Stored as UPPERCASE
  receivedDate: Date;
  receivedBy: string;
  items: GRNItem[];
  qualityIssues: QualityIssue[];
  approvalStage: number;
  approvalHistory: any[];
  createdAt: Date;
  updatedAt: Date;

  // Budget tracking fields (propagated from linked PO)
  budgetCode: string;
  costCenter: string;
  projectCode: string;

  // Business requirement fields
  createdBy: string;
  ownerId: string; // Same as createdBy
  warehouseLocation: string;
  notes: string;
  currentStage: number; // Same as approvalStage
  stageName: string;
  approvedBy: string;
  automationUsed?: boolean; // For automation tracking
  autoCreatedPV?: any; // Auto-created payment voucher
  /** Payment-first flow: PV document number that was approved/paid before goods were received */
  linkedPV?: string;

  // UI compatibility fields
  actionHistory?: any[];
  metadata?: Record<string, any>;
  type?: string;
  createdByUser?: any;
}

// ============================================================================
// REQUEST TYPES
// ============================================================================

export interface CreateGRNRequest {
  poDocumentNumber: string;
  items: GRNItem[];
  receivedBy: string;
  warehouseLocation: string;
  notes: string;
  createdBy: string;
  /** Payment-first flow: PV document number that was approved/paid before goods were received */
  linkedPV?: string;
}

export interface UpdateGRNRequest {
  grnId: string;
  items?: GRNItem[];
  receivedBy?: string;
  qualityIssues?: QualityIssue[];
  warehouseLocation?: string;
  notes?: string;
}

export interface SubmitGRNRequest {
  grnId: string;
  workflowId: string; // REQUIRED - Workflow to use for approval
  submittedBy: string;
  submittedByName: string;
  submittedByRole: string;
  comments?: string;
}

export interface ApproveGRNRequest {
  grnId: string;
  approvingUserId: string;
  approvingUserName: string;
  approvingUserRole: string;
  signature: string;
  comments?: string;
}

export interface RejectGRNRequest {
  grnId: string;
  rejectingUserId: string;
  rejectingUserName: string;
  rejectingUserRole: string;
  remarks: string;
  signature: string;
  comments?: string;
}

// ============================================================================
// STATISTICS TYPES
// ============================================================================

export interface GRNStats {
  total: number;
  draft: number;
  pending: number;
  approved: number;
  thisMonth: number;
}

// ============================================================================
// TYPE ALIASES
// ============================================================================

export type GRNStatus =
  | "DRAFT"
  | "PENDING"
  | "APPROVED"
  | "REJECTED"
  | "PAID"
  | "COMPLETED"
  | "CANCELLED";
// Re-export shared types from core
export type {
  ItemCondition,
  QualityIssueType,
  QualityIssueSeverity,
} from "./core";
